### ISSUE TITLE
Build errors when using beta2 nuget package

### ISSUE THREAD

**Issue by rboada04** [Microsoft/aspnet-api-versioning#114]
I wanted to try out the beta2 for swagger support; however, when I add the beta2 nuget package and follow the documentation, I get build errors.

For example, when I added the following to ConfigureServices() startup.cs:
services.AddMvcCore().AddVersionedApiExplorer();

I get error:
'IMvcCoreBuilder' does not contain a definition for 'AddVersionedApiExplorer' and no extension method 'AddVersionedApiExplorer' accepting a first argument of type 'IMvcCoreBuilder' could be found (are you missing a using directive or an assembly reference?)

Is another nuget package needed?

**Comment by commonsensesoftware** [comment]
I think you're looking  [ASP.NET Core Versioned API Explorer](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer) which you can also find by clicking on the [wiki](../wiki/API-Documentation#aspnet-core) topic title.

**Comment by rboada04** [comment]
Yes, I had to add the Microsoft.AspNetCore.Mvc.Versioning 1.0.0-beta1 nuget package to get it working. Thanks for the resply
