### ISSUE TITLE
Support to be able to version interfaces

### ISSUE THREAD

**Issue by triumlabs** [Microsoft/aspnet-api-versioning#125]
Currently, ApiVersionAttribute, ApiVersionNeutralAttribute etc. can be only used on class level, but if you are using interfaces to declare WebApi routes (to take advantage of dependency injection and interception), the interface itself cannot be marked with e.g. ApiVersionAttribute.

Is it possible to allow interface usage for these versioning attributes?

Thanks in advance,

**Comment by commonsensesoftware** [comment]
To my knowledge, Web API does not consider attributes from interfaces. Attributes are discovered and collected by **HttpControllerDescriptor** and **HttpActionDescriptor**. There is probably a way to make it work, but you'd have to swap out some fundamental components.

There must be something about your scenario that I'm missing. If the attributes are placed on the interface, then that means multiple services _may_ have the same API versions. Ambiguous API versions will lead to runtime exceptions. At the end of the day, regardless of DI, the implemented API versions should be on the concrete type, not the interface. The infrastructure won't understand anything about the interfaces. Attributes are usually collected using **Object.GetType()**, which will return the implementation type, not the interface type. Ultimately, API versioning doesn't use Reflection directly. It relies solely on the Web API descriptor types.

I should also point out that API versioning doesn't care about attributes either. All of it's work is done by inspecting implementations of **IApiVersionProvider**. One of the ways this is realized is by attributes. This can also be realized using [conventions](../wiki/API-Version-Conventions). Based on your description, using conventions might be a better way to go for you.

I hope that helps get you started.

**Comment by triumlabs** [comment]
Let me than provide more information about my scenario.
I have a server side solution that can provide the same set of services either via WCF or WebAPI and can be hosted either via IIS or via windows service. The solution is highly decoupled, heavily depends on DI, to support testability and aspect oriented programing (via interception, aspects like tracing, security and exception handling etc.).

In the world of WCF, you can separate the service declaration from its implementation(s), meaining you can define the required ServiceContract, OperationContract etc. attributes on a service interface once and pick the appropriate service class at runtime (DI). So, if tests require to mock WCF service right after the WCF message arrived to the given operation, it is easy to achieve.

Based on this approach, in the world of WebAPI, I managed to decouple service definition and its implementation(s). So routes are defined on interfaces (each controller has one dedicated interface, no multiple inheritance) and the appropriate implementation is picked upon runtime again.
Of course, to be able to use interfaces as "controllers", I had to change WebAPI configuration to customize service IHttpControllerTypeResolver and replace DependencyResolver (at the moment it is Unity).

So far so good. But I started to think about some cool solution for versioning, so I decided to use this package and I run into an issue, that API versioning inspecting the controller type it receives for IApiVersionProvider, but in my case, it is the interface and not the controller class! (I know it looks for impl. of IApiVersionProvider, but it calls GetCustomAttributes<T> ... so it looks for attributes at the end)
I managed to build this package from source and by changing only attribute usage for ApiVersionAttribute and ApiVersionNeutralAttribute completely solved my problem. So I thought, you could also consider to include this enhancements into API versioning. (Just for the records, it could be also nice if RoutePrefixAttribute could be also placed on interfaces and not just class).

About conventions you mentioned, I have to check it as I don't know anything about conventions at the moment.

Regards

**Comment by commonsensesoftware** [comment]
Hmm... I think I understand. If I'm not mistaken, you're using direct routing (aka attribute routing), but everything is declared at the method level because you can't apply RouteAttribute or RoutePrefixAttribute on the interface itself. You've then swapped out the type and dependency resolver so that you can resolve _IMyController_ as a concrete controller via DI.

Aside from conventions, since the libraries don't directly care about attributes, did you know that you can create your own attributes? The **ApiVersionNeutralAttribute** is intentionally sealed, but you can extend **ApiVersionAttribute**. You can also extend the **ApiVersionsBaseAttribute** base class and apply **IApiVersionProvider** to it. Alternatively, you can roll your own attributes completely from scratch; you just need to implement the expected interfaces.

For example:

```c#
[AttributeUsage( AttributeTargets.Interface, AllowMultiple = false, Inherited = false )]
public sealed class CustomApiVersionNeutralAttribute : Attribute, IApiVersionNeutral
{
}

[AttributeUsage( AttributeTargets.Interface, AllowMultiple = false, Inherited = false )]
public sealed class CustomApiVersionAttribute : ApiVersionsBaseAttribute, IApiVersionProvider
{
  public CustomApiVersionAttribute( string version ) : base( version ) { }
  bool IApiVersionProvider.AdvertiseOnly => false;
  public bool Deprecated { get; set; }
}
```

Would this capability not work for you?

**Comment by triumlabs** [comment]
First, you correctly understood my situation/environment.
Secondly, custom attribute is a great idea, thanks a lot, I own you. It simple works, so I can use again the versioning library from NuGet repository.

Additionally, this custom attribute trick could be also used in case of RoutePrefixAttribute, which greatly simplifies attribute routing.

Thanks again and BR,
