### ISSUE TITLE
TypelLoadException in RC 1.0.0

### ISSUE THREAD

**Issue by gorillapower** [Microsoft/aspnet-api-versioning#129]
Im getting a TypeLoadException when attempting to use `config.AddODataApiExplorer`. 

Using:
Microsoft.AspNet.OData.Versioning 2.1.0.0
Microsoft.AspNet.OData.Versioning.ApiExplorer 1.0.0.0
Microsoft.AspNet.WebApi.Versioning 2.1.0.0
Microsoft.AspNet.WebApi.Versioning.ApiExplorer 1.0.0.0

![image](https://cloud.githubusercontent.com/assets/8879065/26241703/f5f2fca6-3c85-11e7-9102-63ab0c2dc56f.png)

I also get this warning/error when trying to follow the OData sample code.

![image](https://cloud.githubusercontent.com/assets/8879065/26242429/b7f5d4e8-3c88-11e7-8058-5147b82203b8.png)

Am i missing something obvious here?

**Comment by commonsensesoftware** [comment]
It seems like you have a stale set of references. Try the following:

* Make sure that **all** packages are for RC1 (stating the obvious, but I think you've already done that)
* Delete all cached and/or downloaded packages
* Delete all **bin** and **obj** folders in your solution
* Rebuild

If that doesn't work I can dig further. A simple project that reproduces the problem will be useful.

**Comment by commonsensesoftware** [comment]
Was this issue resolved? Are both libraries on the RC?

**Comment by gorillapower** [comment]
Hi Chris,

Apologies, yes this was resolved. I recreated my project and the references
started behaving, I'm not sure why it happened. You may close this.

Thank you!

**Comment by commonsensesoftware** [comment]
Great. Just wanted to make sure you were sorted out. Thanks for confirming.
