### ISSUE TITLE
ApiVersionNeutral always returns 404 error

### ISSUE THREAD

**Issue by mdmoura** [Microsoft/aspnet-api-versioning#137]
I have the following controller:

      [ApiVersionNeutral]
      [Route( "api/[controller]" )]
      public class HealthController : Controller
      {
          [HttpGet("ping")]
          public IActionResult Ping() => Ok("Pinged");
      }

When I access /api/health/ping without AddApiVersioning it works fine ... When I add

     services.AddApiVersioning();

To startup I start getting a 404 error ... Shouldn't still be accessible ?

**Comment by commonsensesoftware** [comment]
Which package version are you using? If it's any of the release candidates, you'll now need the following additional startup configuration:

```c#
app.UseMvc();
app.UseApiVersioning();
```

I had this documented in the release notes, but apparently not in the wiki yet. I just updated it. Sorry for any confusion. I setup a repro of your scenario with RC2 and everything seems ok. Give it a whirl and let me know if you run into any problems.

**Comment by mdmoura** [comment]
@commonsensesoftware I am using RC2 and I was missing the UseApiVersioning(). Thank you.

BTW, is it possible to change the argument name apiVersion to something else:

    [Route( "api/v{version:apiVersion}/helloworld" )]
    public class HelloWorldController : ApiController {
    }

So it would become something like:

    [Route( "api/v{version:XYZ}/helloworld" )]
    public class HelloWorldController : ApiController {
    }

Just out of curiosity ...

**Comment by commonsensesoftware** [comment]
Great. To be clear, did that fix your problem?

Yes, you can change the parameter name, but you have the _naming_ concepts reversed.  The name of the parameter is **version**. The value **apiVersion** the key for the **ApiVersionRouteConstraint** that is automatically registered for you in ASP.NET Core (but not Web API). Today, there is no way to configure that. I've considered allowing people to configure it, but - honestly - there's not much value in it.

You're free to change the route parameter value name all you want. Here's a few examples:

* `api/v{ver:apiVersion}/helloworld`
* `api/v{xyz:apiVersion}/helloworld`

If you have specific need or use case to change the key-to-route constraint mapping, I'm willing to entertain the idea. I don't like _over-configuration_, so I've tried to avoid frivolous configuration options that that really only put you in a state to get yourself into trouble (e.g. not working).

I hope that helps clear things up.

**Comment by mdmoura** [comment]
> Great. To be clear, did that fix your problem?

Yes, it solved it ... Thank you.

About changing the apiVersion parameter name I was just confirming if it was possible to change.

It might be useful to be able to have another name specially with auto generation API docs such as Swagger.

**Comment by commonsensesoftware** [comment]
1. Thanks for confirming.
2. Today, the _api version_ parameter, whatever name or location may contain it, is not discovered by the API explorer - yet. This is something that I'm actively thinking about, but it may not be available until the next release. That being said, for today, you can use whatever name you like (see the Swagger examples). In the ideal future, one or more _api version_ parameters will be added to the _api description_ that contains the name[s] of the parameters. These will always be the names you specify whether it be from the query string, header, route parameter, and so on.  The value **apiVersion** is just the route constraint key; it's not the name.  It's no different that if you had `v{version:int}` for `v1` or `v2`. The route parameter name is still **version** in both cases.  If you don't like the name **version**, you can replace it with whatever name you like. =)

**Comment by sando330** [comment]
Appologies for spam. Thank you for this post. Most of internet resourses, including Pluralsight use AddApiVersioning.

**Comment by commonsensesoftware** [comment]
@sando330 `UseApiVersioning` is a new requirement starting in ASP.NET Core (only) 1.1. You need both `services.AddApiVersioning` and `app.UseApiVersioning`. I hope that clears things up.
