### ISSUE TITLE
AspNetCore: Unable to identify UseApiVersioning and object that are in Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer

### ISSUE THREAD

**Issue by AbhinavMukesh** [Microsoft/aspnet-api-versioning#138]
Hi,
I am trying to use the Nuget package source (Microsoft.AspNetCore.Mvc.Versioning -Version 1.0.3) in my ASP.Net Core Web API project. When I tried to add app.UseApiVersioning() in my Configure method, the code is unable to identify this extension method. 

I also looked into the Sample projects and tried to use Swagger the way you have used. But ran into several compilation issues as Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer is not coming along with the Versioning package restore. 

Can you please verify this and suggest to resolve the issue.

Regards,
Abhinav

**Comment by commonsensesoftware** [comment]
These features were introduced in version 1.1, which is still in the release candidate state. You'll have to use the pre-release package for now if you'd like to take advantage of them. There are only one or two final issues left to resolve and verify. RC3 for ASP.NET Core will likely go out later today. If all goes well, I'll promote 1.1 to the official release by the end of the week. My apologies for any confusion.

**Comment by commonsensesoftware** [comment]
It seems this question has been answered. The official build is nearly here. Keep an eye for it. Let me know if you have any other questions.
