### ISSUE TITLE
Distinguish same route actions. 

### ISSUE THREAD

**Issue by SashaBezugliy** [Microsoft/aspnet-api-versioning#141]
Hi @commonsensesoftware,
I want to make IApiExplorer contain both methods. Actions have the same route, thus i get only one action in IApiExplorer collection. So, the problem is that in Swashbuckle, for v8 document i will always get v6 action.

`    [MapToApiVersion("6.0")]`
`    [Route("items")]`
`   public  Task<Item> PostItemsAsync([FromBody] Item item)    {    }`

`    [MapToApiVersion("8.0")]`
`    [Route("items")]`
`    public Task<ItemV8> PostItemAsyncV8([FromBody] ItemV8 item)    {    }`

I use Centralized route prefix to mark version:

`    public class CentralizedPrefixProvider : DefaultDirectRouteProvider`
    `{`
          ` private readonly string _centralizedPrefix;`
   `        public CentralizedPrefixProvider(string centralizedPrefix)`
   `        {            _centralizedPrefix = centralizedPrefix;        }`

   `        protected override string GetRoutePrefix(HttpControllerDescriptor controllerDescriptor)`
   `        {            return _centralizedPrefix;        }`
`    }`

usage:
`config.MapHttpAttributeRoutes(constraintResolver, new CentralizedPrefixProvider("v{version:apiVersion}"));`

Corresponding issue #https://github.com/domaindrivendev/Swashbuckle/issues/1057

**Comment by commonsensesoftware** [comment]
A couple of questions for you:

1. Are you using the **IApiExplorer** provided by API versioning?
2. If yes, are things not working?

The API version aware API explorer will list both actions and bucketize them by API version. The results will look like:

* API Version 6.0
   * Description: `POST v6/items`
* API Version 8.0
   * Description: `POST v8/items`

**Comment by SashaBezugliy** [comment]
@commonsensesoftware great thanks. 
Sample with using AspNet.Versionig.VersionExplorer and Swashbuckle was exactly what i needed.
