### ISSUE TITLE
v1.1.0 breaks AllowAnonymous attribute behavior

### ISSUE THREAD

**Issue by EPinci** [Microsoft/aspnet-api-versioning#143]
Hello there,

I have a project with this authorization policy:

````csharp
    services.AddMvc(opt =>
    {
        if (env.IsProduction())
        {
            opt.Filters.Add(new RequireHttpsAttribute());
            opt.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));
        }
    });
    services.AddApiVersioning();
````

And a controller with these attributes:

````csharp
    [ApiVersionNeutral]
    [Route("[controller]")]
    [AllowAnonymous]
    public class StatusController : Controller
````

**With v1.0.3 this works fine**: the status controller is exempted from versioning and is anonymously accessible while all other controllers require authentication.
**Upgrading just the versioning package to v1.1.0 breaks this behavior**: it now looks like the AllowAnonymous is now ignored. See app logs:

> info:  Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>      Request starting HTTP/1.1 GET http://[host-omitted]/status  
>info: IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMiddleware[7]
>      Bearer was not authenticated. Failure message: No token found.
>info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>      Request finished in 301.6292ms 404 

**Rolling back to v1.0.3 restores the initial correct behavior**.
Is it a bug or am I missing something?

Thank you.

**Comment by commonsensesoftware** [comment]
There is a breaking, behavioral change starting in the 1.1 release candidate. I tried to get around it, but I couldn't find a way without sacrificing a bunch of intrinsic ASP.NET Core behaviors. Unfortunately, that change has been catching a lot of folks off guard. I've tried to call it out as loudly as possible in the release notes and I've updated all the wiki documentation.

In your setup, you now, also need:

```c#
app.UseMvc();
app.UseApiVersioning();
```

I suspect that may be the issue. Let me know if it's not and I'll investigate further.

**Comment by EPinci** [comment]
Yes, that was it, now everything is back in order. Thank you!

I did try to look or breaking changes both in the wiki (...tidy and great!) and in the release description but I didn't scroll thru the RC although now I see it is mentioned that "every previous release note apply" (I didn't extend that comment to pre-releases). You might want to consider rephrasing that statement to include the catchy "breaking changes" wording and making it a quote as you did in the one below it to have it stand up. :)

Thank you again!

**Comment by commonsensesoftware** [comment]
Yeah, I considered that. Thanks for the feedback. I think I'll update the official release notes to reiterate this **very** important point. Glad things are sorted out.
