### ISSUE TITLE
Strange Behavior with MVC WebApi Routes

### ISSUE THREAD

**Issue by kham04** [Microsoft/aspnet-api-versioning#161]
Hi,

We're trying to support multiple API versions with controllers that differ by namespace only. We've noticed that some routes appear to work fine, while other nearly identical routes return a 404 (see below):

**Working controller route:**

```
    [Authorize]
    [ApiVersion("2.0")]
    [Route("{version:apiVersion}/Filing")]
    public class FilingController : ApiController
    {
        private Context db = new Context ();

        [ResponseType(typeof(Filing))]
        public IHttpActionResult Get(int? id = null)
        {
            var result = new List<FormGroup>();

            if (id.HasValue)
            {

                result = new List<FormGroup>() { User.GetFormGroup(db, id.Value) };

            }
            else
            {
                result = User.AppUser(db).Customer.FormGroups.Where(o => o.IsActive).ToList();
            }

            return Ok(result.Select(o => new Filing(o)).ToArray());
        }
```

**Works fine (note the 200 OK):**

![image](https://user-images.githubusercontent.com/30059681/28042795-82d8cf2e-6594-11e7-96b2-47916599d9d1.png)

**Non-working controller route:**

```
  [Authorize]
    [ApiVersion("2.0")]
    [Route("{version:apiVersion}/FilingErrors")]
    public class FilingErrorsController : ApiController
    {
        private Context db = new Context();
          
        [ResponseType(typeof(FilingErrors))]
        public async Task<IHttpActionResult> Get(int id)
        {
            FormGroupRepository repo = new FormGroupRepository(db);
            var result = await repo.GetErrors(User, id);
            return Ok(new FilingErrors(result));
        }
```

**Non-Working Route Result**

![image](https://user-images.githubusercontent.com/30059681/28042927-1d00dbd2-6595-11e7-9844-96c6be95d2df.png)

**Our Startup.cs file:**

 `
[assembly: Microsoft.Owin.OwinStartup(typeof(Removed.Api.Startup))]
namespace Removed.Api
{
    using Removed.Api.Models;
    using global::Owin;
    using Microsoft.Web.Http.Routing;
    using Swashbuckle.Application;
    using System.IO;
    using System.Reflection;
    using System.Web.Http;
    using System.Web.Http.Description;
    using System.Web.Http.Routing;
    using System.Diagnostics;
    using System.Web.Http.Dispatcher;
    using Removed.Api.Utilities;
    using System.Collections.Generic;

    /// <summary>
    /// Represents the startup process for the application.
    /// </summary>
    public partial class Startup
    {
        /// <summary>
        /// Configures the application using the provided builder.
        /// </summary>
        /// <param name="builder">The current application builder.</param>
        public void Configuration(IAppBuilder builder)
        {
            // we only need to change the default constraint resolver for services that want urls with versioning like: ~/v{version}/{controller}
           var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };
            
            //IMPORTANT keep this here, order is important to make sure auth works.
            ConfigureAuth(builder);
            var configuration = new HttpConfiguration();
            var httpServer = new HttpServer(configuration);

            configuration.MapHttpAttributeRoutes(constraintResolver);

            // reporting api versions will return the headers "api-supported-versions" and "api-deprecated-versions"
            configuration.AddApiVersioning(o =>
            {
                o.ReportApiVersions = true;
                o.AssumeDefaultVersionWhenUnspecified = true;
                o.DefaultApiVersion = new Microsoft.Web.Http.ApiVersion(2,0);
            });

            // add the versioned IApiExplorer and capture the strongly-typed implementation (e.g. VersionedApiExplorer vs IApiExplorer)
            // note: the specified format code will format the version as "'v'major[.minor][-status]"
            var apiExplorer = configuration.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");

            configuration.EnableSwagger(
                            "{apiVersion}/swagger",
                            swagger =>
                            {
                                // build a swagger document and endpoint for each discovered API version
                                swagger.MultipleApiVersions(
                                        (apiDescription, version) => VersionSupportResolver(apiDescription.GetGroupName(), version),
                                        info =>
                                        {
                                            foreach (var group in apiExplorer.ApiDescriptions)
                                            {
                                                var description = "Removed API";
                                                
                                                if (group.IsDeprecated)
                                                {
                                                    description += " This API version has been deprecated.";
                                                }

                                                Debug.WriteLine(group.Name);

                                                info.Version(group.Name, $"Removed.Api.v{group.ApiVersion}")
                                                        .Contact(c => c.Name("Removed Support").Email("support@removed.com"))
                                                        .Description(description)
                                                        .TermsOfService("https://removed.com/Terms");

                                                foreach(var apiDescription in group.ApiDescriptions)
                                                {
                                                    apiDescription.RelativePath = apiDescription.RelativePath.Replace("{version}", group.Name);
                                                }
                                            }

                                        });

                                // add a custom operation filter which sets default values
                                swagger.OperationFilter<SwaggerDefaultValues>();

                                // integrate xml comments
                                swagger.IncludeXmlComments(XmlCommentsFilePath);
                                //swagger.UseFullTypeNameInSchemaIds();
                                swagger.ResolveConflictingActions((apiDescriptions) =>
                                {
                                    var result = new ApiDescription();
                                    var apiEnum = apiDescriptions.GetEnumerator();
                                    while (apiEnum.MoveNext())
                                    {
                                        result = apiEnum.Current;
                                    }
                                    return result;
                                });
                                
                            })
                         .EnableSwaggerUi(swagger => { swagger.EnableDiscoveryUrlSelector(); });

            configuration.Routes.MapHttpRoute(
                "VersionedUrl",
                "v{apiVersion}/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional },
                constraints: new { apiVersion = new ApiVersionRouteConstraint() });

            //configuration.Routes.MapHttpRoute(
            //    "VersionedQueryString",
            //    "api/{controller}/{id}",
            //    defaults: new { id = RouteParameter.Optional }
            //   );

            builder.UseWebApi(httpServer);
        }

        private bool VersionSupportResolver(string apiDescription, string version)
        {
            return apiDescription == version;
        }

        static string XmlCommentsFilePath
        {
            get
            {
                var basePath = System.AppDomain.CurrentDomain.RelativeSearchPath;
                var fileName = "XmlDocument.xml";
                return Path.Combine(basePath, fileName);
            }
        }
    }
}
`

I noticed that commenting out            

 `configuration.MapHttpAttributeRoutes(constraintResolver);`

will allow the erred controller route to work, but of course our Swagger documentation at v2/swagger breaks:

![image](https://user-images.githubusercontent.com/30059681/28042983-63318e6c-6595-11e7-9845-0afc962658d1.png)

We downloaded the source for aspnet-api-versioning and including this in the solution to set breakpoints and determine where the root cause of the issue is, and we found the following:

The non-working controller route returns 'true' for controllerDescriptor.IsAttributeRouted() in ActionSelectorCacheItem.cs - Line 85. Our working controller returns 'false' at this point:

```
  if ( controllerDescriptor.IsAttributeRouted() )
                {
                    selectionCache.StandardCandidateActions = new CandidateAction[0];
                }
                else
                {
                    var standardCandidateActions = new List<CandidateAction>();
```
If we set a breakpoint in the controllerDescriptor.IsAttributeRouted() function and force it to return a false for the erred controller, the route will work. 

Does anyone know what could possibly be wrong here? From what we can tell the 2 controller routes are formatted identically (except for the name) where one works and one doesn't.  Any help is greatly appreciated.

**Comment by commonsensesoftware** [comment]
Thanks for all of the detailed information. It's dense, but it does help track down things quickly. ;)

It seems that you have a simple typo in your **ApiController** routes. The template `[Route("{version:apiVersion}/Filing")]` should be `[Route("v{version:apiVersion}/Filing")]`. You've missed the leading `v` in the attribute templates, but you have it on the convention-based route.  That's why convention routes are working, but attribute routes are not.

I **strongly** discourage mixing routing styles, unless you have legacy stuff that you're afraid to touch. Having attribute and convention-based routes together are supported, but can be very confusing to understand and troubleshoot. Just a suggestion. Anything you may have seen in an example is purely for illustration (e.g. not a _best practice_).

I would recommend deleting the `configuration.Routes.MapHttpRoute` for "VersionedUrl" and "VersionedQueryString". It looks like you may have been just running through some trial and error scenarios. 

The following should get you want you want:

```c#
[Authorize]
[ApiVersion("2.0")]
[RoutePrefix("v{version:apiVersion}/Filing")]
public class FilingController : ApiController
{
    private Context db = new Context ();

    [Route("{id:int?}")]
    [ResponseType(typeof(Filing))]
    public IHttpActionResult Get(int? id = null)
    {
        var result = new List<FormGroup>();

        if (id.HasValue)
        {
            result = new List<FormGroup>() { User.GetFormGroup(db, id.Value) };
        }
        else
        {
            result = User.AppUser(db).Customer.FormGroups.Where(o => o.IsActive).ToList();
        }

        return Ok(result.Select(o => new Filing(o)).ToArray());
    }
}

[Authorize]
[ApiVersion("2.0")]
[RoutePrefix("v{version:apiVersion}/FilingErrors")]
public class FilingErrorsController : ApiController
{
    private Context db = new Context();

    [Route("{id:int}")]
    [ResponseType(typeof(FilingErrors))]
    public async Task<IHttpActionResult> Get(int id)
    {
        var repo = new FormGroupRepository(db);
        var result = await repo.GetErrors(User, id);
        return Ok(new FilingErrors(result));
    }
}
```

I hope that helps. Let me know if you have more questions.

**Comment by kham04** [comment]
Thank you for this!

We had tried this fix earlier and it worked, but our Swagger documentation started to generate routes for this as '/vv2/FilingErrors/{id}'. Is there a simple override for the Swagger URL generation to correct this?

**Comment by kham04** [comment]
Thank you for this!

I just wanted to expand on this a little more.

'FilingErrorsController' from above was a new controller that only exists in the v2 namespace, but 'FilingController' was in both v1 and v2. When I add a FilingErrorsController to the v1 namespace with the ApiVersion("1.0") this route seems to work as expected. Is there a trick to get this to work when the controller is new for v2 without having to add a controller for prior versions?

**Comment by commonsensesoftware** [comment]
It seems that you might have updated or otherwise retracted one of your last comments. The reason the Swagger routes are not being generated correctly is because your are mucking with the URLs. Possible solutions:

* Don't change the URLs; the API explorer generates the correct URLs and supplies default values for the corresponding route parameter so that the user doesn't have to enter it
* Change the **GroupNameFormat** to the format `VVV` without the literal `'v'`
* Account for the literal `v` in your string replacement (e.g. `Replace("v{version}", group.Name)`)

The API explorer bucketizes the controllers by API version. Namespaces and other organization techniques are purely implementation details and of no importance to the API explorer.

Assuming the following:

```c#
namespace Services.V1
{
    [ApiVersion("1.0")]
    [RoutePrefix("v{version:apiVersion}/Filing")]
    public class FilingController : ApiController { }
}
namespace Services.V2
{
    [ApiVersion("2.0")]
    [RoutePrefix("v{version:apiVersion}/Filing")]
    public class FilingController : ApiController { }

    [ApiVersion("2.0")]
    [RoutePrefix("v{version:apiVersion}/FilingErrors")]
    public class FilingErrorsController : ApiController { }
}
```

Then I would expect the API explorer to generate API descriptions grouped the following way:

* API Version 1.0
  * Services.V1.FilingController
* API Version 2.0
  * Services.V2.FilingController
  * Services.V2.FilingErrorsController

If that isn't the case, let me know. There may be a bug in the API explorer. I'm not sure what effect `ResolveConflictingActions` has on the Swagger document generation, but this configuration should not be necessary.

**Comment by commonsensesoftware** [comment]
I also noticed that you've enabled `AssumeDefaultVersionWhenUnspecified`. This isn't doing what you think it does since you are implementing API version by URL segment and the default API version is 2.0. In order for that to work, you have to have default routes for without the API version segment. It is **not** possible to have a default or otherwise assume value in the middle of the URL. See the wiki topic [URL Path Segment Routing with a Default API Version](../wiki/Known-Limitations#url-path-segment-routing-with-a-default-api-version) for more information and possible solutions.

**Comment by kham04** [comment]
Right, sorry about that! 

After I had posted, I notice that tweaking the ApiExplorer formatting seemed to correct the Swagger urls.

Thank you so much for your help, it is sincerely appreciated!

**Comment by commonsensesoftware** [comment]
Glad to help. Feel free to close this out if all of your questions have been answered and you're in business. Thanks!

**Comment by commonsensesoftware** [comment]
Seems like you're good to go. Feel free to come back or reopen this issue if your issue has not been solved.
