### ISSUE TITLE
Issue/Observation while using Versioning and Swashbuck with IIS Deployment

### ISSUE THREAD

**Issue by harish285** [Microsoft/aspnet-api-versioning#162]
@commonsensesoftware  Thanks for giving the detailed samples to work with the Versioning and the Swashbuckle. Being new to the Web API, I wasn't able to get it work correctly when we are using the IIS (It works good when we use OWIN). 

**_Issue Description_** 

The Swagger UI doesn't shows any of the controller methods when the multiple versions are enabled, however it works fine with single version

This is how the SwaggerConfig.cs Looks Like for the multiple versions . 

var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };
           // GlobalConfiguration.Configuration.AddApiVersioning(o => o.ReportApiVersions = true);
            // GlobalConfiguration.Configuration.MapHttpAttributeRoutes(constraintResolver);
            var configuration = new HttpConfiguration();
            configuration.AddApiVersioning(o => o.ReportApiVersions = true);
            configuration.MapHttpAttributeRoutes(constraintResolver);
            var apiexplorer = configuration.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");

            GlobalConfiguration.Configuration
                              .EnableSwagger(
                "{apiVersion}/swagger", c =>
                          {

                              //c.SingleApiVersion("v1", "Sample API");
                              c.MultipleApiVersions(
                                (apiDesc, targetApiVersion) => apiDesc.GetGroupName() == targetApiVersion,
                               info =>
                               {
                                   foreach (var group in apiexplorer.ApiDescriptions)
                                   {
                                       var description = "sample API Solution.";

                                       if (group.IsDeprecated)
                                       {
                                           description += " This API version has been deprecated.";
                                       }

                                       info.Version(group.Name, $"Sample  API {group.ApiVersion}")
                                           .Contact(c2 => c2.Name("Sample  API").Email("abc@gmail.com"))
                                           .Description(description)
                                           .License(l => l.Name("test").Url("test"))
                                           .TermsOfService("test");
                                   }
                               });
                              c.OperationFilter<SwaggerDefaultValues>();

                          })
                      .EnableSwaggerUi(c =>
                          {
                              c.EnableDiscoveryUrlSelector();
                          });
The new HttpConfiguration is created as the API explorer is unable to fetch the descriptions from GlobalConfiguration.Configuration.AddApiVersioning at initialization stage. The apiexplorer.ApiDescriptions has the correct descriptions of all the versions which can be seen by putting the breakpoints.

This is how the WebAPIConfig.cs looks like :

var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };

            config.AddApiVersioning(o => o.ReportApiVersions = true);
            config.MapHttpAttributeRoutes(constraintResolver);
            config.Routes.MapHttpRoute(
              name: "DefaultApi",
              routeTemplate: "v{api-version:apiVersion}/{controller}/",
                defaults: new { apiVersion = RouteParameter.Optional }

            );

After long hours of analyzing i was able to get if worked only by moving the code of the SwaggerConfig.cs to WebAPIconfig.cs.  The Main issue  (i think) was the fact that Apply Method of SwaggerDefaultValues is not getting called if its in SwaggerConfig.cs  but gets called if its in Startup.cs as in your example or WebAPIconfig.cs as shown below

**Please let me know if this the expected behavior/Solution**

Now after fixing this his how WebapiConfig.cs Looks Like

 var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };

            config.AddApiVersioning(o => o.ReportApiVersions = true);
            config.MapHttpAttributeRoutes(constraintResolver);
            //config.Routes.MapHttpRoute(
            //    name: "DefaultApi",
            //    routeTemplate: "v{api-version:apiVersion}/{controller}/",
            //    defaults: new { apiVersion = RouteParameter.Optional }

            //);
            var apiexplorer = config.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");
            config.EnableSwagger(
                "{apiVersion}/swagger", c =>
                {

                    //c.SingleApiVersion("v1", "Sample");
                    c.MultipleApiVersions(
                      (apiDesc, targetApiVersion) => apiDesc.GetGroupName() == targetApiVersion,
                     info =>
                     {
                         foreach (var group in apiexplorer.ApiDescriptions)
                         {
                             var description = "Sample API Solution.";

                             if (group.IsDeprecated)
                             {
                                 description += " This API version has been deprecated.";
                             }

                             info.Version(group.Name, $"Sample API {group.ApiVersion}")
                                 .Contact(c2 => c2.Name("Sample Tech").Email("abc@gmail.com"))
                                 .Description(description)
                                 .License(l => l.Name("Sample").Url("test"))
                                 .TermsOfService("test");
                         }
                     });
                    c.OperationFilter<SwaggerDefaultValues>();

                })
                      .EnableSwaggerUi(c =>
                      {
                          c.EnableDiscoveryUrlSelector();
                      });

**Comment by commonsensesoftware** [comment]
I think there are a couple of things going on:

* You can 100% use the Web API OWIN stack with IIS; the provided examples run in IIS Express (which _is_ IIS with an isolated, per-user configuration).
  * This setup only requires Swashbuckle.Core NuGet package
* When running with the legacy **Application_Start** event from **HttpApplication**, you need to use `GlobalConfiguration.Configure( config => { /* all your config */ } );` as documented in [Configuring ASP.NET Web API](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/configuring-aspnet-web-api#webhost).
  * It's common to break component configurations into different classes and invoke them all in this callback (ex: `GlobalConfiguration.Configure( c => { WebApiConfig.Register( c ); SwaggerConfig.Register( c ); } );`)
  * If this callback isn't used, attribute routing will likely not work correctly; in other words, do not use `GlobalConfiguration.Configuration` directly.
  * This setup needs the full Swashbuckle NuGet package. If I understand what it does correctly, it dynamically injects and registers the necessary Swashbuckle **IHttpModule** for Swagger. I've honestly never used this approach.

It also seems that you have added a convention-based route via `config.Routes.MapHttpRoute`. I strongly recommend that you do **not** do that. Mixing attribute and convention-based routing is supported in a limited capacity, but it can be very confusing. I only demonstrate it for illustration. It is definitely **not** a _best practice_. I suggest that you choose one method and stick with it. Attribute routing tends to be easier to follow and pair with the source code, but it's your choice.

I hope that provides more context for you. Try some of those adjustments and let me know if things light up the way you expect.

**Comment by harish285** [comment]
Thanks for the insights . I was about to use only the Attribute based routing and will comment out the convention based routing. I will give a try to GlobalConfiguration.Configure( config => { /* all your config */ } );  and let you know. For now we have two working solution one using OWIN(personally as i dont have much experience with OWIN i am reluctatnt to take this route) and one invoking the swagger in webapiconfig.cs

**Comment by harish285** [comment]
using  GlobalConfiguration.Configure(SwaggerConfig.Register) in the Global.asax works. Thanks. :)

**Comment by commonsensesoftware** [comment]
Great! Glad to hear.
