### ISSUE TITLE
Broken link in wiki

### ISSUE THREAD

**Issue by vanillajonathan** [Microsoft/aspnet-api-versioning#171]
https://github.com/Microsoft/aspnet-api-versioning/wiki/Known-Limitations#aspnet-web-api-alternate-solution

"If you're using ASP.NET Web API, you can also choose to implement a custom IDirectRouteProvider as suggested in Issue #73."

The hyperlink to issue #73 is broken.

**Comment by commonsensesoftware** [comment]
Thanks. I've fixed it.  Apparently the `#73` auto-link feature doesn't work in the wiki so you have to craft the link manually. Looks like I accidentally had it go up one too many levels.
