### ISSUE TITLE
POST request always returns current (newest) version of API

### ISSUE THREAD

**Issue by ghanavat** [Microsoft/aspnet-api-versioning#183]
Hi,

Using the media type (content negotiation), POST requests are always pointing at the current/newest version despite explicitly requesting another version.

I have 3 versions for POST in different namespaces. I am requesting version 2:
Content-Type : application/json;version=2.0
But I am getting response from version 3 which is newest version. This is not happening for GET. I want to be able to send POST request to explicit version.

Please advise.

Kind regards,
Saeed

**Comment by commonsensesoftware** [comment]
Can you share your startup configuration? We can start with that and if you have a simple repro, that will go a long way into any investigation if needed.

**Comment by ghanavat** [comment]
This is my startup:
            services.AddApiVersioning(options =>
            {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true;
                options.DefaultApiVersion = new Microsoft.AspNetCore.Mvc.ApiVersion(1, 0);
                options.ApiVersionReader = new MediaTypeApiVersionReader("version");
                options.ApiVersionSelector = new CurrentImplementationApiVersionSelector(options);
            });

I have found the problem though. It worth to share it. I had to look at the response body, and I have noticed that the content type was form-data. However, the content type I was requesting was (as above) application/json. So that's why I was getting the response from the newest version always, because there was no resource/action to satisfy the request.

**Comment by commonsensesoftware** [comment]
Correct. You are also using the API version selector that chooses the current API version when otherwise unspecified. This is why you are getting 3.0 instead of 1.0.

**Comment by ghanavat** [comment]
Ah, yes that's correct. I am getting closer to have a solution I initially wanted. I don't think that I would need ApiVersionSelector in my case. Instead I can I configure my solution for DefaultApiVersion, so I won't break the code for existing clients/users.

**Comment by commonsensesoftware** [comment]
It seems as though you are on your way. Come back if you have more questions or feel free to reopen the issue if things are not resolved. Thanks.
