### ISSUE TITLE
Occasional UnsupportedApiVersion error

### ISSUE THREAD

**Issue by israellot** [Microsoft/aspnet-api-versioning#185]
I'm experiencing and odd behavior. 
I have a route that accepts websockets connections. The signagure looks like: 

`    [RequireHttps] 
     [HttpGet("/{app}/ws")]
     [ProducesResponseType(101)]
 public async Task<ActionResult> AcceptWebsocket([FromRoute(Name ="app")]Application app,[FromServices] IWebsocketsManager websocketsManager)
` 

The problem is that if I hit that multiple times with same parameters and headers, some of the requests will fail with error **UnsupportedApiVersion** and some will work just fine.

**Comment by commonsensesoftware** [comment]
I haven't tried combining things with web sockets myself. This might be a result of how (more likely when) the versioning policy is applied. If you have the world's simplest repro, it would be really useful and accelerate the investigation process. Using something close to your setup is always best to ensure I get similar results.

**Comment by commonsensesoftware** [comment]
Did you ever resolve this? There are several ways this could be handled. Addressing versioning directly in the web sockets layer might be better.

**Comment by commonsensesoftware** [comment]
Seems like you solved your issue or went another route. Should you still need help, feel free to come back and reopen the issue. Thanks.
