### ISSUE TITLE
An element with the key 'version' already exists in the RouteValueDictionary. Parameter name: key

### ISSUE THREAD

**Issue by chatnoir1982** [Microsoft/aspnet-api-versioning#188]
Hi,

I am using version 1.2.1 of the library with MVC Core 1.1.2, and have configured my Startup's ConfigureServices method as such :

```
services.AddMvc(<MVC options omitted for brevity>);
services.AddApiVersioning(options => { options.Conventions.Controller<FooController>().HasApiVersion(new ApiVersion(1, 0)); })
```

My controller is decorated with the Route attribute as such:
```
[Route("api/v{version:apiVersion}/[controller]")]
public class FooController : Controller
```

My controller's action methods:

```
[HttpGet("{fooId}")]
public IActionResult Get([FromRoute]string fooId)

[HttpPost("{fooId}:[action]")]
public IActionResult Cancel([FromRoute]string fooId)
```

When calling the above urls from PostMan with the id Guid:
`GET localhost:6000/api/v1/Foo/<some-guid-here>`
`POST localhost:6000/api/v1/Foo/<some-guid-here>:cancel`

I get the below error from my application:
> fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HL83UF1HL0HA": An unhandled exception was thrown by the application.
> System.ArgumentException: An element with the key 'version' already exists in the RouteValueDictionary.
> Parameter name: key
>    at Microsoft.AspNetCore.Routing.RouteValueDictionary.Add(String key, Object value)
>    at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.MatchComplexSegmentCore(TemplateSegment routeSegment, String requestSegment, IReadOnlyDict
> ionary`2 defaults, RouteValueDictionary values, Int32 indexOfLastSegmentUsed)
>    at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.MatchComplexSegment(TemplateSegment routeSegment, String requestSegment, IReadOnlyDictiona
> ry`2 defaults, RouteValueDictionary values)
>    at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.TryMatch(PathString path, RouteValueDictionary values)
>    at Microsoft.AspNetCore.Routing.Tree.TreeRouter.<RouteAsync>d__13.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

If I change my methods' signatures from:
```
[HttpGet("{fooId}")]
public IActionResult Get([FromRoute]string fooId)

[HttpPost("{fooId}:[action]")]
public IActionResult Cancel([FromRoute]string fooId)
```

to:
```
[HttpGet("{fooId}/[action]")]
public IActionResult Get([FromRoute]string fooId)

[HttpPost("{fooId}/[action]")]
public IActionResult Cancel([FromRoute]string fooId)
```

then calling the methods works as expected.

I'd appreciate some input. Thanks.

Regards

**Comment by commonsensesoftware** [comment]
It seems odd that you would use a `:` in your route template, but I guess you have your reasons. Do things work without API versioning? I don't see anything in the call stack that indicates that is the source of the issue. If it doesn't work with API versioning, then you know it's something else. If you have the world's simplest repro that you can attach here, that would go a long in accelerating any investigation.

**Comment by chatnoir1982** [comment]
Ok so I've created a brand new empty project to check, this is MVC core 1.1.2.

Here's the startup class:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using WebApplication4.Controllers;

namespace WebApplication4
{
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();
            services
                .AddApiVersioning(options =>
                {
                    options.Conventions.Controller<ValuesController>().HasApiVersion(new ApiVersion(1, 0));
                });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseMvc();
        }
    }
}

```

And the controller:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication4.Controllers
{
    [Route("v{version:apiVersion}/[controller]")]
    public class ValuesController : Controller
    {
        //http://localhost:54149/v1/values/1 - throws exception
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        //http://localhost:54149/v1/values/1:getthis - reachable
        [HttpGet("{id}:[action]")]
        public string GetThis(int id)
        {
            return "value";
        }
        
    }
}
```

Using Postman, I call the first get:
**http://localhost:54150/v1/values/1**
, which throws the following:

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:54150/v1/values/1
> fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HL8B4U39I175": An unhandled exception was thrown by the application.
> System.ArgumentException: An element with the key 'version' already exists in the RouteValueDictionary.
> Parameter name: key
>    at Microsoft.AspNetCore.Routing.RouteValueDictionary.Add(String key, Object value)
>    at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.MatchComplexSegmentCore(TemplateSegment routeSegment, String requestSegment, IReadOnlyDict
> ionary`2 defaults, RouteValueDictionary values, Int32 indexOfLastSegmentUsed)
>    at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.MatchComplexSegment(TemplateSegment routeSegment, String requestSegment, IReadOnlyDictiona
> ry`2 defaults, RouteValueDictionary values)
>    at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.TryMatch(PathString path, RouteValueDictionary values)
>    at Microsoft.AspNetCore.Routing.Tree.TreeRouter.<RouteAsync>d__13.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 12.3306ms 500

Calling the "getthis" method works:

> Now listening on: http://localhost:54150
> Application started. Press Ctrl+C to shut down.
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:54150/api/values
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 633.317ms 404
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:54150/v1/values/1:getthis
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method WebApplication4.Controllers.ValuesController.GetThis (WebApplication4) with arguments (1) - ModelState is Valid
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action WebApplication4.Controllers.ValuesController.GetThis (WebApplication4) in 446.4701ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 675.1304ms 200 text/plain; charset=utf-8


Regards

**Comment by commonsensesoftware** [comment]
I guess I should have looked closer at the stack trace. This error is coming from the built-in routing infrastructure. As it stands, your route templates are ambiguous. The `:` character is not a path separator. Each action must form a distinct path segment and HTTP method.

The router sees your templates as:
* GET, `v1/values/{param}` where **param** = `{id}`
* GET, `v1/values/{param}` where **param** = `{id}:getthis`

To my knowledge, you cannot define routes that vary purely by type or format. For example, you cannot have:
* GET `v1/values/abc` --> GetValuesByString
* GET `v1/values/1` --> GetValuesByInteger

I fully expect things to fail without API versioning as well.

Based on your original post, I recommend the following:
```c#
[HttpGet( "{id}" )]
public IActionResult Get( string id ) => Ok();
```
Paired with:
```c#
[HttpPost( "{id}/[action]" )]
public IActionResult Cancel( string id ) => NoContent();
```
OR
```c#
[HttpDelete( "{id}" )]
public IActionResult Cancel( string id ) => NoContent();
```

I hope that helps.

**Comment by chatnoir1982** [comment]
Yes I see, thank you. We wanted to use ':' in the URL for calling custom methods, as defined in the Google API design guidelines.
