### ISSUE TITLE
OWIN Web API - VersionedAPIExplorer registers additional routes

### ISSUE THREAD

**Issue by matsbjorkmaneldh** [Microsoft/aspnet-api-versioning#190]
Hi,

Thanks for all the good work on a great API. We've previously used it successfully for an ASP.NET Core project. Currently however we ran into some issues when adding support for versioning in a Web API project when using OWIN and attribute based routing. 

A bit simplified you could say we've implemented an optional base-controller in a referenced assembly and then we have a couple of controllers in a startup assembly:

```       
namespace BaseAssembly
{
    public class CloudApplicationController : ApiController
    {
        [HttpGet]
        [Route("ping")]
        public virtual IHttpActionResult Ping()
        {
            return Ok();
        }

        [HttpGet]
        [Route("apiinfo")]
        public virtual IHttpActionResult GetApiInformation()
        {
            return Ok(new AssemblyInfoModel(GetType().Assembly));
        }

        ...
    }
}
```

```       
namespace StartupAssembly
{
    [ApiVersion("1")]
    [ApiVersion("2")]
    [RoutePrefix("api/v{version:apiVersion}/books")]
    public class BookController : ApiController
    {
        private IBookService _bookService;

        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }

        [HttpPost]
        [Route("")]
        [AllowAnonymous]
        public async Task<IHttpActionResult> CreateBook(BookModel model)
        {
            var book = await _bookService.CreateAsync(model);
            return Created(string.Format("api/books/{0}", book.UID), book);
        } 

         ...
    }

    [ApiVersion("2")]
    [RoutePrefix("api/v{version:apiVersion}/authors")]    
    public class AuthorController : ApiController
    {
        private IAuthorService _authorService;
        private IBookService _bookService;

        public AuthorController(IAuthorService authorService, IBookService bookService)
        {
            _authorService = authorService;
            _bookService = bookService;
        }

        [HttpPost]
        [Route("")]
        public async Task<IHttpActionResult> CreateAuthor(AuthorModel model)
        {
            var author = await _authorService.CreateAsync(model);
            return Created(string.Format("api/author/{0}", author.UID), author);
        }

        ...
  }
}
```

We're using Autofac to register controllers and only register controllers from the startup assembly. When running this as a non-versioned api or using hard-coded versions for swagger as below

```
var apiExplorer = config.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'V");
config.EnableSwagger("{apiVersion}/swagger", c =>
	{
		c.MultipleApiVersions(
			(apiDescription, version) => apiDescription.GetGroupName() == version,
			info =>
			{
				info.Version("v1", $"Sample API 1 ... original");
				info.Version("v2", $"Sample API 2 .... version 2");

			});
```

everything works as expected, see attached screenshot "HardcodedSwaggerVersions.png" (only actions from startup assembly).  

However when using _VersionedAPIExplorer_ to dynamically detect the versions:

```
var apiExplorer = config.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'V");               
config.EnableSwagger("{apiVersion}/swagger", c =>
	{
		c.MultipleApiVersions(
			(apiDescription, version) => apiDescription.GetGroupName() == version,
			info =>
			{
				foreach (var group in apiExplorer.ApiDescriptions)
				{
					info.Version(group.Name, $"Sample API {group.ApiVersion}");
				}
			});
```
then the resulting registered routes include actions from the basecontroller in the referenced assembly, see attached screenshot "DynamicSwaggerVersions.png".

Am I missing something obvious here? I'm a bit surprised over the fact that calling _VersionedAPIExplorer_ to find out defined versions also will register additional routes from the referenced assembly.

Regards, Mats Björkman Eldh
![dynamicswaggerversions](https://user-images.githubusercontent.com/8612571/30900657-173aa972-a365-11e7-86af-048eef9b20a1.png)
![hardcodedswaggerversions](https://user-images.githubusercontent.com/8612571/30900656-1739c94e-a365-11e7-8c32-82c8106c496a.png)

**Comment by commonsensesoftware** [comment]
I suspect this may have always been the case, even before API versioning. The **VersionedApiExplorer** is forked from the original **ApiExplorer** implementation and that's only because it was not very extensible. In terms of controller discovery and resolution, API versioning does not do anything _special_. It will use the registered routes and **IHttpControllerTypes** service to discover services just like the default implementation. In your first example above, I noticed you are _cherry-picking_ the services you want rather than enumerating them all. That's probably why you get different results.

It appears  that **CloudApplicationController** is simply a generic controller that you include in applications that you just don't want to make discoverable. Fortunately, this is a first-class concept that continues to be honored by the **VersionedApiExplorer**. You just need to decorate your controller like so:

```c#
[ApiExplorerSettings( IgnoreApi = true )]
public class CloudApplicationController : ApiController
{
  // ommitted
}
```

That will make the controller excluded from the discover and enumeration. Let me know if that doesn't work.

**Comment by commonsensesoftware** [comment]
You should be on your way to lighting up Swagger the way you want. If your issue is not resolved or you continue to encounter issues, feel free to come back. Thanks.
