### ISSUE TITLE
Handling odata $batch

### ISSUE THREAD

**Issue by d-saravanan** [Microsoft/aspnet-api-versioning#193]
We would like to confirm if that if we have an OData $batch, will it work with the versions.

For example: we earlier had it as http://localhost/odata/$batch and in the payload we used to post the data with the changesets.

However if we use the versioned OData Controllers, giving a http://localhost/odata/v1/$batch also succeeds and so is http://localhost/odata/$batch. 

We would like to know if the internal resource URL alone needs to be versioned like 
/v1/Roles(1)... or the $batch url to be versioned and the internal URL's to be used without a versions or if both of them needs to be versioned.

**Comment by commonsensesoftware** [comment]
The **$batch** route isn't a controller or service. It maps to a special handler that splits and joins the items. Since the batch route isn't a service, there's no reason to version it specifically. The default handler can process all API versions without modification.

**Comment by d-saravanan** [comment]
I have an issue here, I have not used the version in the $batch. However, I have a route in my action method like the one below.

```
        [ODataRoute("Roles({RoleId})")]
        public async Task<IHttpActionResult> DeleteRole([FromODataUri] long RoleId, [FromODataUri] bool commitChanges = true)
```
When called using the batch handler, it does not construct the correct batch URL. i.e. the ODataRouteName property in the DefaultODataBatchHandler is set as null, due to which the OData url formed for the items in the batch is rendered as wrong and the batch fails.

```
public class ServiceBatchHandler : DefaultODataBatchHandler
{
	public override Uri GetBaseUri(HttpRequestMessage request)
	{
	    System.Diagnostics.Trace.WriteLine("The default route name is: ", ODataRouteName);

	    var formedBaseUri = request.GetODataBatchBaseUri(ODataRouteName);

	    return base.GetBaseUri(request);
	}
}
```
The same code without API Versioning is working fine and fails with this versioned model alone. Kindly note that, I suspect that the ODataRouteName property is set as null and also the routes does not contain the route named as "odata". I checked the `request.GetUrlHelper().Route(.. ) `to see if the routes collection contains a route by name "odata" and that one too fails. The following are the route config done in the webapiconfig.cs file

```
config.MapVersionedODataRoutes("odata", "odata", models, odataBatchHandler);
config.MapVersionedODataRoutes("odata-by-path", "odata/v{apiVersion}", models,odataBatchHandler);
config.MapVersionedODataRoutes("odata$batch", "odata$batch", models, odataBatchHandler);
```

All of these experiments are being carried out on .Net Framework 4.5.1 and Versioning DLL version 2.0.1.0.

Since this issue is taking toll on the time, any help in fixing or understanding the right routing configuration would be of great help.

**Comment by commonsensesoftware** [comment]
I think I have enough information to put together a repro. In fact, I may have even have a batching example laying around. If you have your own repro that you can share, that will be immensely useful. Ensuring that I have the same starting point as you helps accelerate my investigations. Feel free to post the *.zip here or a link to the project. Thanks.

**Comment by d-saravanan** [comment]
Thanks for you reply. Sure thing, I will prepare the repro app and share it within this time tomorrow, so we can arrive at a conclusion and be on the same page.

**Comment by d-saravanan** [comment]
Please note that, I have the code available [here](https://github.com/d-saravanan/451ApiVersioning). Kindly use this repository code to test out the issue. The issue can be found when you attempt to do an OData $batch call as per the below given postman script.

```
POST /Services/odata/$batch HTTP/1.1
Host: localhost:60351
Content-Type: multipart/mixed; boundary=batch_1506596024110
Cache-Control: no-cache
Postman-Token: 603e7230-f976-ba43-c66c-5fe06cf72c97

--batch_1506595850678
Content-Type: multipart/mixed; boundary=changeset_1506595870398
Prefer: odata.continue-on-error

--changeset_1506595870398
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 0
Prefer: odata.continue-on-error

DELETE Employees(1) HTTP/1.1
Host: localhost:50443

--changeset_1506595870398--
--batch_1506595850678--
```

Please review the same and share your comments and how it can be achieved without using Attribute Routing or otherwise.

**Comment by commonsensesoftware** [comment]
Thanks for the repro. A couple of things right off the bat:
* You have both OWIN and the legacy IIS host setups; I'm not sure exactly which one you're using
   * My examples use OWIN (over IIS), but that doesn't mean you have to
   * I chose to use OWIN so the example between ASP.NET Core and Web API have greater parity

Since you enabled implicit versioning, the item in the current batch will work, but don't forget that other API versions will require an explicit API version - `DELETE Employees(1)?api-version=2.0`.

I'll continue examining what you have and return a working example to you. I don't see anything thus far that would prevent things from working. I've enabled batching with API versioning many times. In fact, you can use the following request against the [Basic OData Example](../tree/master/samples/webapi/BasicODataWebApiSample):

```http
POST http://localhost:4129/api/$batch HTTP/1.1
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b
Host: localhost:4129
Content-Length: 678

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http
Content-Transfer-Encoding:binary

GET orders(1)?api-version=1.0 HTTP/1.1


--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http
Content-Transfer-Encoding:binary

GET people(1)?api-version=1.0 HTTP/1.1


--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http
Content-Transfer-Encoding:binary

GET people(1)?api-version=2.0 HTTP/1.1


--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http
Content-Transfer-Encoding:binary

GET people(1)?api-version=3.0 HTTP/1.1


--batch_36522ad7-fc75-4b56-8c71-56071383e77b--
```

**Comment by commonsensesoftware** [comment]
Attached is a working version of your project. Aside from the mixing of OWIN with the legacy IIS hosting, there was only one real issue. The two routes defined on the **ValuesController** were ambiguous. This was true even without API versioning. I temporarily removed API versioning to verify. You may want to  test your routes standalone before adding API versioning or disable versioning to test out templates.

Once I had that working, I tried using a batch request in Postman. Here's the working request I used:

```http
POST http://localhost:60351/Services/odata/$batch HTTP/1.1
User-Agent: Fiddler
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b
Host: localhost:60351
Content-Length: 686

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http
Content-Transfer-Encoding:binary

GET services/api/values HTTP/1.1


--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http
Content-Transfer-Encoding:binary

GET services/api/values/42/constants HTTP/1.1


--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http
Content-Transfer-Encoding:binary

GET services/odata/Employees(1) HTTP/1.1


--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http
Content-Transfer-Encoding:binary

DELETE services/odata/Employees(3) HTTP/1.1


--batch_36522ad7-fc75-4b56-8c71-56071383e77b--
```

And here is the response:

```
HTTP/1.1 200 OK
Content-Type: multipart/mixed; boundary=batchresponse_3916ea37-f27a-4272-88e5-6bbab12e5a09
Server: Microsoft-IIS/10.0
OData-Version: 4.0
X-SourceFiles: =?UTF-8?B?QzpcRGV2XFByb2plY3RzXFJuRFw0NTFBcGlWZXJzaW9uaW5nXDQ1MVdlYkFwaVxvZGF0YVwkYmF0Y2g=?=
X-Powered-By: ASP.NET
Date: Mon, 02 Oct 2017 01:54:23 GMT
Content-Length: 1200

--batchresponse_3916ea37-f27a-4272-88e5-6bbab12e5a09
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
api-supported-versions: 1.0
Content-Type: application/json; charset=utf-8

"from values controller without any versions"
--batchresponse_3916ea37-f27a-4272-88e5-6bbab12e5a09
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
api-supported-versions: 1.0
Content-Type: application/json; charset=utf-8

"Constants for 42."
--batchresponse_3916ea37-f27a-4272-88e5-6bbab12e5a09
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
api-supported-versions: 1.0
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true
OData-Version: 4.0

{
  "@odata.context":"http://localhost:60351/Services/odata/$metadata#Employees","value":[
    {
      "EmployeeId":1,"FirstName":"kqwcgdaq.fim","LastName":"b1k42fth.szx"
    }
  ]
}
--batchresponse_3916ea37-f27a-4272-88e5-6bbab12e5a09
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 204 No Content
api-supported-versions: 1.0


--batchresponse_3916ea37-f27a-4272-88e5-6bbab12e5a09--
```
[V451VersionCheck.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1347733/V451VersionCheck.zip)

**Comment by d-saravanan** [comment]
Thanks for your response. I will check out with my original source, this exercise served a good understanding of routing. I will make corresponding change and let you know help required if any.

Your help is greatly appreciated :)

**Comment by commonsensesoftware** [comment]
I have the impression you were able to get batching working as expected. If you continue to encounter issues, feel free to come back or reopen the issue. Thanks.
