### ISSUE TITLE
A fix in the wiki (Deprecating a Service Version)

### ISSUE THREAD

**Issue by hikalkan** [Microsoft/aspnet-api-versioning#203]
I suppose the example has missing ``MapToApiVersion( "1.0" )`` for Get method. It should be:

````C#
[ApiVersion( "2.0" )]
[ApiVersion( "1.0", Deprecated = true )]
[Route( "api/[controller]" )]
public class HelloWorldController : Controller
{
    [HttpGet, MapToApiVersion( "1.0" )]
    public string Get() => "Hello world!"

    [HttpGet, MapToApiVersion( "2.0" )]
    public string GetV2() => "Hello world v2.0!";
}

[ApiVersion( "2.0" )]
[ApiVersion( "1.0", Deprecated = true )]
[Route( "api/v{version:apiVersion}/[controller]" )]
public class HelloWorldController : Controller
{
    [HttpGet, MapToApiVersion( "1.0" )]
    public string Get() => "Hello world!"

    [HttpGet, MapToApiVersion( "2.0" )]
    public string GetV2() => "Hello world v2.0!";
}
````

Otherwise I'm getting exception when I call v2.0 indicates that there are multiple actions for the same path. I suppose ``[GET] /api/v2/helloworld`` matches both actions.

Maybe I'm wrong and this error occurs because of my customizations, but I wanted to inform you in case of it's missing.

**Comment by hikalkan** [comment]
Additional info: It works normally, but gets exception for swagger:

````
NotSupportedException: HTTP method "GET" & path "api/v{api-version}/identity/fixture" overloaded by actions - Volo.Abp.Identity.FixtureController.Get (Volo.Abp.Identity.HttpApi),Volo.Abp.Identity.FixtureController.Get3 (Volo.Abp.Identity.HttpApi). Actions require unique method/path combination for Swagger
````

My code:

````C#
    [ApiVersion("3.0")]
    [ApiVersion("2.0", Deprecated = true)]
    [Route("api/v{api-version:apiVersion}/identity/fixture")]
    public class FixtureController : Controller
    {
        [HttpGet]
        public int Get()
        {
            return 41;
        }

        [HttpGet, MapToApiVersion("3.0")]
        public int Get3()
        {
            return 42;
        }

        [HttpPost]
        public int Post()
        {
            return 43;
        }
    }
````

**Comment by commonsensesoftware** [comment]
The `[MapToApiVersion]` is optional. I intentionally omit it from many examples. By default, all actions have the same API version as their defining controller. In most cases of version interleaving, a new action is added or is _overridden_ on a controller. `[MapToApiVersion]` provides a way to identify which API version the action should match to. Once explicit API versions are mapped, the inferred controller versions are no longer considered. In general, this requires fewer applications of attributes on actions. If a controller has enough versions, it's possible that inversing the behavior would yield fewer attributes. If you're in this situation though, it's probably time to consider breaking the controller into multiple classes.

I think what may be confusing in the wiki is that the controllers shown are two, distinct examples. They can be defined side-by-side in the same application. I mix and match various styles in the examples, but in this particular case, it appears that the two controllers are together. I'm make the change. Thanks for pointing that out.

How are you integrating with Swagger? Are you using the API Explorer package for API versioning? I don't think that I tested Swagger scenarios for interleaved API versions. It's possible there may be a bug.

**Comment by commonsensesoftware** [comment]
I updated the wiki page. Hopefully, that makes things a little more clearer.

**Comment by hikalkan** [comment]
> How are you integrating with Swagger? Are you using the API Explorer package for API versioning.

Yes, using Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer package 2.0.

Actually, I'm just trying different combinations to better understand api versioning. I would not mix different versions in same controller normally. Thank you :)

**Comment by commonsensesoftware** [comment]
This seems to be address. Thanks for providing feedback. It helps everyone. Keep it coming. ;)
