### ISSUE TITLE
Api-versioning and RouteBuilder not working together in Core 2.0

### ISSUE THREAD

**Issue by jnUser** [Microsoft/aspnet-api-versioning#204]
I am upgradin our Core 1.1.2 project to core 2.0 and I am having an issue with Mvc.Versioning
no longer working with RouteBuilder.

I am using RouteBuilder to branch the pipeline for api and swagger.

public void Configure(IApplicationBuilder app, IHostingEnvironment env,
      IServiceProvider serviceProvider, ILoggerFactory loggerFactory, IApplicationLifetime appLifetime)
    {
 
      // Branch pipeline for api and swagger
      var routeBuilder = new RouteBuilder(app);
      routeBuilder.MapMiddlewareRoute("api/{*path}", (IApplicationBuilder api) =>
      {
        api.UseCors(builder =>
         builder.AllowAnyOrigin()
           .AllowAnyHeader()
           .AllowAnyMethod());

        api.UseAuthentication();

        api.UseMiddleware<ErrorResponseMiddleware>();

        api.UseMultitenancy<Tenant>();

        api.UseUserResolution<User>();

        api.UseMvc();

      });

      if (enableSwagger)
      {
        routeBuilder.MapMiddlewareRoute("swagger/{*path}", (IApplicationBuilder swag) =>
        {
          swag.UseStaticFiles();

          initializeAutoMapper(serviceProvider);

          swag.UseSwagger(c =>
          {
            c.PreSerializeFilters.Add((swaggerDoc, httpRequest) =>
            {
              swaggerDoc.Host = httpRequest.Host.Value;
            });
          });

          swag.UseSwaggerUI(c =>
          {
            c.SwaggerEndpoint("/swagger/v1/swagger.json", "API v1");
            c.SwaggerEndpoint("/swagger/v2/swagger.json", "API v2");

            if (!enableSwaggerDataSubmit)
              c.SupportedSubmitMethods(new[] { "get", "head" });
          });
        });
      }

      var router = routeBuilder.Build();
      app.UseRouter(router);
    }

On ConfigureServices I add versioning:
    services.AddApiVersioning(o =>
      {
        o.AssumeDefaultVersionWhenUnspecified = true;
        o.DefaultApiVersion = new Microsoft.AspNetCore.Mvc.ApiVersion(2, 0);
        o.ApiVersionReader = new HeaderApiVersionReader("api-version");
      });

This code has worked on Core 1.1.2. On Core 2.0 endpoint returns 404 and does not cause any exeptions.

If I remove services.AddApiVersioning the api works.
If I don't use RouteBuilder the api and ApiVersioning works.

Has something changed on declaring ApiVersioning in 2.0 or is this a bug?

**Comment by jgoelten** [comment]
It looks like as if the [IStartupFilter](https://github.com/Microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.Extensions.DependencyInjection/IServiceCollectionExtensions.cs) in the IServiceCollectionExtensions.cs does not register the required routePolicy service (IApiVersionRoutePolicy). In another project I had to manually register this policy due to a custom pipeline architecture. This solved the issue in that case. Right now I am facing the same issue as @jnUser, even manual registration does not apply the route policy.

**Comment by jgoelten** [comment]
Update: To workaround this issue I solved it as followed:

1. In the Configure(...) startup method resolve the versioning route policy manually
2. Manually add the route policy as new Mvc Route

The following two lines solve the routing issues till we get a fixed version:
```
            var routePolicy = app.ApplicationServices.GetService<IApiVersionRoutePolicy>();
            app.UseMvc(o => o.Routes.Add(routePolicy));
```

**Comment by commonsensesoftware** [comment]
@jnUser and @jgoelten, did you happen to see/review the [known ASP.NET Core routing limitations](../wiki/Known-Limitations#aspnet-core-routing)? I believe for you scenarios, that will get you what you need. A far more extreme solution would be to follow the direction that @jgoelten is suggesting. I provided a detailed explanation of how to setup things up yourself in #194, though I'm not sure you are exactly in the same scenario. That case was rather unique.

If you're not familiar with the background to this issue, there was a change in 1.1+ to fix a different issue that has resulted required configuration changes for some. In short, the ASP.NET Core infrastructure can make multiple controller action selection passes. This results in API versioning not being able to make a final decision during action selection. I've been in discussion with the ASP.NET team. For now, the solution is to inject a _catch-all_ route that can make the final decision based on all collated candidate actions. In order for that to work, it must be the last router in the MVC part of the pipeline. I'm hoping we'll find some way to make a decision and short-circuit upfront as is the case with the vanilla action selector.

**Comment by commonsensesoftware** [comment]
@jgoelten thanks for confirming your solution.

@jnUser did any of these suggestions work for you?

**Comment by jnUser** [comment]
I ended up using parts of  your and @jgoelten solution and got it working. I think the solution @jgoelten  gave would have suffixed, but for some reason it did not work in testing, so I ended up mixing your solution in as well. It works now. Thanks.
