### ISSUE TITLE
No check if description.RoutInfo is null in Sample Code for Operation Filter

### ISSUE THREAD

**Issue by bjoernhoeper** [Microsoft/aspnet-api-versioning#210]
Before this line:

https://github.com/Microsoft/aspnet-api-versioning/blob/52d02228db5b7ccbdc6eea596cd4b7aa90e4bb4c/samples/aspnetcore/SwaggerSample/SwaggerDefaultValues.cs#L32

it should be checked that the `description.RouteInfo != null`. If you have query parameters in your controllers action methods the route info is null and the whole method fails (and also swagger generation and everything that depends on it) with a `NullReferenceException`.
Maybe there is an even more sophisticated solution that I did not see at the moment.

**Comment by commonsensesoftware** [comment]
>Disclaimer: The samples are purely for illustrative purposes and intentionally are not hardened or otherwise production-ready. No warranties, expressed or implied, are given as to their quality.

That said, the examples should work without issue. If something is not working, then I definitely want to fix it. If something doesn't work after someone changes something, I'm less concerned about that.

It seems odd that the `RouteInfo` would be `null`, but I've noticed a few cases where things were `null` in unexpected places. In fact, PR #202 is looking to address some of these cases. I'm not opposed hardening against NRE, but I want to better understand what causes them. My preference would be to avoid `null` altogether. If it can't be avoided, I'd like a few repro cases that can be incorporated into the test suite.
