### ISSUE TITLE
Error with Get and Get(int id)

### ISSUE THREAD

**Issue by SilverXXX** [Microsoft/aspnet-api-versioning#216]
I'm getting an error using the following controller:
```csharp
namespace WebApi.Controllers
{
    [ApiVersion("1.0")]
    [Route("v{version:apiVersion}/values")]
    public class ValuesController : ApiController
    {
          [HttpGet]
          public IEnumerable<string> Get()
          {
              return new string[] { "value controller 1", "value controller 2" };
          }

          [HttpGet]
          [Route("{id:int}")]
          public string Get(int id)
          {
              return "value " + id;
          }
          //removed methods
    }
}
```
and the following WebApiConfig.cs:
```csharp
namespace DocFxWebApi
{
    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services
            config.AddApiVersioning();

            var constraintResolver = new DefaultInlineConstraintResolver()
            {
                ConstraintMap = {
                    ["apiVersion"] = typeof( ApiVersionRouteConstraint )
                }
            };

            // Web API routes
            config.MapHttpAttributeRoutes(constraintResolver);
        }
    }
}
```

Going to v1.0/values/5 always return 404

**Comment by commonsensesoftware** [comment]
Can you elaborate on the error. What's the message and against which routes?  Also, I notice that your route attributes are incongruent. For clarity, I would recommend:

```c#
namespace WebApi.Controllers
{
    [ApiVersion("1.0")]
    [RoutePrefix("v{version:apiVersion}/values")]
    public class ValuesController : ApiController
    {
          [HttpGet]
          [Route]
          public IEnumerable<string> Get()
          {
              return new string[] { "value controller 1", "value controller 2" };
          }

          [HttpGet]
          [Route("{id:int}")]
          public string Get(int id)
          {
              return "value " + id;
          }
          //removed methods
    }
}
```
That _might_ even solve the issue.

**Comment by SilverXXX** [comment]
Yes, sorry it was quite lacking in details.
If i add [Route] like in your code i get for the first Get:
```xml
<Error>
<Error>
<Code>UnsupportedApiVersion</Code>
<Message>
The requested resource with API version '1' does not support HTTP method 'GET'.
</Message>
<InnerError>
<Message>
No route providing a controller name with API version '1' was found to match HTTP method 'GET' and request URI 'http://localhost:1032/v1/values'.
</Message>
</InnerError>
</Error>
</Error>
```
and 404 for the second one

Removing the first Route like in my sample, i get the correct answer for the first get, and 404 for the second one

**Comment by commonsensesoftware** [comment]
Did you also change the `[Route]` on the controller to `[RoutePrefix]`? I haven't been able to reproduce your scenario - yet. I've attached a working example based on your information ([ApiVersionRepro.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1527348/ApiVersionRepro.zip)).

The route provides the following results:

| Request URL | Status Code | Body |
| -------------- | -------------- | ----- |
| `http://localhost/v1/values` | 200 | `["value controller 1", "value controller 2"]` |
| `http://localhost/v1/values/42` | 200 | `"value 42"` |

This would seem to be the expected results. Perhaps you can compare it against your configuration.

**Comment by SilverXXX** [comment]
Thanks, i didn't notice `RoutePrefix` instead of `Route` , i didn't see that in the various docs.
It solved everything
