### ISSUE TITLE
ArgumentNullException on initial routing after upgrade to .NET Core 2.0

### ISSUE THREAD

**Issue by xakep139** [Microsoft/aspnet-api-versioning#222]
We caught an exception on initial routing at our project [NuClear VStore](https://github.com/2gis/nuclear-vstore) after migrating to .Net Core 2.0, here is the stacktrace:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: version
   at Microsoft.AspNetCore.Mvc.Versioning.ApiVersionModelExtensions.Aggregate(ApiVersionModel version, IEnumerable`1 otherVersions)
   at Microsoft.AspNetCore.Mvc.Abstractions.ActionDescriptorExtensions.AggregateAllVersions(ActionDescriptor action, IEnumerable`1 matchingActions)
   at Microsoft.AspNetCore.Mvc.Routing.DefaultApiVersionRoutePolicy.OnSingleMatch(RouteContext context, ActionSelectionResult selectionResult, ActionDescriptorMatch match)
   at Microsoft.AspNetCore.Mvc.Routing.DefaultApiVersionRoutePolicy.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuClear.VStore.Host.Middleware.CrosscuttingTraceIdentifierMiddleware.<Invoke>d__2.MoveNext() in /builds/ams/vstore/src/VStore.Host/Middleware/CrosscuttingTraceIdentifierMiddleware.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuClear.VStore.Host.Middleware.HealthCheckMiddleware.<Invoke>d__3.MoveNext() in /builds/ams/vstore/src/VStore.Host/Middleware/HealthCheckMiddleware.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```
Two first requests reached route `GET /api/1.0/objects/{id:long}/versions` (action [`GetVersions(long id)`](https://github.com/2gis/nuclear-vstore/blob/master/src/VStore.Host/Controllers/ObjectsController.cs#L84)) right after application startup. Then both requests finished up simultaneously with status code 500 and further requests on this route matched the incorrect action [`GetVersion(long id, string versionId)`](https://github.com/2gis/nuclear-vstore/blob/master/src/VStore.Host/Controllers/ObjectsController.cs#L147) linked with route `GET /api/1.0/objects/{id:long}/{versionId}`
Unfortunately we couldn't reproduce the issue nor create a simple repro. We suppose this bug could be caused by multithreading scenario at initial route resolving.
It's worth mentioning that application was running in Kubernetes cluster (shipped in Docker image), so it has been compiled with runtime 'ubuntu.14.04-x64'.

**Comment by commonsensesoftware** [comment]
I presume that things worked at some point. I'd like to try to boil down the bare bones to understand where things are going sideways. Your route templates look ambiguous to me. The segment `versions` can be substituted for the route parameter `{versionId}`. There might be a scenario where it _can_ work, but it will likely be very particular as to the order of registration.

It appears that you are versioning by the URL, but I don't see the API version route constraint. Should I assume that the templates are:

* `api/{version:apiVersion}/objects/{id:long}/versions`
* `api/{version:apiVersion}/objects/{id:long}/{versionId}`

It seems like that may not be the case.

Ultimately, it appears that you have applied API versioning, are going through the versioned pipeline, but you aren't actually _using_ API versioning. When you use the URL segment method of API versioning, you **must** use the provided route constraint in your template. That's the only way the infrastructure knows how to get the _magic string_ from the URL.

Regardless, it seems like you may have found a bug where you reach the final policy decision, but the underlying API version model used to make the decision is `null` (e.g. not available). This also suggests that you have not applied the `[ApiVersion]` attribute anywhere, nor used conventions, nor allowed for a default API version (which isn't really possible with the URL method anyway).

Creating a repro with your route templates shouldn't be terribly difficult, but understanding your configuration and setup with respect to API versioning would be useful to make sure we're comparing _apples to apples_.

**Comment by xakep139** [comment]
Surely we have applied both API version route constraint and `[ApiVersion]` attribute, you can see it [here](https://github.com/2gis/nuclear-vstore/blob/9b1f38afebc3f442f0235f9115337cfd6e830c36/src/VStore.Host/Controllers/ObjectsController.cs#L20).
Our system is currently running in production perfectly under .Net Core 1.1.4 runtime and we don't experience any issues with routing since you have fixed https://github.com/Microsoft/aspnet-api-versioning/issues/148.
I want to be clear about reproducing the issue - this exception was caught only on one POD on production after upgrading the runtime and packages, other 5 PODs worked just fine. Two first requests on this POD broke this route, other routes worked fine. So the issue had fired just once and we rolled back our release in order to investigate the issue.

**Comment by commonsensesoftware** [comment]
Weird. Out of curiosity, which version were you upgrading from? I can see that the error occurs in an internal extension method where the API version models are aggregated (see [Line 37](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Abstractions/ActionDescriptorExtensions.cs#L37)). An action _should_ never have a `null` API version model here.

In fact, versioned controllers should never a `null` API version model period. The API version models are built and defined by application conventions very early on. The only case I've seen where that happens is with the new Razor Pages. There was a bug filed for that, which I've fixed, but haven't published yet. As I recall, it failed in a completely different way though. To eliminate the obvious, you aren't using Razor Pages are you? I took a peek at your source and I didn't notice it (but I didn't look very deep).

To help repro, which version of ASP.NET Core and API versioning are you using?

Thanks

**Comment by tukaef** [comment]
Hi,

No, we aren't using Razor Pages.
We've upgraded ASP.NET Core from `1.1.4` to `2.0.1` and API versioning from `1.2.1` to `2.0.0`. 
We've also upgraded runtime deps from `dotnet:1.1.4-runtime-deps` to `dotnet:2.0.3-runtime-deps-jessie`.

**Comment by commonsensesoftware** [comment]
Interesting... There really haven't been any significant changes from 1.2.0 to 2.0.0.  The version bump is almost entirely just upgrading and aligning to ASP.NET Core 2.0.0.

I'll try to put together a repro based on what you have provided thus far. Unfortunately, I suspect this may be difficult to track down. Out of curiosity, what is the frequency that you see this happen?

**Comment by tukaef** [comment]
As @xakep139 said, we faced this only once - at production environment. Then we immediately rolled back to 1.x. After that we haven't managed to reproduce the issue.

**Comment by commonsensesoftware** [comment]
Did you ever find any other information on this?

I noticed from the stack trace that you're using the **Exception Handler** middleware. Is there any chance that an exception your app was thrown and your exception policy redirects to another page? That seems like an odd behavior for an API, but I recently saw someone else do something similar. Should that be the case (or maybe the case), this could result in the API versioning policy encountering `null` and ultimately this error.

I may be able to reproduce this behavior by using the **Exception Handler** middleware, triggering an explicit exception, and then see what happens. This may be a scenario that _should never happen_, but may need to be defended against.

Please share anything new you may have collected on your side.

**Comment by tukaef** [comment]
Nope, we didn't. 

Here is our exception handler config, there is no redirect:
```
app.UseExceptionHandler(
  new ExceptionHandlerOptions
    {
      ExceptionHandler =
        async context =>
          {
            var feature = context.Features.Get<IExceptionHandlerFeature>();
            var error = new JObject
                            {
                                { "requestId", context.TraceIdentifier },
                                { "code", "unhandledException" },
                                { "message", feature.Error.Message }
                            };

            if (env.IsDevelopment())
            {
                error.Add("details", feature.Error.ToString());
            }

            context.Response.ContentType = ContentType.Json;
            await context.Response.WriteAsync(new JObject(new JProperty("error", error)).ToString());
          }
    });
```

**Comment by commonsensesoftware** [comment]
Do you know the URL of the request that failed?

I tried integrating your exception handler and things worked as expected. The stack trace you provided leads back to [here](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Abstractions/ActionDescriptorExtensions.cs#L37); however, I don't see how this could happen. The models are pre-built via the [ApiVersionConvention.cs](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionConvention.cs). The only way that I know or have seen where a model is not assigned is when the action doesn't match the convention, such as Razor Pages; however the result was a route fail and not a NullReferenceException. You can also see in the [ApiVersionActionSelector.cs](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs#L210) that a candidate is not matched when it's **ApiVersionModel** is `null`. I don't see how this check can be valid and later be invalid during the same request.

I'm not sure how else to continue the investigation without a repro, but this isn't like anything I've seen before. Since the other PODs were working is there any chance this is external? Somehow one POD rolled out incorrectly. I'm open to any ideas you many have. I'm grabbing at straws here.

**Comment by xakep139** [comment]
As I've mentioned in first comment URLs of requests look like `/api/1.0/objects/1022980760354685016/versions` (with different identifiers). We assume this could be some kind of race condition on route initialization.

**Comment by commonsensesoftware** [comment]
Arguably you can never rule out a race condition, but that seems unlikely. That would have to occur at the ASP.NET Core level itself. Versioning doesn't change routing. It only change action selection. The API version models are built at startup by ASP.NET and are only ever changed when they are aggregated per request, per action. Since they are only ever replaced, there is no chance for a `null`. Furthermore, if the model was `null` during action selection, it won't be matched.

Now that I have the template and an example of what a completed template looks like in an actual request, I'll see if I can't setup a repro. I also published a new version of the package that includes a change to ensure actions with `null` models are not selected. This is meant to solve the issue with Razor Pages, but it _might_ fix your scenario. If you have a chance to experiment, it might be worth a try.

**Comment by xakep139** [comment]
@commonsensesoftware, we haven't faced this bug after updating `Microsoft.AspNetCore.Mvc.Versioning` to 2.1.0. I suppose this issue could be closed for now.

**Comment by commonsensesoftware** [comment]
Thanks for the heads up. If you see it come back, please share whatever details you can and I'll be happy to keep digging into it.
