### ISSUE TITLE
Abstract Base Class Routing with Web API Versioning

### ISSUE THREAD

**Issue by zerosnap** [Microsoft/aspnet-api-versioning#242]
I've managed to get everything working except for one issue.  We have an abstract base class we're inheriting from like so:  

> public abstract class BaseEntitySearchController
> { 
> [Route("Entity/Search")]
> public virtual IEnumerable<EntityModel> Search(EntitySearchModel model)
> { 
>      return null;
> }

> [ApiVersion(RLApiVersions.V2)]
> [RoutePrefix("v{apiVersion:apiVersion}")]
> public class EntityController : BaseEntitySearchController
> {
> }

The WebApiConfig.cs:

> public void Register(HttpConfiguration config)
> {
> var constraintResolver = new DefaultInlineConstraintResolver
> {
>      ConstraintMap =
>      {
>           ["apiVersion"] = typeof(ApiVersionRouteConstraint)
>      }
>  };
> 
> var apiExplorer = new UrlVersionedApiExplorer(config);
> config.Services.Replace(typeof(IApiExplorer), apiExplorer);
> config.MapHttpAttributeRoutes(constraintResolver);
> config.AddApiVersioning();
> }

> UrlVersionedApiExplorer (from help here):
> 	public class UrlVersionedApiExplorer : VersionedApiExplorer
> 	{
> 		public UrlVersionedApiExplorer(HttpConfiguration configuration)
> 			: base(configuration, new ApiExplorerOptions(configuration) {GroupNameFormat = "'v'VVV"})
> 		{
> 		}

> 		protected override ApiDescriptionGroupCollection InitializeApiDescriptions()
> 		{
> 			var groups = base.InitializeApiDescriptions();
> 
> 			foreach (var group in groups)
> 			{
> 				foreach (var description in group.ApiDescriptions)
> 				{
> 					var url = description.RelativePath;
> 					url = url.Replace("{apiVersion}",
> 						description.ApiVersion.MinorVersion > 0
> 							? description.ApiVersion.ToString("VVVV")
> 							: description.ApiVersion.ToString("VVV"));
> 					description.RelativePath = url;
> 				}
> 			}
> 			return groups;
> 		}
> 	}

These base class routes showed up and worked properly in Swagger and worked as expected with only one version. Now, the endpoints no longer show up in Swagger and hitting the endpoint throws the following error:

> [System.InvalidOperationException: Multiple actions were found that match the request:   Search on type RightsLine.RestApi.V2.Controllers.EntityController  SearchCount on type RightsLine.RestApi.V2.Controllers.EntityController  SearchRelationshipsCount on type RightsLine.RestApi.V2.Controllers.EntityController  SearchRelationships on type RightsLine.RestApi.V2.Controllers.EntityController  SearchDeletedRelationships on type RightsLine.RestApi.V2.Controllers.EntityController     at Microsoft.Web.Http.Controllers.ApiVersionActionSelector.SelectActionVersion(HttpControllerContext controllerContext, IReadOnlyList`1 candidateActions)     at Microsoft.Web.Http.Controllers.ApiVersionActionSelector.ActionSelectorCacheItem.FindAction(HttpControllerContext controllerContext, Func`3 selector, Boolean ignoreSubRoutes)     at Microsoft.Web.Http.Controllers.ApiVersionActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext, Func`3 selector)     at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)     at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()  --- End of stack trace from previous location where exception was thrown ---

Any ideas on how to get this one last thing fixed would be greatly appreciated.

**Comment by commonsensesoftware** [comment]
Inheritance seems to do nothing but cause developers grief in this context.  The built-in **DefaultDirectRouteProvider** does **not** support inheritance. This means that `[RoutePrefix]` and `[Route]` attributes declared on the base class are ignored.

There are a few ways you can address this:
1. Replace the default **IDirectRouteProvider** with your own implementation that supports inheritance
2. Only declare the routing attributes on the subclasses

Unfortunately, this has everything to do with how Web API works and little to do with API Versioning. If you choose option 2, you can refactor to:

```c#
public abstract class BaseEntitySearchController
{
    public abstract IHttpActionResult Search(EntitySearchModel model);
}

[ApiVersion(RLApiVersions.V2)]
[RoutePrefix("v{apiVersion:apiVersion}/Entity")]
public class EntityController : BaseEntitySearchController
{
    [HttpPost]
    [Route(nameof(Search))]
    public override IHttpActionResult Search(EntitySearchModel model) => Ok(model);
}
```

You can move all kinds of things to the base class, but not the routing attributes.  If you'd rather make the IDirectRouteProvider support honoring inherited routing attributes, it's not a difficult change. There are some examples of how to achieve that from previous threads. You'll want review the various other [issues](../issues?utf8=%E2%9C%93&q=is%3Aissue+inheritance) on this topic. Hopefully this gets you on the path to success.

**Comment by zerosnap** [comment]
I ended up doing almost exactly what you suggested, funny enough.  Thanks!
