### ISSUE TITLE
Versioning not working when using AppBuilder branching

### ISSUE THREAD

**Issue by srivelicheti** [Microsoft/aspnet-api-versioning#243]
I am using branching (using IApplicationBuilder.Map) to add new features to existing AspNetCore Web Api that uses versioning. But looks like once I add a branch at the root, I get a 404 for all of the routes.

```
 public void Configure( IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) 
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            //app.UseMvc();
            **app.Map("/test", appBuilder =>**
            {
                appBuilder.UseMvc();
            });

        }
```

Appreciate your help. Thank you

**Comment by commonsensesoftware** [comment]
I believe what you are looking for is the setup described in [this comment](194#issuecomment-333644220).

API Versioning has an injectable **IApiVersionRoutePolicy** which also happens to be an **IRouter** (currently). You need to add this to the branch a la:

```c#
app.Map( "/test", a => a.UseMvc().UseRouter( b => b.Routes.Add( policy ) ) );
```

Give that a try and let me know how it works out.

**Comment by srivelicheti** [comment]
Thank you, that fixes it.
