### ISSUE TITLE
Swagger integration -- two service scopes

### ISSUE THREAD

**Issue by Mardoxx** [Microsoft/aspnet-api-versioning#246]
https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-core

These docs say to do this

```csharp
    services.AddSwaggerGen(
        options =>
        {
            var provider = services.BuildServiceProvider()
                                   .GetRequiredService<IApiVersionDescriptionProvider>();

            foreach ( var description in provider.ApiVersionDescriptions )
            {
                options.SwaggerDoc(
                    description.GroupName,
                    new Info()
                    {
                        Title = $"Sample API {description.ApiVersion}",
                        Version = description.ApiVersion.ToString()
                    } );
            }
        } );
```

Does this not mean you have two service scopes for the lifetime of your application? Is this not a bad idea?

**Comment by commonsensesoftware** [comment]
Arguably that's true, but it shouldn't matter. This service is **only** used here. It's needed to collate the API versions to build the Swagger document. Since `services` is within a closure, it's evaluation is delayed until it's needed (and the rest of the services have been registered).

If you know of an alternate way to retrieve the **IApiVersionDescriptionProvider** service here, please share and I'll update the examples. API Versioning has no direct dependencies on Swagger/Swashbuckle. You can change things as you see fit for this. However, if you do have a _better_ way, I'm happy to update things to help others fall into _the pit of success_.  Thanks.

**Comment by Mardoxx** [comment]
I think I'm good! Thanks. As I understand the service scope object will be disposed of after this closure has been invoked wont it? So unless you're doing something dumb (like capturing a service from it e.g.) it shouldn't hang around should it?

**Comment by commonsensesoftware** [comment]
Correct. This interface is really just an abstraction for a property/method. At this point in the code, you're just asking for a thing that can collate and iterate all defined API versions. After this one usage, it is never used again - anywhere.  Should you find that to the contrary, let me know and I'll fix it.  Thanks.

**Comment by Mardoxx** [comment]
That's great! That was my only concern really. I suppose for added piece of mind could wrap it in a `using`, it isdisposable isn't it?

Thanks 😁

**Comment by ericsampson** [comment]
@commonsensesoftware since Core 3, this pattern is throwing a warning as discussed here:
https://github.com/dotnet/aspnetcore/issues/14587
is it possible to make this late-resolved, like other package authors have done (for example see https://github.com/Particular/NServiceBus.RavenDB/issues/445)

**Comment by commonsensesoftware** [comment]
@ericsampson  It is and has been for some time. The examples also demonstrate the configuration. Things are wired up [here](../blob/master/samples/aspnetcore/SwaggerSample/Startup.cs#L57) and are implemented [here](../blob/master/samples/aspnetcore/SwaggerSample/ConfigureSwaggerOptions.cs). I hope that helps.

**Comment by ericsampson** [comment]
@commonsensesoftware thank you so much - I must have missed that change, sorry for the noise! I'll pull it into our codebases. Thanks again.
