### ISSUE TITLE
NullReferenceException in ApiVersionParameterDescriptionContext.RemoveAllParametersExcept

### ISSUE THREAD

**Issue by dbrink** [Microsoft/aspnet-api-versioning#250]
When using the ApiExplorer in AspNet Core a null reference exception is thrown if the API defines a parameter as part of a route, but does not have matching parameter on the controller method.  

```
[HttpGet("foo/{unmatched}"]
public string GetFoo()
{
   return "foo";
}

```

With no matching C# parameter on GetFoo() the ApiParameterDescription's ModelMetadata is null.  A null coalescing operator should fix the problem.

```
void RemoveAllParametersExcept( ApiParameterDescription parameter )
{
// code omitted
   if ( otherParameter?.ModelMetadata.DataTypeName == nameof( ApiVersion ) )
   {
      collection.Remove( otherParameter );
   }
// code omitted
}

```

**Comment by commonsensesoftware** [comment]
Yep ... except you want to coalesce on the model metadata like so `otherParameter.ModelMetadata?.DataTypeName == nameof( ApiVersion )`.  It's not the parameter that's null, it's the model metadata.

I had new feature I was about to roll out for the API Explorer anyway. I should have this patched and published tonight or tomorrow. Thanks.

**Comment by dbrink** [comment]
Ah, yes.  Thanks for the catch and incorporating the fix.

**Comment by wburgers** [comment]
Is this bugfix released yet? (I could not find a nuget version newer than jan 2018, while this bugfix is done on the 9th of feb)
I am using version 1.2.1 of Microsoft.AspNetCore.Mvc.Versioning.
I also get to see a nullref.
Is it possible to backport this bugfix to 1.2.2 perhaps?

**Comment by commonsensesoftware** [comment]
It's _possible_, but kind of a pain. Is there a particular reason to not move forward? As an _army of one_, it's hard to maintain multiple different version branches on 3 difference platforms. This would require creating a divergent branch with the fix or publishing a package version with the fix which doesn't correspond back to source. Neither is very amicable scenario.

**Comment by wburgers** [comment]
No, there is no particular reason.
We just lag behind in our asp.net core maintenance 😇.
I'll see if I can upgrade our webapp.
Thanks for getting back to me!
