### ISSUE TITLE
/samples/aspnetcore/SwaggerSample/ cannot build

### ISSUE THREAD

**Issue by Lechus** [Microsoft/aspnet-api-versioning#251]
D:\OtherProjects\aspnet-api-versioning\samples\aspnetcore\SwaggerSample>dotnet build
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 37.95 ms for D:\OtherProjects\aspnet-api-versioning\src\Microsoft.AspNetCore.Mvc.Versioning\Microsoft.AspNetCore.Mvc.Versioning.csproj.
  Restore completed in 37.95 ms for D:\OtherProjects\aspnet-api-versioning\src\Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer\Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.csproj.
  Restore completed in 68.61 ms for D:\OtherProjects\aspnet-api-versioning\samples\aspnetcore\SwaggerSample\SwaggerSample.csproj.
  Restore completed in 87.25 ms for D:\OtherProjects\aspnet-api-versioning\samples\aspnetcore\SwaggerSample\SwaggerSample.csproj.  Microsoft.AspNetCore.Mvc.Versioning -> D:\OtherProjects\aspnet-api-versioning\src\Microsoft.AspNetCore.Mvc.Versioning\bin\Debug\netstandard2.0\Microsoft.AspNetCore.Mvc.Versioning.dll
  Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer -> D:\OtherProjects\aspnet-api-versioning\src\Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer\bin\Debug\netstandard2.0\Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.dll
C:\Program Files\dotnet\sdk\2.1.3\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\2.1.3\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\OtherProjects\aspnet-api-versioning\samples\aspnetcore\SwaggerSample\SwaggerSample.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.1.3\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\2.1.3\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\OtherProjects\aspnet-api-versioning\samples\aspnetcore\SwaggerSample\SwaggerSample.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:13.00

**Comment by commonsensesoftware** [comment]
Sadly, I'm aware of this issue, but don't know what the fix is - yet. There seems to be a bug with the targets in the .NET SDK. I've internally engaged with the team, but I don't have any additional details to share. I'll share whatever I find out or if there is an issue filed in their repo.

To workaround this issue, you'll have to use MSBuild directly. The following should be useful having near equivalent behavior to `dotnet`.

**Build** - `msbound /v:m`
**Restore** - `msbuild /v:m /t:Restore`
**Restore** and **Build** - `msbuild /v:m /t:Restore;Build`

This issue is actually a problem for me in the CI build. I've been investigating, but no solution as of yet. Have I to run ``dotnet test --no-build`.  I feel your pain - literally. I hope to resolve this soon.

**Comment by Lechus** [comment]
Hi @commonsensesoftware 
Cleaned bin/obj folders and removing Net.Compilers package helped to build and run the project.
`<!--    <PackageReference Include="Microsoft.Net.Compilers" Version="2.6.0" PrivateAssets="All" /> -->`
https://stackoverflow.com/questions/32150204/buildtasks-csc-task-could-not-be-loaded-from-the-assembly

**Comment by commonsensesoftware** [comment]
Good find. This does appear to fix the issue. Weird. As I recall, I needed to add the `Microsoft.Net.Compilers` package for code analysis at one point. I guess that need is now gone. You should see the change momentarily. Thanks for the assist! ;)
