### ISSUE TITLE
Need help with error response provider

### ISSUE THREAD

**Issue by arpymastro** [Microsoft/aspnet-api-versioning#259]
Hi,

Can you please help with a sample/example for customised error responses?
I checked the wiki on that but I am not quite able to get that.
Thank you!

**Comment by commonsensesoftware** [comment]
The documentation is intentionally light as a means to discourage changing the response behavior, but there isn't anything complex or secret about it. I'm not sure which platform you're targeting, but I would look at the [Web API](../blob/master/src/Microsoft.AspNet.WebApi.Versioning/Versioning/DefaultErrorResponseProvider.cs) and [ASP.NET Core](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/DefaultErrorResponseProvider.cs) implementations of the **DefaultErrorResponseProvider**. This is how things are implemented out-of-the-box. You can choose to extend this base class or roll your own from scratch by implementing **IErrorResponseProvider**. The possible status codes, error codes, and the way that you wire it up in options are all documented in the wiki. It should be straight forward. Most people who have changed the response have only been interested in changing the status code, which is very simple to do.

Let me know if you have more questions.

**Comment by arpymastro** [comment]
Thanks a lot
