### ISSUE TITLE
Api version via custom header does not fire any exception

### ISSUE THREAD

**Issue by cyberbolt** [Microsoft/aspnet-api-versioning#264]
I set up my API versioning via custom header, e.g. x-api-version. 
Regardless If I pass this header inside request or not, or even x-api-version: 121, my controller, which has attribute [ApiVersion("1.0")], executes the action I am requesting. 

Api version options:
`{
            options.ApiVersionReader = new HeaderApiVersionReader("x-api-version");
            options.ReportApiVersions = true;
 }`
I use ASP.NET Web API 2 and Microsoft.AspNet.WebApi.Versioning 2.2.0

**Comment by commonsensesoftware** [comment]
Can you share the other relevant parts of your configuration? If you can share the skeleton that would be helpful too. The world's simplest repro is ideal, but I can probably get you going by just seeing the configured parts.

**Comment by cyberbolt** [comment]
The whole project is using asp net boilerplate (the Web UI), so API configuration is wrapped by ABP too, but I am not iusing ABP web api controllers inside API, just ApiControllers. All exceptions are processed in custom ExceptionFilter, anyway, no any exception thrown in Debug mode.
`public override void Initialize()
        {
            this.IocManager.RegisterAssemblyByConvention(Assembly.GetExecutingAssembly());

            this.Configuration.Modules.AbpWebApi().HttpConfiguration.AddApiVersioning(options =>
            {
                options.ApiVersionReader = new HeaderApiVersionReader("x-api-version");
                options.ReportApiVersions = true;
            });

            this.Configuration.Modules.AbpWebApi().HttpConfiguration.Filters.Add(this.IocManager.Resolve<ApiExceptionFilter>());

            this.Configuration.Modules.AbpWebApi().HttpConfiguration.MapHttpAttributeRoutes();

            this.Configuration.Modules.AbpWebApi().HttpConfiguration.Filters.Add(this.IocManager.Resolve<UowFilter>());

            var requestParametersBinderProvider = new SimpleModelBinderProvider(
                typeof(RequestParameters<DimensionElementFilter>),
                new RequestParametersModelBinder<DimensionElementFilter>());

            var apiFilterBinderProvider = new SimpleModelBinderProvider(
                typeof(DimensionElementFilter),
                new ApiFilterModelBinder<DimensionElementFilter>());

            var paginationRequestParametersBinderProvider = new SimpleModelBinderProvider(
                typeof(PaginationRequestParameters),
                new PaginationRequestParametersModelBinder());

            this.Configuration.Modules.AbpWebApi().HttpConfiguration.Services.Insert(typeof(ModelBinderProvider), 0, requestParametersBinderProvider);
            this.Configuration.Modules.AbpWebApi().HttpConfiguration.Services.Insert(typeof(ModelBinderProvider), 0, apiFilterBinderProvider);
            this.Configuration.Modules.AbpWebApi().HttpConfiguration.Services.Insert(typeof(ModelBinderProvider), 0, paginationRequestParametersBinderProvider);

            this.Configuration.Modules.AbpAutoMapper().Configurators.Add(AutoMapperRegistrar.Initialize);
}`

**Comment by commonsensesoftware** [comment]
I'm not familiar with ABP at all. However, with a little bit of research, I was able to find that it appears to replace the **IHttpControllerSelector** and **IHttpActionSelector** [here](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/eac1d44ba87396075af001fcc55e1a8c41cdd631/src/Abp.Web.Api/WebApi/AbpWebApiModule.cs#L88). This will conflict with API versioning, which also replaces these services. The solution may just a matter of ordering and making sure API versioning is configured last.

@hikalkan has been here before. Perhaps he can answer it or you might be able to ask on the ABP repo. The configuration requirement seems specific to ABP. Without it, things definitely work.

**Comment by hikalkan** [comment]
Thanks @commonsensesoftware 
@cyberbolt we can continue to discuss that on the [ABP repo](https://github.com/aspnetboilerplate/aspnetboilerplate) if you can open an issue.

**Comment by cyberbolt** [comment]
@commonsensesoftware  @hikalkan thank you for your help. I've created an issue https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3200
