### ISSUE TITLE
URL Versioning Not working - Using AspNetCore 2.0.2 targeting net471 (vs2017 15.7 Preview)

### ISSUE THREAD

**Issue by mradamclark** [Microsoft/aspnet-api-versioning#270]
So I found this issue, #211, regarding which framework you are tageting and at first I thought i figure out what i was doing wrong. I was targeting 4.6.1 with aspnetcore 2.0.2. 

I changed it so that it was targeting 4.7.1 and I still get no versioning occurring.

i have these nuget packages installed.

- Microsoft.AspNetCore (2.0.2)
- Microsoft.AspNetCore.Mvc (2.0.3)
- Microsoft.AspNetCore.Mvc.Versioning (2.1.0)
- Microsoft.AspNetCore.StaticFIles (2.0.2)
- NSwag.AspNetCore (11.16.1)

And here is the current state of my code. Seems very simple, not sure what i have missed, or if there is just an issue with the associated version of packages and vs2017 15.7 Preview 1.0

Startup.cs
```CSharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddApiVersioning();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, s =>
            {
                s.GeneratorSettings.DefaultPropertyNameHandling = PropertyNameHandling.CamelCase;
            });

            app.UseMvc();

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("why am i here");
            });
        }

```

ValueController.cs
```CSharp
namespace myApi.Controllers
{
    [ApiVersion("1")]
    [Route("api/v{version:apiVersion}/[controller]")]
    public class ValuesController : Controller
    {
        [HttpGet]
        [Route("{id:int}")]
        public string Get(int id)
        {
            return "value";
        }
    }
}
```

**Comment by commonsensesoftware** [comment]
What is the request URL you are expecting or is not working? The setup looks correct.

**Comment by mradamclark** [comment]
oops forgot to add that.

http://localhost:53391/api/v1/values

**Comment by commonsensesoftware** [comment]
If it makes you feel better, I zipped right past the route template myself. =/

You don't want to define a new route on the action. You only want to add the remaining part of the template. Try changing it to:

```c#
namespace myApi.Controllers
{
    [ApiVersion("1")]
    [Route("api/v{version:apiVersion}/[controller]")]
    public class ValuesController : Controller
    {
        [HttpGet("{id:int}")]
        public string Get(int id) => "value";
    }
}
```

**Comment by mradamclark** [comment]
wow, didn't see that one, I use [RoutePrefix()] in my web api project (pre aspnetcore) but it still doesn't work.

I also have this action defined, which wasn't included orginally, which i don't think it is really that different.
 
```CSharp
 [HttpGet]       
        public IActionResult Get()
        {
            return Ok(new[] { "value 1", "value 2" });
        }
```
All i ever get back is "why am i here" from the final app.Run handler in the startup class.

**Comment by commonsensesoftware** [comment]
`[RoutePrefix]` doesn't exist anymore. I would remove `app.Run` to get things working first. It's possible to integrate the middleware, but it's not as straight forward as I would like due to previous limitations in the MVC pipeline. I'm going to re-evaluate the internal mechanics in 3.0 to hopefully make integrating middleware more natural.

**Comment by mradamclark** [comment]
well that was pretty simple. it works now. Not sure why I didn't try to remove that before asking, i tried removing pretty much everything else. Thanks for the quick responses.

**Comment by commonsensesoftware** [comment]
I believe this issue is resolved. Feel free to reopen the issue or come back if you're still facing the issue. Thanks.
