### ISSUE TITLE
Using single swagger documentation for different Version of Web Controllers 

### ISSUE THREAD

**Issue by Boriszn** [Microsoft/aspnet-api-versioning#271]
Hi. 
Quite nice and useful solution.

Would it be possible to configurate versioning with swagger to use different API versions But withing one swagger documentation (Open Api specification) ?

**Comment by commonsensesoftware** [comment]
Can you elaborate a little on exactly what you mean?

This project doesn't specifically care about or have an specific dependency on Swagger nor any specific implementation libraries such as Swashbuckle or NSwag. What's provided is an **API Explorer** library that is API version-aware. The API Explorer collates all actions by API version for you. Exactly how that information is used is purely up to you or the consuming library.

The examples provided use Swashbuckle, but that's purely for illustration purposes. If the information isn't collated the way you want, I'd consider alternate arrangements.

**Comment by Boriszn** [comment]
Thank you a lot for the feedback.

Sure, will explain in details then:

1. We configured to use Versioning as header based, so it adds `version` parameter to all Api calls, like on on configuration below:
````C#
services.AddApiVersioning(o => {
	o.ReportApiVersions = true;
	o.AssumeDefaultVersionWhenUnspecified = true;
	o.DefaultApiVersion = new ApiVersion(1, 0);
 
	o.Conventions.Controller<HomeV1Controller>().HasApiVersion(new ApiVersion(1, 0));
	o.Conventions.Controller<HomeV2Controller>().HasApiVersion(new ApiVersion(2, 0));
});
````
As understood it will use `version` parameter to route to the proper method/controller, Right ? 
(For example: if passed version `1.0` it will lead to method which marked for version `1.0` etc..)

2. For the Swagger configuration below will generate swagger documentations (OpenApi specs) for all  versions, Right ?

````C#
app.UseSwaggerUI(
        options =>
        {
            foreach ( var description in provider.ApiVersionDescriptions )
            {
                options.SwaggerEndpoint(
                    $"/swagger/{description.GroupName}/swagger.json",
                    description.GroupName.ToUpperInvariant() );
            }
        } );
````

If Yes, then main question: **How to use this `version` parameter alongside with swagger withing one API endpoint (or Swag. API spec)?** 

Is it clear or should I add more details ?

Thanks,
Boris
P.S 
And yes It may be a question to Swagger also.

**Comment by commonsensesoftware** [comment]
After `AddApiVersioning` you need this:

```c#
services.AddSwaggerGen(
    options =>
    {
        // note: need a temporary service provider here because one has not been created yet
        var provider = services.BuildServiceProvider()
                               .GetRequiredService<IApiVersionDescriptionProvider>();

        // add a swagger document for each discovered API version
        foreach ( var description in provider.ApiVersionDescriptions )
        {
            options.SwaggerDoc( description.GroupName, CreateInfoForApiVersion( description ) );
        }
    } );
```

This will produce a Swagger document per API version. Each Swagger document will be accessible as:

* `/swagger/v1/swagger.json`
* `/swagger/v2/swagger.json`
* ...

To see all the pieces together, please review the [Startup.cs](../blob/master/samples/aspnetcore/SwaggerSample/Startup.cs) in the Swagger example. My understanding of the Swagger specification is that you cannot combine everything in a single document because the relative path for each URL must be unique. At least in Swashbuckle, the Swagger UI is setup for one document per API version. Diverging from that approach is certainly possible, but will likely require work on your side.

Also, if you're using the header method, then you need to configure that in the options. Only the query string or URL method work with the default configuration.

```c#
services.AddApiVerisoning(
    options =>
    {
        // specify the header[s] containing the api versions
        options.ApiVersionReader = new HeaderApiVersionReader( "api-version" );
     }
);
```

I hope that helps.

**Comment by commonsensesoftware** [comment]
Did this get you what you needed or are you still stuck?

**Comment by Boriszn** [comment]
@commonsensesoftware Thank you a lot for the feedback. Yeah, a bit stuck. Basically, my goal is combine somehow versioning with only one, single `SwaggerDoc`.  Exactly like in issue mentioned [Here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/244) 
So, for example methods with V1 and methods with V2 should be listed in one Swagger Documentation.

**Comment by commonsensesoftware** [comment]
Great! Feel free to come back if you remain stuck. Thanks.

**Comment by mehdiAbbaspour** [comment]
hi , 
i using asp mvc 5 and api in area difrrent project ,
 how to config mulitiapiVersion in swagger

**Comment by commonsensesoftware** [comment]
I don't _believe_ there's anything special you need to do if you're mixing UI and APIs together in the same project, even if you're using _Areas_. To enable Swagger you need the [API Explorer](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer) package and choose a supported Swagger generator such as Swashbuckle or NSwag. The [sample project](../tree/master/samples/aspnetcore/SwaggerSample
) shows an end-to-end configuration using Swashbuckle.

If you're trying to use _nested applications_ (which is not quite the same as _Areas_), you might want to peek at #391.

I hope that helps.

**Comment by gaoconggit** [comment]
Hi @Boriszn
Thank you very much. Could you please provide me with a code?

**Comment by bhagyashreeborate** [comment]
Hi @Boriszn or @gaoconggit 
Can you share you solution on how you managed to display all versions on same swagger document?

**Comment by bhagyashreeborate** [comment]
@Boriszn I am trying to show two different versions v1 and v2 on same swagger page - having same method name AddRequests().
Can it be possible for you to share your solution to do that?

**Comment by Dejavu333** [comment]
has anyone solved this?

**Comment by commonsensesoftware** [comment]
@Dejavu333 Yes. However, this is **only** achievable if you are versioning URL segment, which I don't recommend; it's not RESTful. OpenAPI does not support the concept of versioning directly. All endpoints **must** have a unique path. The only method of versioning that produces unique paths per version is by URL segment. While that might solve one problem, it will come with a litany of other problems, unless you don't care about REST and then you can do as you please.

Asking or elaborating on your use case in a new [discussion](../discussions) might bear more fruit. Merging all documents into a single one for the UI will likely be clunky for all but the smallest of APIs. I suspect your use case is different.
