### ISSUE TITLE
Support namespaces

### ISSUE THREAD

**Issue by jstachowiak** [Microsoft/aspnet-api-versioning#272]
Hello!

This is a great project, thanks!

Is supporting namespaces something that you would be willing to consider? As per [PayPal API design guidelines](https://github.com/paypal/api-standards/blob/master/api-style-guide.md):

> **Namespaces** should reflect the domain that logically groups a set of business capabilities. Domain definition should reflect the customer's perspective on how platform capabilities are organized. Note that these may not necessarily reflect the company's hierarchy, organization, or (existing) code structure. In some cases, domain definitions are aspirational, in the sense that these reflect the target, customer-oriented platform organization model. Underlying service implementations and organization structures may need to migrate to reflect these boundaries over time.

The URI would look like the following:
`[scheme"://"][host[':'port]]"/v" major-version '/'namespace '/'resource ('/'resource)* '?' query`

`ApiExplorerSettingsAttribute ` has a `GroupName` property which value could be included in the final API description. Any idea if this can be done without a significant amount of work?

**Comment by commonsensesoftware** [comment]
To be honest, a _namespace_ seems to be very specific to the PayPal API design guidelines. A URI has no formal concept of a namespace. A URI is usually used _as_ a namespace (ex: `urn:isbn:0345391802`).

It sounds like what you are asking for is an alternate way to collate API descriptions. Today, the API Explorer collates all descriptions by API version. This loosely has affinity to the rules used by Swagger. A Swagger document cannot have duplicate URLs, so a distinct document must be generated per API version.

That said, I want the Swagger integration to be seamless, but not coupled. Several people have _hinted_ at an ask to collate API descriptions different ways, but nothing has really manifested. This feels like a similar ask. I don't have a problem with entertaining different ways of collating API descriptions, but this is a pretty simple transformation you can do yourself.

Something like:

```c#
var keyComparer = StringComparer.OrdinalIgnoreCase;
var apiByNamespace = new Dictionary<string, List<ApiDescription>>( keyComparer );

string GetNamespace( string relativeUrl ) => relativeUrl.Split('/')[1];

// bucketize by namespace
foreach ( var description in provider.ApiVersionDescriptions )
{
    var @namespace = GetNamespace( description.RelativePath );

    if ( !apiByNamespace.TryGetValue( @namespace, out var descriptions ) )
    {
        apiByNamespace[@namespace] = descriptions = new List<ApiDescription>();
    }

    descriptions.Add( description );
}

// order results by namespace
foreach ( var pair in apiByNamespace.OrderBy( p => p.Key ) )
{
    // ... and then by api version
    foreach ( var description in pair.Value.OrderBy( d => d.GetApiVersion() ) )
    {
        // TODO: use description
    }
}
```

**Comment by jstachowiak** [comment]
Yes, I'm looking for an alternate way to collate API descriptions. I found a way how to produce distinct Swagger documents per API version and namespace. However, `ApiVersionDescription` does not seem to have a `RelativePath` property that I can use to bucketize by namespace or am I missing something?
 
https://github.com/Microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/ApiVersionDescription.cs

**Comment by commonsensesoftware** [comment]
Whoops - wrong provider in the example. You want the out-of-the-box [IApiDescriptionGroupCollectionProvider](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ApiExplorer/IApiDescriptionGroupCollectionProvider.cs).

The revised version should be:

```c#
// get from services (e.g. DI)
IApiDescriptionGroupCollectionProvider provider;

var keyComparer = StringComparer.OrdinalIgnoreCase;
var apiByNamespace = new Dictionary<string, List<ApiDescription>>( keyComparer );

string GetNamespace( string relativeUrl ) => relativeUrl.Split('/')[1];

// bucketize by namespace
foreach ( var group in provider.ApiDescriptionGroups.Items )
{
    foreach ( var description in group.Items )
    {
        var @namespace = GetNamespace( description.RelativePath );

        if ( !apiByNamespace.TryGetValue( @namespace, out var descriptions ) )
        {
            apiByNamespace[@namespace] = descriptions = new List<ApiDescription>();
        }

        descriptions.Add( description );
    }
}

// order results by namespace
foreach ( var pair in apiByNamespace.OrderBy( p => p.Key ) )
{
    // ... and then by api version
    foreach ( var description in pair.Value.OrderBy( d => d.GetApiVersion() ) )
    {
        // TODO: use description
    }
}
```

**Comment by jstachowiak** [comment]
Thanks, this works for now! It would be nice if `ApiVersionDescription` also encapsulated `RelativePath`. This would enable more customization in the future.
