### ISSUE TITLE
Is there a way to integrate Swagger without using SwashBuckle?

### ISSUE THREAD

**Issue by gauravagerwala** [Microsoft/aspnet-api-versioning#282]

**Comment by gauravagerwala** [comment]
Services.GetApiExplorer is returning the endpoint(ApiDescription.RelativePath) like this:
example/v{version}/call
How do I ensure that it returns the version I have specified

**Comment by commonsensesoftware** [comment]
API Versioning doesn't directly care about Swagger or Swashbuckle; it only provides an _API Explorer_. The API Explorer is paramount to Swashbuckle and NSwag to generate Swagger documents. To answer your question, then - yes - you can create Swagger documents without Swashbuckle using the API Explorer.

It also looks like you're asking how to substitute the API version in the _explored_ APIs. Remember that your route templates are defined as `example/v{version:apiVersion}/call`. This is no different than if the route template was `example/call/{id:int}`. Route templates are not normally _auto-magically_ populated. 

While it's always been possible to perform the substitution yourself, service authors using the URL segment version method often ask for this behavior. A new option was added to the API Explorer a while back to do this for you:

```c#
configuration.AddVersionedApiExplorer( options => options.SubstituteApiVersionInUrl = true );
```

This is documented in the [wiki](../wiki/API-Explorer-Options#substitute-api-version-in-url) and only applies to the URL segment method.

I hope that helps.

**Comment by gauravagerwala** [comment]
I am unable to access the new option on ApiExplorer using the nuget package,
What could be the reason for this?

**Comment by gauravagerwala** [comment]
It worked, Thanks
