### ISSUE TITLE
Versioning with MapSpaFallbackRoute

### ISSUE THREAD

**Issue by dannoh** [Microsoft/aspnet-api-versioning#284]
I assume this issue is more me than aspnet-api-versioning however I'm at a loss.  404s from my api return my Home/Index instead of continuing with the 404, or I can get it to return a 404 from my api call, but then all my SPA pages also return 404.  If I remove services.AddApiVersioning everything works as expected.

My ConfigureServices:
```
 services.AddApiVersioning(options =>
            {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true;
                options.DefaultApiVersion = new ApiVersion(1, 0);
            });
...
services.AddMvc();
```

My Configure:
```
app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

                //routes.MapSpaFallbackRoute(
                //    name: "spa-fallback",
                //    defaults: new { controller = "Home", action = "Index" });
            });

            app.Properties["analysis.NextMiddlewareName"] = "MapWhen starts without Api";
            app.MapWhen(x =>
            {
                var result = !x.Request.Path.Value.StartsWith("/api");
                return result;
            }, builder =>
            {
                builder.UseMvc(routes =>
                {
                    routes.MapSpaFallbackRoute(
                        name: "spa-fallback",
                        defaults: new { controller = "Home", action = "Index" });
                });
            });
```

**Comment by commonsensesoftware** [comment]
I believe this is just a simple setup issue. Things work the way I would expect with the following setup:

```c#
app.UseMvc();
app.MapWhen(
 c => !c.Request.Path.StartsWithSegments("/api"),
 a => a.UseMvc(r=>r.MapRoute(name:"default",template:"{controller=Home}/{action=Index}/{id?}")
                   .MapSpaFallbackRoute(name:"spa",defaults:new{controller="Home",action="Index"})));
```

Let me know if that works. I'm planning on trying make the middeware story better in 3.0.

**Comment by dannoh** [comment]
/ 404
/Home/Index 404
/SampleData/WeatherForecasts/ 200
/SampleData/MadeUp/ 404

So, still not working correctly.  This is using the default dotnet core react template.

```C#
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
		app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
		{
			HotModuleReplacement = true,
			ReactHotModuleReplacement = true
		});
	}
	else
	{
		app.UseExceptionHandler("/Home/Error");
	}

	app.UseStaticFiles();
	app.UseMvc();
	app.MapWhen(
		c => !c.Request.Path.StartsWithSegments("/api"),
		a => a.UseMvc(r => r.MapRoute(name: "default", template: "{controller=Home}/{action=Index}/{id?}")
			.MapSpaFallbackRoute(name: "spa", defaults: new { controller = "Home", action = "Index" })));
	//app.UseMvc(routes =>
	//{
	//    routes.MapRoute(
	//        name: "default",
	//        template: "{controller=Home}/{action=Index}/{id?}");


	//});
	//app.MapWhen(x => !x.Request.Path.Value.StartsWith("/api"), builder =>
	//{
	//    builder.UseMvc(routes =>
	//    {
	//        routes.MapSpaFallbackRoute(
	//            name: "spa-fallback",
	//            defaults: new { controller = "Home", action = "Index" });
	//    });
	//});
}
```

**Comment by commonsensesoftware** [comment]
Do you have a repro project you can share? Apparently what I've tried doesn't match your scenario somehow.

**Comment by dannoh** [comment]
Attached.  Pretty much just the default template with the package added.
[SpaVersioningIssue.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1920771/SpaVersioningIssue.zip)

**Comment by commonsensesoftware** [comment]
Great. Thanks. I'll take a look.

**Comment by dannoh** [comment]
Not in a huge rush, but just wanted to see if you had a chance to look at this issue.

**Comment by commonsensesoftware** [comment]
Still digging into this. The expected setup didn't do what I expected so I need to investigate deeper. Thanks for your patience.

**Comment by BranigansLaw** [comment]
I'm also having this issue and tried to configuration provided and it's still not working.

I'll keep an eye on this thread to see if things get fixed.

**Comment by DaanWasscher** [comment]
I also ran into this issue.

**Comment by dannoh** [comment]
Just want to bump this back up, and can we maybe remove the question tag for something more appropriate?

**Comment by commonsensesoftware** [comment]
Sorry it's taken so long. I've had to push out a couple of confirmed bugs and I've been up to my eyeballs with my day job.

Custom routing can be tricky. There a few limitations in the routing system that make it difficult for things to work as orthogonal as they should in all cases. There is _supposed_ some work being done by the ASP.NET team, but I don't know when that will happen. In the meantime, I am working to allow you more control (e.g. full) where API versioning gets in involved in the pipeline for the upcoming v3.0. With you fully in the driver's seat, you'll have full control for complex routing configurations.

For now however … 

It took me a few trial and error attempts with your example, but I've made the necessary changes that _should_ work. It was working for me anyway.

[ApiVersioningWithSpa.zip](https://github.com/Microsoft/aspnet-api-versioning/files/2103635/ApiVersioningWithSpa.zip)

### Results

| Request URL | Status Code |
| ----------- | ----------- |
| / | 200 |
| /Home | 200 |
| /Home/Index | 200 |
| /Home/Error | 200 |
| /api/v1/values | 200 |
| /api/v1/values/1 | 200 |
| /api/v2/values | 400 |
| /api/v2/values | 400 |
| /api | 200 (transfer to /Home/Index) |
| /api/v2 | 200 (transfer to /Home/Index) |

These are the results in both IIS Express and bare Kestrel

Let me know if this doesn't get you want you want.

**Comment by commonsensesoftware** [comment]
Did this solution work or is there still an issue?

**Comment by dannoh** [comment]
Haven't had a chance to circle back to this, but I'll check tonight.

**Comment by commonsensesoftware** [comment]
Glad you got things working. These discussions invariably help others who have similar setups. Come back if you have more questions. Thanks.
