### ISSUE TITLE
HTTP 405 status code

### ISSUE THREAD

**Issue by sajibcefalo** [Microsoft/aspnet-api-versioning#286]
Hello,
The api supports two versions. Version 2 is the latest version and Version 1 is the deprecated version. One of the end point which is POST method only supports api version 1. When I try to call the end point with api version other than 1 it returns HTTP 405 status code. But, according to my understanding it should return 400. As the documentation said
" If no implemented API versions match the HTTP request method, then status code 405 (Method Not Allowed) is returned; otherwise, status code 400 (Bad Request) is returned. "

Since there is already an implemented HTTP request POST method implemented but which is different version though, it should return 400.

Is this unexpected behavior or am i missing something?

**Comment by commonsensesoftware** [comment]
It appears this sufficiently answered you question. If not or you're still having trouble feel free to re-open or open a new issue. Thanks.
