### ISSUE TITLE
DefaultApiVersionReporter and websockets 

### ISSUE THREAD

**Issue by israellot** [Microsoft/aspnet-api-versioning#290]
DefaultApiVersionReporter tries to add headers to the response for websocket requests. 
This results in invalid operation since the headers were already sent along the HTTP 101 status.

**Comment by commonsensesoftware** [comment]
I'm assuming this is ASP.NET Core and the same symptoms as #273.

It appears the platform differences require Core to write the headers **before** the action is processed and Web API should write **after** the action is processed.

I should have the fix out within the next couple of days. Thanks.
