### ISSUE TITLE
"Opting-Out-of-Versioning" page has mislabeled sections (twice asp.net core)

### ISSUE THREAD

**Issue by mstaessen** [Microsoft/aspnet-api-versioning#294]
The documentation page https://github.com/Microsoft/aspnet-api-versioning/wiki/Opting-Out-of-Versioning section headers are twice "ASP.NET Core" while the first one should say "ASP.NET Web Api"

**Comment by commonsensesoftware** [comment]
The text has been updated, so I think this can be closed out. Thanks.
