### ISSUE TITLE
Version by namespace: what to include in each version?

### ISSUE THREAD

**Issue by nirzamir** [Microsoft/aspnet-api-versioning#303]
Hi,

I'm implementing versioning by convention (Web API) - I have a folder for each version with its controllers and models (as shown in the sample project with their mappers and resolvers). My question is whether other class types are relevant to version.

In other words, Is it best practice to include in each version also other classes like filters, validation attributes, utilities etc.? These classes can 'break' the existing API when they change.
My intuition tells me that those classes might change but not too often, and in those cases - instead of duplicating these classes per each version - I can just create a new class and delete the old implementation when the older API versions that use it are deleted.
p.s. see more details in the last comment (not replied yet) in [issue 276].(https://github.com/Microsoft/aspnet-api-versioning/issues/276)

Your thoughts are welcome.
Thank you!

**Comment by commonsensesoftware** [comment]
Ideally, you'll want constituent components such as these to be _version-neutral_. The rationale is less about versioning and more about how things map in ASP.NET. Most of these components can be mapped at the global/application, controller, action, and/or parameter level. The global or application level will not have the ability to deal with variations in API version unless you bake it in directly; for example, by querying `Request.GetRequestedApiVersion()`. If you need version-specific behaviors, you can implement them and apply them at the controller (or below) level as appropriate. In Web API, it is possible to mix global and some sublevel components like filters using overrides, but that can become messy to rationalize about.

A key decision point will be how much effort you want to put into a theoretical future issue. If the issue happens, your early planning is likely to pay off. If it doesn't, you may end up doing a bunch of unnecessary work. Probably the best trade-off is to _know_ how you'll branch behaviors or logic when you need to. Then make sure you have comprehensive test coverage for all of your services. That should largely protect you from regressions while making changes to existing service versions. The use of [Consumer-Driven Contracts](http://www.servicedesignpatterns.com/WebServiceEvolution/ConsumerDrivenContracts) is a way to help further verify you don't break existing clients. Ultimately, it's a case of _pay me now or pay me later_ and only you know for sure which approach is more economically viable for your scenarios.

If I had the choice, I would likely defer as much of this type of work as possible. Tests to validate and document my APIs are already a must. I would trust in their quality as a means to guard against regressions with future changes.

**Comment by commonsensesoftware** [comment]
Between here and #276, I think this has been adequately answered. Feel free to come back for more questions or re-open this issue if there's more to discuss. Thanks!
