### ISSUE TITLE
Feature request: MinApiVersionAttribute

### ISSUE THREAD

**Issue by mstaessen** [Microsoft/aspnet-api-versioning#304]
If I understand correctly, the way to evolve an API right now is as follows. 

We start at v1.0

    [ApiVersion("1.0")]
    public class Controller {
        IHttpActionResult SomeAPI() {}
    }

Adding an API (non-breaking, so minor version goes up)

    [ApiVersion("1.0")]
    [ApiVersion("1.1")]
    public class Controller {
        IHttpActionResult SomeAPI() {}
        
        [MapToApiVersion("1.1)]
        IHttpActionResult SomeOtherAPI() {}
    }

Repeat the last step with yet another new, non-breaking API

    [ApiVersion("1.0")]
    [ApiVersion("1.1")]
    [ApiVersion("1.2")]
    public class Controller {
        IHttpActionResult SomeAPI() {}
        
        [MapToApiVersion("1.1)]
        [MapToApiVersion("1.2)]
        IHttpActionResult SomeOtherAPI() {}

        [MapToApiVersion("1.2)]
        IHttpActionResult YetAnotherAPI() {}
    }

For all APIs that were not in v1.0, but are added after, the MapToApiVersionAttribute with the latest version number needs to be added. This becomes quite cumbersome after some time and it makes the code less readable. 

I would like to propose a MinApiVersionAttribute to filter the ApiVersions on the controller such that each method only requires one attribute to indicate whether it is included in a certain version or not. 

    [ApiVersion("1.0")]
    [ApiVersion("1.1")]
    [ApiVersion("1.2")]
    public class Controller {
        IHttpActionResult SomeAPI() {} //available in v1.0, v1.1 and v1.2
        
        [MinApiVersion("1.1)]
        IHttpActionResult SomeOtherAPI() {} // available in v1.1 and v1.2

        [MinToApiVersion("1.2)]
        IHttpActionResult YetAnotherAPI() {} // available only in v1.2
    }

What's your feedback?

**Comment by commonsensesoftware** [comment]
Reiterating some previous thoughts on the subject...

In my opinion, there is always a misnomer in services about what a _breaking change_ is. **Any** change in contract can and should be considered breaking. Many service authors assume that additive changes are non-breaking, but that simply is not the case. You cannot guarantee the client follows the [Tolerant Reader](http://www.servicedesignpatterns.com/WebServiceEvolution/TolerantReader) pattern. You usually also cannot make assumptions about what client technologies will be used. While it's true that many mature client technology stacks will support tolerant readers, it may not be true for all. This is one of the reasons why all API versioning must be explicit. A minor version technically doesn't imply anything officially, but based on your conventions or arguably commonsense, the changes are _small_. Small changes _can_ still be breaking.

Decorating controllers with a bunch of attributes only occurs when you interleave API versions on a single type. This _might_ make sense for small changes between API versions, but more significant changes should split into different types. You only need to decorate methods with `[MapToApiVersion]` when you are overriding an implementation or that implement is only present in particular API versions. Undecorated actions always implicitly map to the API versions declared by the controller.

While API versions do support comparison, they do not support incrementing or decrementing. Even if they did, there's no way to convey what the _step_ should be. The **ApiVersion** supports dates, major and minor, and status or any combination thereof. This makes the concept of a `[MinApiVersion]` infeasible. Furthermore, API versions need to be explicit. If your API versions are `1.0`, `1.1`, `1.2`, and `1.4`, how do you deal with omitting `1.3`? This is one of many holes where you can get into trouble.

With that said, not all hope is lost. Although API versions must be explicit, there is a way you can create _ranges_. This is not supported directly out-of-the-box, but it's easy for you to customize. Again, the variation in style and requirements make it infeasible to provide a generic solution for all. There are a few examples I've provided in the issues, but you can roll your own attribute for this either from scratch or by extending the **ApiVersionsBaseAttribute** and then implementing the **IApiVersionProvider** interface. Once implemented, your controller might then look like:

```c#
[ApiVersion("1.0")]
[ApiVersion("1.1")]
[ApiVersion("1.2")]
public class MyController : ApiController {
    IHttpActionResult SomeAPI() {}
    
    [MapToApiVersions(Major = 1, MinorStart = 1, MinorEnd = 2, Step = 1))]
    IHttpActionResult SomeOtherAPI() {}

    [MapToApiVersion("1.2)]
    IHttpActionResult YetAnotherAPI() {}
}
```

You can get just about as wild as you can imagine. The only requirement is that you produce a discrete set of API versions.


I hope that helps. If you can find the range examples or have more questions, feel free to ask.

**Comment by commonsensesoftware** [comment]
Seems like your question has been adequately answered. Thanks
