### ISSUE TITLE
Unversioned APIs

### ISSUE THREAD

**Issue by jayrulez** [Microsoft/aspnet-api-versioning#31]
When using this library, can we still have api endpoints that are not versioned and still accessible?

I am unable to reach an api endpoint for which I have not specified a version that does not have a version attribute.

I am using dotnet core.

**Comment by JayBazuzi** [comment]
Oooh, ooh, I know this one!

- If the endpoint is not part of your public API, i.e. it's for your use only, perhaps to check on service health, then you know will never need to version it, and you can mark it as `[ApiVersionNeutral]`.

- If you made your endpoint callable without a version number, and now you want to start versioning it, use:

```
        configuration.AddApiVersioning( o => o.AssumeDefaultVersionWhenUnspecified = true );
```

And mark your existing controller to accept the default version. Ask your clients to migrate to calling with a version number, and then remove this setting.

**Comment by jayrulez** [comment]
I see. This works. Thank you @JayBazuzi 

Fortunately there are no clients yet so I can get away with this scot-free.
