### ISSUE TITLE
Using Query Path versioning throws "A route named 'x' is already in the route collection. Route names must be unique." exception

### ISSUE THREAD

**Issue by sander1095** [Microsoft/aspnet-api-versioning#326]
Hello!

I am using ASP.NET Web API on .NET 4.5.2. 

My example API looks like this:

```
namespace App.Backend.Controllers.Version1
{
    [ApiVersion("1.0")]
    public class SomeController: ApiController
    {
        [HttpGet]
        [Route("api/entity/{id:int:min(1)}")]
        public async Task<IHttpActionResult> ApiAction(int id) //Already running in production
        {
            //Accessible by using ?api-version=1.0 OR by omitting that since this is the default version
            return Ok();
        }
    }
}
namespace App.Backend.Controllers.Version2
{
    [ApiVersion("2.0")]
    public class SomeController : ApiController
    {
        [HttpGet]
        [Route("api/entity/{id:int:min(1)}")]
        public async Task<IHttpActionResult> ApiAction(int id)
        {
            //Accessible by using ?api-version=2.0 OR by omitting that since this is the default version
            return Ok();
        }
    }
}
```

The config is as follows:

    // Add versioning
    config.AddApiVersioning(o => 
    {
        o.AssumeDefaultVersionWhenUnspecified = true;
        o.DefaultApiVersion = new ApiVersion(1, 0);
    });

When I send a request, though, the following happens:

`System.InvalidOperationException: A route named 'RegisterHours' is already in the route collection. Route names must be unique.`

**Duplicates:**
api/some/ApiAction
api/some/ApiAction

This is weird to me because in the wiki [there is an example](https://github.com/Microsoft/aspnet-api-versioning/wiki/Versioning-via-the-Query-String) exactly like my situation

I'd like to use the `?api-version={version}` option but it looks I have no choice to use the URL path version now (`api/v1.0/some/apiAction` and `api/v2.0/some/apiAction`.  If that's true, I guess I have to add another Route to every existing action which will be like `api/v{version:apiVersion}/controller/action` to allow them to use `v1.0` so it will be uniform in the entire application?

What do you guys advise? I could just use `/v2.0/` in the URL of version 2 of the API I guess, but I'd prefer the query string version.

**Comment by commonsensesoftware** [comment]
It would seem there's part of your configuration I'm not seeing. The message indicates you have multiple routes named **RegisterHours**. I don't see where the name is defined. Route names are not versioned or intrinsically supported. You would have to use names like **RegisterHoursV1** and **RegisterHoursV2**.

**Comment by sander1095** [comment]
🤦‍♂️  I believe you are right. 

The RegisterHours part is from my API, I forgot to censor that out.

But yeah, the one in my API looks like `[Route("route-stuff", Name = "RegisterHours")]` ... I will change that tomorrow and provide feedback then.

If this fixes my issue, thank you for fixing this dumb issue. I learn something everyday, I guess :)

**Comment by commonsensesoftware** [comment]
No problem. Glad you got it resolved. ;)
