### ISSUE TITLE
VersionedODataModelBuilder Error [Docs]

### ISSUE THREAD

**Issue by albertoVieiraNeto** [Microsoft/aspnet-api-versioning#327]
Hi, maybe i missed something but If anyone tries to follow the asp.net core + odata quickstart (https://github.com/Microsoft/aspnet-api-versioning/wiki/New-Services-Quick-Start#aspnet-core-with-odata-v40) it wont work, i feel that it should be mentioned somewhere that you should have a class that implements IModelConfiguration and that will be used to inject VersionedODataModelBuilder on the configureServices method.

**Comment by commonsensesoftware** [comment]
I haven't had enough time to get all the wiki stuff out, but it's coming. Following the sample apps are the best place to start with all the parts. The mechanics are the same as Web API, but some things are streamlined since DI is intrinsically built in.

**Comment by commonsensesoftware** [comment]
This wiki has been updated. The OData documentation now calls out, in a few places, that _Dependency Injection_ is wired up automatically and can be used for **IModelConfiguration** and **VersionedODataModelBuilder** in ASP.NET Core. This is **not** a requirement for use, but it's kind of hard to imagine a scenario where you wouldn't want DI to handle this for you. The examples continue to show setups with and without DI. Thanks.
