### ISSUE TITLE
using mvc areas keeps giving 404

### ISSUE THREAD

**Issue by Mhirji** [Microsoft/aspnet-api-versioning#329]
Hi, 

I have a project configured to use MVC areas.  When I include [area] in MapVersionedODataRoutes, I keep getting a 404.  I then tried to add it directly to ODataRoutePrefix, but that gave me a 404 also.  I even tried to hardcode it into ODataRoutePrefix and still came up with a 404.

I think this is coming from the MapVersionedODataRoutes requiring a class implementing IModelConfiguration, but am not sure.  If anyone has gotten this to work, I would appreciate the help.

Thanks!!

**Comment by Mhirji** [comment]
Just a follow-up, I ended up using multiple routes with the area hard coded in, then specified the RouteName on the ODataRoute.  It seems to be ok, but not sure if this was the best way to go about it.

**Comment by Mhirji** [comment]
Sorry, reopening this.  My "solution" caused other issues.   To give a little more context, in my startp.cs I have:

var models = modelBuilder.GetEdmModels();
      routes.MapVersionedODataRoutes("odata", "v{version:apiVersion}/odata/[area]", models);


The ODataRoutePrefix on the ODataController class is:
[ODataRoutePrefix("Components")]

And the action is decorated with:
[ODataRoute]
-----------------------------------------------------------------------------------------------------------------
Adding the area to the ODataRoutePrefix to make it [ODataRoutePrefix("[area]/Components")] does not work.

Changing MapVersionODataRoutes to pass a null to the routeprefix and add the entire template into the ODataRoutePrefix on the odatacontroller does not work.

Changing ODataRoutePrefix to [ODataRoutePrefix("[area]")]  and the action to [ODataRoute("Components")] does not work either.

Again, any help getting this working would be greatly appreciated. 

Thanks!!

**Comment by commonsensesoftware** [comment]
Does this even work without API versioning? I'm not sure that it does. I don't recall seeing anything in the OData source code that would support it. Furthermore, _areas_ are a UI concept, so I wouldn't expect there to be any first-class support for areas in the context of authoring APIs.

If you can provide a repro that demonstrates that areas work with OData before API versioning is applied, I'll look into this further.

**Comment by Mhirji** [comment]
Thanks again for the time @commonsensesoftware . . . I totally agree with your comment regarding Areas, but its an older project which had view controllers and api controller together in areas.  After a night of refactoring things working again.   Just a quick question,
In the samples project you have here https://github.com/Microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerSample you have shown using attribute routing to include the version.  Have you tried this same strategy with the ODataRoutePrefix/ODataRoute?

 Thank you for all your work, and time given to responding to these threads.

**Comment by commonsensesoftware** [comment]
Glad you got things working. Things are still beta for OData so I won't be surprised if there aren't some edge cases where things may not work as expected.

OData does it's own thing when it comes to routing. It's unfortunate, but that's the way it is. Honestly, they should have rethought their approach for Core, but ended up just trying to make the same old model work.

You can definitely use URL segment style just like you could in Web API if you really want to. There is an example in the [OData Basic Sample](../blob/master/samples/aspnetcore/ODataBasicSample/Startup.cs#L43
). Unlike Web API, there is no additional setup on your side. The route constraint is automatically wire up for you to use.

I hope that helps.

**Comment by Mhirji** [comment]
I know what you mean with their routing strategy, I struggled with it for awhile, but to some extent I see why they did it.  Anyways, such is life.  I think there is an issue with MapVersionedODataRoutes, just have not had the time to verify and dig into it.  If/when I do, will let you know and get out a PR.  Thanks again for e erything.
