### ISSUE TITLE
Use together with SignalR

### ISSUE THREAD

**Issue by Zaixer** [Microsoft/aspnet-api-versioning#333]
Are there any known issues using this together with SignalR long polling? It didn't seem to work but might have been other problems. Will test some more.

**Comment by commonsensesoftware** [comment]
You should able to use SignalR without issue if you want to. If you're trying apply API versioning to SignalR, that's likely not going to work. SignalR is working at the websocket layer and is outside the purview of API versioning once the connection is established. If you want versioning at the websocket level, then you'll likely need your own mechanisms for that.

**Comment by commonsensesoftware** [comment]
Were you able to resolve this, provide additional context, or at least a repro?

**Comment by Zaixer** [comment]
I used config something like this in Core and got it working.

```
services.AddSignalR();

services.AddApiVersioning(options => {
  options.AssumeDefaultVersionWhenUnspecified = true;
});

app.UseSignalR(routes => {
  Action<HttpConnectionDispatcherOptions> setOptions = options => {
    options.Transports = HttpTransportType.LongPolling;
    options.LongPolling.PollTimeout = TimeSpan.FromSeconds(30);
  };
  routes.MapHub<NotificationCreatedHub>("/hubs/notificationcreated", setOptions);
  routes.MapHub<AggregateChangedHub>("/hubs/aggregatechanged", setOptions);
});
```

**Comment by commonsensesoftware** [comment]
Great! Thanks for confirming. Cheers!
