### ISSUE TITLE
Asp.Net Core ApiExplorer sample outdated

### ISSUE THREAD

**Issue by cgbeutler** [Microsoft/aspnet-api-versioning#343]
Looking at the file `aspnet-api-versioning/samples/aspnetcore/SwaggerSample/Startup.cs` it shows that you set up the VersionedApiExplorer using the code `services.AddVersionedApiExplorer( options => ...` but that appears to be inaccurate. The wiki shows that you need to build it off the MvcCoreBuilder like so: `services.AddMvcCore().AddVersionedApiExplorer( options => { /* configure options */ } );`. In trying to set stuff up myself, I was unable to get it to work on anything but the MvcCoreBuilder. If the extension method was removed for services and was never present on the MvcBuilder, it would be good to have the sample reflect that.

**Comment by commonsensesoftware** [comment]
I'll chaulk this up a _documentation bug_ and track it. The wiki is overdue for some updates and a few things are definitely out-of-sync. The examples are snapped to the latest build in _master_ which is v3.0-beta. In the updates, the explicit need to `AddMvcCore()` is no longer required and implicitly done for you. This fixes a different issue where devs didn't call it and the call to `AddApiExplorer()` was missed, but is required.

Thanks for pointing it out. I'll be sure to update this. I'll also put a note about the difference in previous versions.

**Comment by commonsensesoftware** [comment]
The wiki has been updated to reflect the 3.0+ documentation. A note has also been left in place for the difference in earlier versions. Feel free to report any other discrepancies. Thanks.
