### ISSUE TITLE
Wiki - remove/update comment about UseApiVersioning()

### ISSUE THREAD

**Issue by collinbarrett** [Microsoft/aspnet-api-versioning#345]
In the sample code for ASP.NET Core [here](https://github.com/Microsoft/aspnet-api-versioning/wiki/Versioning-via-the-URL-Path#aspnet-core), there is the following line:

`services.UseApiVersioning(); // required in 1.1+`

If I understand the [1.2.0 release notes](https://github.com/Microsoft/aspnet-api-versioning/releases/tag/v1.2.0) correctly, this comment should be updated to say something like `required in >= 1.1.0 and <= 1.2.0` similar to how it is annotated [here](https://github.com/Microsoft/aspnet-api-versioning/wiki/Known-Limitations#aspnet-core-routing).

**Comment by commonsensesoftware** [comment]
Good catch. Surprised no one has mentioned that before. I've actually completely removed that in the example as it's highly unlikely to be used.

In 3.0+ `services.UseApiVersioning()` makes a comeback, but only optionally in advanced scenarios. The **only** case you should ever need to use it is if you need full control over how and when the API versioning middleware gets registered.

In case you're curious, it would have to look like this in 3.0+ (again - for advanced setups only):

```c#
public void ConfigureServices( IServiceCollection services )
{
   services.AddApiVersioning(options => options.RegisterMiddleware = false);
}

public void Configure( IAppBuilder app )
{
   app.UseApiVersioning();
}
```

Thanks for bring this to my attention. Feel free to report any additional discrepancies. Thanks.
