### ISSUE TITLE
RouteCreationException

### ISSUE THREAD

**Issue by fjukstad** [Microsoft/aspnet-api-versioning#348]
Hi! 

If for some reason one of the controller methods in an existing project use `{version}` as an `HTTPGetAttribute`, e.g.

 ```c#
[HttpGet("{version}")]
public ActionResult<string> ExistingAction([FromRoute] int version){
    return version.ToString();
}
```

adding API versioning will throw a `RouteCreationException`. 

```
Microsoft.AspNetCore.Routing.RouteCreationException: The following errors occurred with attribute routing information:

For action: 'api_version_test.Controllers.FooController.ExistingAction (api-version-test)'
Error: The route parameter name 'version' appears more than one time in the route template.
Parameter name: routeTemplate
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetRouteInfos(IReadOnlyList`1 actions)
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.AddEntries(TreeRouteBuilder builder, ActionDescriptorCollection actions)
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Is it possible to use URL path versioning while still using `{version}` in HTTPAttributes in an existing project? Full example [here](https://github.com/fjukstad/aspnet-api-versioning-test).

Cheers!

**Comment by commonsensesoftware** [comment]
No, but you're in full control of the route parameter names. The route parameter name `version` in the **RouteAttribute** is inconsequential. The examples I provide use the name **version**, but it can be anything you want. You can just as easily use a different name to remove the ambiguity:

```c#
[Route("v{api-version:apiVersion}/foo")]
[ApiVersion("1.0")]
[ApiController]
public class FooController : ControllerBase
{
    [HttpGet("{version}")]
    public ActionResult<string> ExistingAction([FromRoute] int version) => version.ToString();
}
```

Starting in 3.0+, you can now also use an alternate name for the route constraint (instead of **apiVersion**) if you really want to via:

```c#
services.AddApiVersioning(options => options.RouteConstraintName = "api-version");
```

**Comment by fjukstad** [comment]
Perfect! Thanks!

**Comment by commonsensesoftware** [comment]
It looks like you were able to work through this issue. If you run into any more issues, feel free to come back or reopen the issue. Thanks.
