### ISSUE TITLE
Sample for versioning in ASP.NET Core with Swagger does not work with .NET Core 2.1

### ISSUE THREAD

**Issue by victormarante** [Microsoft/aspnet-api-versioning#349]
Hi. The sample shown in your samples folder where you incorporate Swagger with API versioning by namespace convention, does not work as of 2.1. If I only have 1 version (as shown in the image), I get a 404 no matter what route I try to access the resource at.

Secondly, the service AddVersionedApiExplorer does not exist (or is somehow changed), in the latest version of .NET Core.

`
services.AddVersionedApiExplorer(
                options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                } );
`

Is there some way to handle this? The provider is needed for me to loop over all versions and create swagger docs for each one. Has this interface been moved so I can access it somewhere else?

![image](https://user-images.githubusercontent.com/41802977/45947619-3dd40d00-bff5-11e8-8c68-d1d523f80155.png)

EDIT:

Rewrote the issue since I noticed I made no sense in the original iteration.

**Comment by commonsensesoftware** [comment]
Have you added the [API Explorer](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer) package reference? I can't tell from the information provided thus far. The `AddVersionedApiExplorer` extension method is in that package.

I'm not aware of any compatibility issues with 2.1, but that doesn't mean their aren't any. I would be surprised though. Do you have a repro that you can share? That will accelerate the troubleshooting process. Thanks.

**Comment by victormarante** [comment]
Hi, I might not have done that, was not aware you had too. I might have missed that step. I will try to do so, and get back to you.

Another question, I noticed the VersionByNamespaceConvetion is only supported in the 3.0.0-beta version. Is the sample still valid for 2.1? The Swagger sample one, without OData?

**Comment by victormarante** [comment]
Hi, so after installing the API Explorer nuget package, I had access to the AddVersionedApiExplorer extension. But I still ran into issues with using the extension (services.AddVersionedApiExplorer did not show up on intellisense). Luckily I stumbled upon another issue (https://github.com/Microsoft/aspnet-api-versioning/issues/330) where you explain that you need to access it through AddMvcCore(). I will close the issue myself.
