### ISSUE TITLE
MapVersionedODataRoute or MapVersionedODataRoutes always throws an exception

### ISSUE THREAD

**Issue by silkroadscott** [Microsoft/aspnet-api-versioning#35]
I've been trying to add versioning to our OData API for the last couple of days but despite working off the samples here I find that my call to MapVersionedODataRoute or MapVersionedODataRoutes (depending on which sample I based my code on) inevitably results in the following exception:

``` csharp
System.MissingMethodException was unhandled by user code
  HResult=-2146233069
  Message=Method not found: 'Void System.Web.OData.Routing.ODataPathRouteConstraint..ctor(System.Web.OData.Routing.IODataPathHandler, Microsoft.OData.Edm.IEdmModel, System.String, System.Collections.Generic.IEnumerable'1<System.Web.OData.Routing.Conventions.IODataRoutingConvention>)'.
  Source=Microsoft.AspNet.OData.Versioning
```

It's been difficult to troubleshoot as I can't tell what method it can't find. In case it matters, the stack trace is basically identical in each case, aside from the name of the method that I invoked in my code.

``` csharp
StackTrace:
       at System.Web.Http.HttpConfigurationExtensions.MapVersionedODataRoutes(HttpConfiguration configuration, String routeName, String routePrefix, IEnumerable'1 models, IODataPathHandler pathHandler, IEnumerable'1 routingConventions, ODataBatchHandler batchHandler)
       at System.Web.Http.HttpConfigurationExtensions.MapVersionedODataRoutes(HttpConfiguration configuration, String routeName, String routePrefix, IEnumerable'1 models, ODataBatchHandler batchHandler)
       at VersionedAPI.Startup.Configuration(IAppBuilder appBuilder)
```

or

``` csharp
StackTrace:
       at System.Web.Http.HttpConfigurationExtensions.MapVersionedODataRoute(HttpConfiguration configuration, String routeName, String routePrefix, IEdmModel model, ApiVersion apiVersion, IODataPathHandler pathHandler, IEnumerable'1 routingConventions, ODataBatchHandler batchHandler)
       at System.Web.Http.HttpConfigurationExtensions.MapVersionedODataRoute(HttpConfiguration configuration, String routeName, String routePrefix, IEdmModel model, ApiVersion apiVersion)
       at VersionedAPI.Startup.Configuration(IAppBuilder appBuilder)
```

Do I possibly need to include another package? Is there a bug in the current release?

**Comment by commonsensesoftware** [comment]
Which version of the OData package are you using? I'm guessing you are upgrading a project or creating a new project which is using 6.0.0.  There were some pretty significant changes to API and runtime behaviors in 6.0 (see [OData 6.x Features](http://odata.github.io/WebApi/#13-01-modelbound-attribute) for more details).  There were a few places where I had to beat the OData APIs into submission, which required nasty, but unavoidable Reflection use. I suspect you are either encountering an incompatible binding redirect from the changes in the APIs or some internal piece of Reflection code is now broken.

Assuming this is your case, then my suggestion would be to use a previous release of the OData package - for now. All of the examples in this project are written against 5.9.1, but I suspect things will work all the way back to at least 5.6 (untested).  That should unblock you.

If you can indeed confirm you are using 6.0, then I'll also file a bug that the library is incompatible with 6.0.  I haven't dug deep into the changes for 6.0 yet, so I'm not sure how much work it will be; presumably minor. Until I've had some time to look into it, I can't say whether the fix will take a few days or a few weeks.  Regardless, I'll start taking a look and get a fix out as soon as possible.

Thanks for reporting the issue. Apologies for the inconvenience.

**Comment by silkroadscott** [comment]
Thanks, I appreciate the quick response. I can confirm that I've been using version 6.0.0 of the package. I was planning to try starting fresh with an earlier version of the package to see if that made a difference, but I got hung up in meetings and hadn't had the time to try it yet. Thanks for your help.

**Comment by commonsensesoftware** [comment]
Changing this to an enhancement rather than a bug, since the latest, published API versioning package for OData now indicates that it's not compatible with the OData 6.0.0+ package.
