### ISSUE TITLE
Support for APIs with no version specified.

### ISSUE THREAD

**Issue by nmathurbkn** [Microsoft/aspnet-api-versioning#350]
Hello All,

This is a question. 

I am implementing API versioning to an old API project. Some major APIs are live and people are accessing them from old versions of the application, so I cannot apply versioning to them (I can create a copy to implement versioning but cannot tough the old APIs). Is it possible that I can implement all new  APIs using version patter and simultaneously old APIs will work.

API with no version
`http://api.example.com/api/countries`

API with version
`http://api.example.com/api/v1.0.0/industries`

Please guide and share suggestions.

**Comment by commonsensesoftware** [comment]
It seems that you may have found the answer you were looking for. The URL versioning method **cannot** have unspecified segments, but you can have a route that without an API version that maps the default version (which you always had, but didn't name).

I'm not sure if your using Web API or ASP.NET Core, but it should look something like:

```c#
services.AddApiVersioning( options => options.AssumeDefaultVersionWhenUnspecified = true );
// ...

[ApiVersion( "1.0" )]
[Route( "api/[controller]" )]
[Route( "api/v{version:apiVersion}/[controller]" )]
public class CountriesController : ControllerBase
{
    [HttpGet]
    public IActionResult Get() => Ok();
}
```

This will match the following routes:
* `http://api.example.com/api/countries`
* `http://api.example.com/api/v1/countries`
* `http://api.example.com/api/v1.0/countries`

I hope that helps. Feel free to come back or reopen the issue if you still have questions.
