### ISSUE TITLE
How to Version only odata APIs without impacting standard Apis

### ISSUE THREAD

**Issue by fazil1987** [Microsoft/aspnet-api-versioning#368]
Hi all, 

This is just a question. 

We have existing web api's that are versioned by Namespaces using NamespaceHttpControllerSelector class ( Implementation of IHttpControllerSelector ) and new odata api. We want to version the newly created odata api by Namespaces too. 

I thought of using this library but this affects standard apis because of ApiVersionControllerSelector that doesn't know our way of resolving controller as stated above. 

So, How can I use this library only for odata api versioning without affecting the existing standard api's versioning ( which is done using NamespaceHttpControllerSelector ) ? Please suggest.

One option I could think of is having one implementation of IHttpControllerSelector, which decides whether to use ApiVersionControllerSelector or NamespaceHttpControllerSelector based on whether the request is for odata or standard api. But I feel this increases complexity. 

Do you have any better idea pls suggest ?

**Comment by commonsensesoftware** [comment]
Unfortunately, I think your assertion is correct. Web API only affords for a single implementation of **IHttpControllerSelector** for the entire application. You'd have to use a something like another instance that can compose the different implementations.

I'm not sure you've seen the new [Version By Namespace Convention](../wiki/API-Version-Conventions#version-by-namespace-convention), but this is something new in 3.0 that might make it easier for you to port your existing services over. Should that not fit your needs, it's now possible to author your own [custom conventions](../wiki/API-Version-Conventions#custom-conventions) in 3.0 as well.

There are a number of other possibilities in the earlier versions to enable a similar behavior too. The risk in migrating will be all about how sound your test suite is. If you have good test coverage, it should be _relative_ to port things over.

Another option would be to host the OData part in a separate web application and use the `host` header to give thing the appearance of being a single application to the outside world. This would allow the existing bits to stay _as is_ and only introduce the API versioning library stuff to the new OData APIs.

I hope that gives  you a few ideas.

**Comment by commonsensesoftware** [comment]
First, you implement the [IControllerConvention](../blob/master/src/Microsoft.AspNet.WebApi.Versioning/Versioning/Conventions/IControllerConvention.cs) interface. You can see an example of how to implement it by looking at [VersionByNamespaceConvention.cs](../blob/master/src/Microsoft.AspNet.WebApi.Versioning/Versioning/Conventions/VersionByNamespaceConvention.cs) (the remaining part is [here](blob/master/src/Common/Versioning/Conventions/VersionByNamespaceConvention.cs)). To put everything together, you just add your convention in the setup. You can see an [example](../blob/master/samples/webapi/ByNamespaceWebApiSample/Startup.cs) in the _Version By Namespace Convention_ project, but it will look like:

```c#
configuration.AddApiVersioning( options => options.Conventions.Add( new MyCustomConvention() ) );
```

That's all there is to it! I'm happy to answer any other questions you might have about how to get things working.

**Comment by fazil1987** [comment]
👍 @commonsensesoftware, I will try it out. Thanks

**Comment by commonsensesoftware** [comment]
Great. I fixed the link. Come back if you have more questions.
