### ISSUE TITLE
Trying to remove api-version query string from url

### ISSUE THREAD

**Issue by dhananjaysakhare244** [Microsoft/aspnet-api-versioning#372]
Hi,

I am using Swagger for documentation and API Versioning to version my APIs.
I wanted to use both OData and API Versioning together in the project.
The issue is whenever I try to call any API through Swagger or Postman I have to specifically insert api-version in query parameter.
I tried to implement Versioning via the URL path but I was unable to remove api-version query parameter.

Is there any way that I can configure both OData and ASP.NET Web APIs together and remove the api-version query parameter?

**Comment by figuerres** [comment]
@dhananjaysakhare244  sounds like something is not configured right.
in my case i have not yet put a version on my url but i did make the version not a part of the query string
i used the attribute [ApiVersionNeutral] and that solved my problem.
but if you use [ApiVersion( "1.0" )]
it was my understanding that would also take it off the query string.
is that what you have done ?

**Comment by commonsensesoftware** [comment]
Sounds like you **only** want the URL segment to be available as a way to version. The default configuration actually supports the query string and URL segment methods. The query string is the _encouraged_ behavior and adding the URL segment behavior typically doesn't add any visible side effects. The inverse, however, is not true; at least not as it relates to Swagger.

To use the URL method and only that method, change your configuration as follows:

```c#
configuration.AddApiVersioning( options =>
 {
    options.ApiVersionReader = new UrlSegmentApiVersionReader();
 } );
```

@figuerres has a point as well. Your comment _suggests_ you are trying to make a request without specifying an API version. If that is the case, you'll need to mark your controller as `[ApiVersionNeutral]`, which will allow it to response to any API version, including not at all. Keep mind that may not work the way you want or expect. There is **no** way to provide a default value for a URL segment. If you want version-neutral behavior, your routes will have to reflect that. This may mean multiple route mappings in some cases. For example:

```c#
[ApiVersionNeutral]
public class ValuesController : ApiController
{
  // GET values
  // GET v1/values
  [Route("values")]
  [Route("v{version:apiVersion}/values")]
  public IHttpActionResult Get() => Ok();
}
```

I hope that helps.

**Comment by commonsensesoftware** [comment]
There isn't a flavor of OData since at least the 5.x release that I'm aware of that being an issue. You can see the query string usage in [this](../blob/master/test/Microsoft.AspNet.WebApi.Acceptance.Tests/OData/Basic/given%20a%20versioned%20ODataController/when%20using%20a%20query%20string.cs
) acceptance test. Starting in 7.0+, OData has even relaxed the use of the `$` to disambiguate _system_ or built-in query parameters. The **ODataQueryOptions** doesn't attempt to parse query parameters that it doesn't understand.

Should you encounter such a scenario, I'm happy to help sort it out.

**Comment by commonsensesoftware** [comment]
sure. no problem. I recommend taking a look at the OData + Swagger example as place to start integrating the two.

**Comment by dhananjaysakhare244** [comment]
Thank you guys for your input.
But it seems that the approaches you shared are not working in my case.
I added this code and my swagger UI stopped showing APIs. It gave me APIVersionUnspecified error
```
configuration.AddApiVersioning( options =>
 {
    options.ApiVersionReader = new UrlSegmentApiVersionReader();
 } );
```
![capture](https://user-images.githubusercontent.com/22951770/47336247-8b9f6c00-d6ac-11e8-9678-ab437d70315e.PNG)


I will add configuration code for swagger and WebApi for your reference.

WebApiConfig.cs

```
config.MapHttpAttributeRoutes();

            config.Services.Add(typeof(IExceptionLogger), new NLogApiExceptionLogger());
            config.Services.Replace(typeof(IExceptionHandler),new ApiExceptionHandler());

            // reporting api versions will return the headers "api-supported-versions" and "api-deprecated-versions"
            config.AddApiVersioning(o => o.ReportApiVersions = true);
            config.AddApiVersioning(o => o.AssumeDefaultVersionWhenUnspecified = true);
            config.AddApiVersioning(o => o.ApiVersionReader = new UrlSegmentApiVersionReader());
            //config.MapVersionedODataRoutes("odata-bypath", "integration_services/api/v{apiVersion}", MyProjectContextODataEdmBuilder.CreateInstance(config), ConfigureODataServices);
            config.MapODataServiceRoute("odata", "integration_services/api/v1", builder => AddServicesToODataContainerBuilder(config, builder));
            config.MapODataServiceRoute("odatav2", "integration_services/api/v2", builder => AddServicesToODataContainerBuilderV2(config, builder));

            //Odata Query option is enabled.(by default it is disabled)
            config.Count().Filter().OrderBy().Expand().Select().MaxTop(PageSize);

            config.EnableDependencyInjection();
            config.EnsureInitialized();

            FluentValidationModelValidatorProvider.Configure(config);

            SwaggerConfig.Register(config);
```

SwaggerConfig.cs

```
internal class SwaggerConfig
  {
    // navigate to swagger/docs/v1 to download the swagger specification
    private const string SwaggerDocsRoute = "swagger/docs/{apiVersion}";

    // note that the URL to access this is help/integrationservices/rest/index
    private const string SwaggerUiRoute = "help/integrationservices/rest/{*assetPath}";

    public static void Register(HttpConfiguration configuration)
    {
      if (!IsRestApiDocsEnabled())
        return;
      // add the versioned IApiExplorer and capture the strongly-typed implementation (e.g. ODataApiExplorer vs IApiExplorer)
      // note: the specified format code will format the version as "'v'major[.minor][-status]"
      var apiExplorer = configuration.AddODataApiExplorer(
        options =>
        {
          options.GroupNameFormat = string.Format(CultureInfo.InvariantCulture, "'v'VVV");

          // note: this option is only necessary when versioning by url segment. the SubstitutionFormat
          // can also be used to control the format of the API version in route templates
          options.SubstituteApiVersionInUrl = true;
        });


      configuration.EnableSwagger(SwaggerDocsRoute, swagger =>
      {
        swagger.MultipleApiVersions(
          (apiDesc, version) =>
          {
            var controllerName = apiDesc.ActionDescriptor.ControllerDescriptor.ControllerType.FullName;
            var isRestIntegrationServices =
              (controllerName != null && controllerName.Contains(nameof(RestIntegrationServices)));

              if (isRestIntegrationServices)
              {
                  if (apiDesc.RelativePath.Contains("integration_services/api/" + version + "?"))
                      return false;

                  var path = apiDesc.RelativePath.Split('/');
                  //if(path.Length>1)
                  var pathVersion = path[2];

                  return CultureInfo.InvariantCulture.CompareInfo.IndexOf(pathVersion, version, CompareOptions.IgnoreCase) >=
                         0;
              }
              else
              {
                  return CultureInfo.InvariantCulture.CompareInfo.Compare("IntegrationApi", version) == 0;
              }                 
          },
          info =>
          {
            info.Version("v1", string.Format(CultureInfo.CurrentCulture, "My Project REST Integration Services V1"));
            info.Version("v2", string.Format(CultureInfo.CurrentCulture, "My Project REST Integration Services V2"));
            info.Version("IntegrationApi", string.Format(CultureInfo.CurrentCulture, "My Project Test Integration API Services"));

              foreach (var group in apiExplorer.ApiDescriptions)
            {
              info.Version(group.Name, string.Format(CultureInfo.CurrentCulture, "My Project REST Integration Services {0}",group.ApiVersion));
            }

          });
        swagger.PrettyPrint();
        swagger.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
        swagger.IncludeXmlComments(GetXmlCommentsPath("A.B.My Project.Web.XML"));
        swagger.IncludeXmlComments(GetXmlCommentsPath("A.B..My Project.RestIntegrationServices.Contracts.XML"));

        swagger.OperationFilter<AuthOperationFilter>();
        swagger.OperationFilter(() => new AddHeaderParameter());
        swagger.DocumentFilter<ShowInDocumentFilter>();

          // Swashbuckle's default handling of Guids is unclear - override
          // it to show GUID examples instead of string examples. Unfortunately
          // we still have to document GUID fields carefully, since GUID isn't
          // a type in the swagger specification.
          swagger.MapType<Guid>(() => new Schema
        {
          type = "string",
          format = "uuid",
          example = Guid.Empty
        });

        // todo: This custom provider makes loading/refreshing the swagger docs very slow.
        //Commenting out this custom provider speeds it up, but we lose odata docs.
        //Include Navigation Properties in your entity swagger models
        swagger.CustomProvider(defaultProvider =>
          new ODataSwaggerProvider(defaultProvider, swagger, configuration).Configure(odataConfig =>
          {
            odataConfig.IncludeNavigationProperties();
          }));

        swagger.UseFullTypeNameInSchemaIds();
      }).EnableSwaggerUi(SwaggerUiRoute, swagger =>
        {
          swagger.EnableDiscoveryUrlSelector();
        })
    ;
  }

    private static string GetXmlCommentsPath(string xmlFilename)
    {
      return Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "CodeDocs", xmlFilename);
    }

    private static bool IsRestApiDocsEnabled()
    {
      bool result;
      if (!bool.TryParse(ConfigurationManager.AppSettings["IsRestApiDocsEnabled"], out result))
        result = false;
      return result;
    }
  }
```


Please let me know if there is anything wrong that I have done 

Thanks in advance

**Comment by commonsensesoftware** [comment]
The two issues I see:

1. If you call `AddApiVersioning` multiple times, you reconfigure it each time. Only the third call is taking effect, which is surely not your intention.
2. You **must** call `MapVersionedODataRoute` or `MapVersionedODataRoute`; `MapODataServiceRoute` will not set things up properly. For the URL segment method, you must also specify the route constraint in the route prefix; otherwise, API versioning doesn't know how to extract the API version from the route template. There is **no** _magical_ regex or other pattern matching happening.

> Prior to 3.0, the route constraint was restricted to `{apiVersion}`. In 3.0+, that is still the default name, but you can now alter it to something else if you wish. For example, `options => options.RouteConstraintName = "api-version"`

I hope that helps.

**Comment by commonsensesoftware** [comment]
Ultimately, your configuration was wrong. Did you update and get things working?

**Comment by commonsensesoftware** [comment]
It seems you've solved your issue from this guidance or an alternate solution. If that turns out not to be the case, feel free to come back and/or reopen the issue. Thanks.
