### ISSUE TITLE
 Asp.Net Web Api. A problem with the base url path after the swagger implementation.

### ISSUE THREAD

**Issue by kamilkieszek** [Microsoft/aspnet-api-versioning#375]
I am using the Asp.Net Web API application and I used swagger, versioning and had to add the Route attributes for my methods, because I have several methods to get, post, etc. Now I have a problem. Before the swagger implementation, I used the basic path eg api / connect / test. Now the path does not work because it requires a version. Is it possible to use the versioning for the swagger documentation itself and leave the api to remain unchanged?

**Comment by commonsensesoftware** [comment]
It would appear that one of these solutions worked for you or you came up with an alternate solution. Feel free to reopen the issue or ask a new question if your issue wasn't resolved. Thanks.
