### ISSUE TITLE
V3 expected release date

### ISSUE THREAD

**Issue by cviktor** [Microsoft/aspnet-api-versioning#381]
Hi,

My team wants to use the library for api versioning, but I am curious about the release of the V3 version because we are a few months away from production. What I want to know is that, are there any roadmap or planned release date for the V3 version so we can maybe use the v3 right now and it will be stable until our planned production date, or we should stick with the current release and update when it will be stable?

Thanks, 
Viktor

**Comment by commonsensesoftware** [comment]
Fair question. Are you targeting ASP.NET Web API or Core? For Web API, there will be very little visible changes. For Core, I'm trying to reconcile against the forthcoming 2.2 release, which will contain new routing features. This may be mean that API versioning for Core has a 3.0 and 3.1 release that are not terribly far apart.

Unless you're getting deep into the customization and extensibility layers, you can expect things to be stable and not change much. Most of the new features are in the OData space. Other changes are enhancements or improvements in the internal mechanics.

Committing to a date is hard when this project isn't my day job and I'm an army of one. I expect 3.0 to be released within the next couple of months though. ASP.NET Core 2.2 is scheduled to be release by the end of the year. I expect to be on par or earlier than that. I'm trying to keep all the library flavors aligned at the moment so it's easy to find the official commits. I tend to not be so concerned with smaller patches and minor bumps.  I'm close to having Beta 2 out. After it has had a little time to burn in.

That's not a specific answer or date, but that's probably the best I can do - for now. Again, unless you go deep into the customization side, you should be able to go back to 2.x quite easily - possibly even transparently (e.g. full source compatibility). I hope that helps.

**Comment by cviktor** [comment]
Thanks for the quick answer. We are using ASP.NET Core and my problem was with the current version that I was not able to integrate with the Swashbuckle swagger generation despite the tutorials and issues I read (I knew about the necessity of the AddMvcCore) and tought that the beta will solve my problem, but after further investigation, it was a user error on my side. 

In the end we will stick with the current stable version but I tried update to the beta and there will be minimal changes, so thanks for the help, I am looking forward to the next version.
