### ISSUE TITLE
Issue Versioning APIs Behind an API Gateway/Swagger UI

### ISSUE THREAD

**Issue by jetedrow** [Microsoft/aspnet-api-versioning#383]
**Background:**
We are currently using Azure's API Management (APIM) Gateway for our public-facing developer portal, and are looking to add API versioning using this library.  The below issue could be related to other API gateways as well, not just APIM.

APIM also has a concept of versioning using the same mechanisms that are used by this library (i'm guessing it may be the same code).  Our organization has chosen to use query string versioning in APIM, thus allowing us to support multiple versions in a controlled "pretty" fashion through the gateway.

**The Issue:**
My issue is that although I can successfully generate swagger documents for all versions defined in my code, the fact that the "api-version" query element is also defined is causing issues with APIM, which is configured identcally. Because of this, APIM is doubling-up on the querystring parameters and passing two "api-version" parameters in the querystring which is causing issues.

If I manually take these parameters out from the specifications in APIM, or add a new OperationFilter within the services.AddSwaggerGen() call, I can eliminate this querystring parameter from the resulting swagger doc so that it will import into the APIM ecosystem and work correctly.  This works since APIM requires the same version number in the querystring, it is automagically passed to the back-end API as well. While this configuration will work, it ultimately does not allow the swagger UI to work out of the box, as the querystring parameter is no longer an option and is not sent to the back-end, causing an error.

**My Question:**
Is there any way to be able to generate multiple swagger documents - one that includes this (for use in the swagger UI for debugging) and another for use with APIM consumption. (Effectively two versions of the same "version" of the swagger document: one with the parameter, and one without this added.

I have tried without success in the operation filter to detemine selectively when to remove values, but there is nothing based on this code that will allow me to determine this.  Also,  when looking at the *-APIM versions in the UI, it states that there are no operations available.  (I'm guessing because this version is not defined anywhere in our code.)
```c#
services.AddSwaggerGen(opt =>
{
    var provider = services.BuildServiceProvider().GetRequiredService<IApiVersionDescriptionProvider>();
    foreach (var description in provider.ApiVersionDescriptions.Where(d => !string.IsNullOrWhiteSpace(d.GroupName)))
    {
        opt.SwaggerDoc(description.GroupName, CreateInfoForApiVersion(description));
        opt.SwaggerDoc($"{description.GroupName}-APIM", CreateInfoForApiVersion(description));
    }

    opt.OperationFilter<SwaggerDefaultValues>();
    opt.OperationFilter<APIMRemoveVersionParameter>();

    opt.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, $"{System.Reflection.Assembly.GetEntryAssembly().GetName().Name}.xml"), true);

});
```
```c#
app.UseSwaggerUI(c =>
{
    foreach (var description in provider.ApiVersionDescriptions.Where(d => !string.IsNullOrWhiteSpace(d.GroupName)))
    {
        c.SwaggerEndpoint($"/swagger/{description.GroupName}/swagger.json", description.GroupName.ToUpperInvariant());
        c.SwaggerEndpoint($"/swagger/{description.GroupName}/swagger.json", $"{description.GroupName.ToUpperInvariant()}-APIM");
    }
});
```
I'm at a loss on what I can do to be able to make this functionality work, or if there is some other feature out there I could use to accomplish this.

**Comment by jetedrow** [comment]
I have taken your suggestion and submitted a question to the APIM team.  Upon further inspection, APIM is actually not sending anything to the back-end API because it cannot find a proper route (due to the doubled api-version parameters) and returns a 404.

https://social.msdn.microsoft.com/Forums/en-US/193c102a-b3d3-42c1-8a00-54d36fd9edc9/apim-versioning-with-backend-api-versioning?forum=azureapimgmt&prof=required

I would appreciate anyone up-voting this thread that is interested in a solution for this issue with APIM.

I will investigate further into your two options, and will report back as to what solution I used.

Thanks for your help!

**Comment by commonsensesoftware** [comment]
Well-articulated. I agree with your assessment. I upvoted. We'll see what happens.

**Comment by commonsensesoftware** [comment]
With respect to this issue, I believe it has reached its conclusion. I've replied to the APIM discussion. The answers aren't particuarly _great_, so I've attempted to reach out internally to try and get traction for you.

Although it's _wonky_, I should mention that it's ok if your endpoint is using API versioning and has the **api-version** query parameter specified multiple times as long as the values are exactly the same. The validation is performed very early in the pipeline so the API version is not parsed. This means that semantically equivalent API versions are not enough. The requested values must be exactly the same literal values (but case-insensitive). I agree that it's silly, but this might be a workable solution for you with APIM without having to modify the Swagger document by hand.

**Comment by mrcunninghamz** [comment]
> With respect to this issue, I believe it has reached its conclusion. I've replied to the APIM discussion. The answers aren't particuarly _great_, so I've attempted to reach out internally to try and get traction for you.
> 
> Although it's _wonky_, I should mention that it's ok if your endpoint is using API versioning and has the **api-version** query parameter specified multiple times as long as the values are exactly the same. The validation is performed very early in the pipeline so the API version is not parsed. This means that semantically equivalent API versions are not enough. The requested values must be exactly the same literal values (but case-insensitive). I agree that it's silly, but this might be a workable solution for you with APIM without having to modify the Swagger document by hand.

This does not work. For some reason APIM is not fowarding  to the backend. I created a filter that runs during publish that removes the api-version from swagger and that turns out to look and work fine in APIM. The problem then becomes the swagger definition that is downloaded doesn't have a param for api-version which then causes issues when generating the clients via AutoRest.
