### ISSUE TITLE
2.3 MediaType Versioining Calls Version Twice in Core 2.1 on 404

### ISSUE THREAD

**Issue by RichardD012** [Microsoft/aspnet-api-versioning#387]
Not quite sure the best way to debug this but I added versioning with the following:
```c#
services.AddMvc().AddMvcOptions(option =>
{
    option.OutputFormatters.Clear();
    option.OutputFormatters.Add(new JsonOutputFormatter(StandardResolver.Default));
    option.InputFormatters.Clear();
    option.InputFormatters.Add(new JsonInputFormatter());
})
.SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
services.AddApiVersioning(o =>
{
    o.AssumeDefaultVersionWhenUnspecified = true;
    o.DefaultApiVersion = new ApiVersion(1, 0);
    o.ApiVersionReader = new MediaTypeApiVersionReader();
});
```

If I have the following two simplified versioned controllers:
```c#
[Route("api/lookup")]
[ApiVersion("1.0")]
public class LegacyLookupController : BaseCustomController
{
    [HttpGet, HttpOptions]
    [Route("{routeID}")]
    public async Task<IActionResult> GetLegacyRoute(string routeID, CancellationToken cancellationToken = default(CancellationToken))
    {
        return NotFound();
    }
}
```
and 
```c#
[Route("api/lookup")]
[ApiVersion("2.0")]
public class LookupController : BaseCustomController
{
    [HttpGet, HttpOptions]
    [Route("{routeID}")]
    public async Task<ActionResult<ResultType>> GetRoute(string routeID, CancellationToken cancellationToken = default(CancellationToken))
    {
        return NotFound();
    }
}
```
If I pass in the Content-Type header value of `text/plain;v=1.0`, the first method will be called once.  If I pass in the value of `text/plain;v=2.0` the second method is called, but it is executed twice (a break point will be hit twice).  

The browser only gets a single result so its definitely happening inside the request pipeline on the server and not something weird like a redirect.  

If the results return an "OK" response (actual type) the methods are executed once and everything is fine.  My concern here is the performance implications if we have some methods that have to do some sort of lookup to return a 404.  Seems weird that the method is executed twice only in that example.

FWIW, I made custom code for the MediaType reader and stepped through it and its only called once in all scenarios.

**Comment by RichardD012** [comment]
I just pulled down the code and ran from source on master and this isn't happening.  Not sure if there was something changed and fixed or if you could shed some light on what happened there but it def. doesn't do this on latest from master.

**Comment by RichardD012** [comment]
So I noticed this after posting that comment but what ends up happening on latest from master is that v2.0 works fine.  But v1.0 throws an "AmbiguousActionException".

```
TestProject.Controllers.API.LegacyLookupController.GetLegacyRoute(string, CancellationToken) (test-project)
TestProject.Controllers.GlobalController.Error404(Exception) (test-project)
```

So seems to potentially be somethign to do with my global error page perhaps?

**Comment by commonsensesoftware** [comment]
This could be the case. It depends on which branch of the source your working from. Ultimately, there is a rather severe limitation in the ASP.NET Core routing infrastructure that prevents API Versioning from making the right decision. The only way to solve this has been to collate all possible results and make a decision at the end with a _catch-all_ router. Fortunately, this only happens on a first pass. In the existing ASP.NET Core design, it's possible for the **IActionSelector** to be called multiple times. As a result API Versioning may not make it's final decision until later in the pipeline on the first pass. You _might_ see duplicate hits on the first class, but you shouldn't see that on subsequent calls.

Another consequence of this behavior is that certain types of middleware don't work well with API versioning in the default configuration. The error status page is one such case. Honestly, I'm of the strong opinion that the error page middleware makes zero sense for APIs, but you won't be the first person to ask for such a thing. It **is** possible to make it work, but you need to tweak the configuration. You should be able to find an example in the existing issues. If you can't find it, I think I have an example I can dig up. Let me know.

I've expressed my feedback to the ASP.NET team and some great new improvements are coming in 2.2. Once that support is enabled, much of these types of oddities should go away. I hope that points you in the right direction and provides a little bit of explanation.

**Comment by RichardD012** [comment]
I actually agree with your opinion.  The error pages don't make any sense but we have a blend of MVC routes and API routes.  The MVC routes benefit greatly but the limitation really hasn't bothered us as most of the api clients we have only care about status.  But I would very much not like that middleware for API routes, just never took the time to really care.  Guess that time is now.

**Comment by RichardD012** [comment]
Thanks for pointing me in the right direction.  That was definitely it.  I made a custom extension based off of the Diagnostics middleware (found [here](https://github.com/aspnet/Diagnostics/blob/ebafbcdae33ddb2981f96c7790e1c6f422a59a8a/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesExtensions.cs#L163)) That simply excludes based on the conditions that match our criteria.  It falls back to the middleware exception handling otherwise and seems to work perfectly for our needs.  No more error pages for API results and can get actual restful responses now.
