### ISSUE TITLE
Getting UnsupportedApiVersion issue

### ISSUE THREAD

**Issue by senad004** [Microsoft/aspnet-api-versioning#389]
I am getting below error when calling API link directly on browser. Can you please help on this issue?

<Error>
<Error>
<Code>UnsupportedApiVersion</Code>
<Message>
The HTTP resource that matches the request URI  does not support the API version '1'.
</Message>
</Error>
</Error>

**Comment by senad004** [comment]
<Error>
<Error>
<Code>UnsupportedApiVersion</Code>
<Message>
The HTTP resource that matches the request URI  does not support the API version '1'.
</Message>
</Error>
</Error>

**Comment by commonsensesoftware** [comment]
You've provided no context as to what you configuration is and how you are versioning. By default, the query string parameter **api-version** would mandatory. It sounds like you have not specified it.

**Comment by commonsensesoftware** [comment]
This is a basic, documented behavior in API versioning. I suspect you've since found a solution. If still need assistance, feel free to reopen the issue and please provide more context.
