### ISSUE TITLE
3.0.0 beta 2 value factory error on getedmmodels

### ISSUE THREAD

**Issue by figuerres** [Microsoft/aspnet-api-versioning#401]
ValueFactory attempted to access the Value property of this instance.
this is in startup.cs   -- will try rollback to beta 1 of 3.0.0  which did not get this issue for me.

3.0.0 beta 1 does not throw this error.

Line 203:            var model = Builder.GetEdmModels();

here is the stack trace:

[InvalidOperationException: ValueFactory attempted to access the Value property of this instance.]
   System.Lazy`1.CreateValue() +411
   System.Lazy`1.LazyInitValue() +152
   System.Lazy`1.get_Value() +75
   Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.GetControllerMapping() +16
   System.Web.Http.Routing.AttributeRoutingMapper.AddRouteEntries(SubRouteCollection collector, HttpConfiguration configuration, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +48
   System.Web.Http.Routing.<>c__DisplayClass1_1.<MapAttributeRoutes>b__1() +57
   System.Web.Http.Routing.RouteCollectionRoute.EnsureInitialized(Func`1 initializer) +61
   System.Web.Http.Routing.<>c__DisplayClass1_0.<MapAttributeRoutes>b__0(HttpConfiguration config) +91
   System.Web.Http.HttpConfiguration.ApplyControllerSettings(HttpControllerSettings settings, HttpConfiguration configuration) +70
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +165
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +54
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +54
   System.Web.Http.Controllers.HttpControllerDescriptor..ctor(HttpConfiguration configuration, String controllerName, Type controllerType) +105
   Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.InitializeControllerInfoCache() +377
   System.Lazy`1.CreateValue() +411
   System.Lazy`1.LazyInitValue() +152
   System.Lazy`1.get_Value() +75
   Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.GetControllerMapping() +16
   Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetApiVersions() +166
   Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetEdmModels() +18
   ADL.Web.Services.Adl.Startup.Configuration(IAppBuilder app) in C:\TFSAzure\ATRAK Services\ADL.Web.Services.Adl\Startup.cs:203

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +160
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
   Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +66
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +123
   Microsoft.Owin.Host.SystemWeb.<>c__DisplayClass2.<InitializeBlueprint>b__0(IAppBuilder builder) +71
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +462
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +40
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +70
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +115
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +106
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +523
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +176
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +220
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +303

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +658
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +89
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +188

**Comment by figuerres** [comment]
i will see what i can find, i am for sure not calling EnsureInitalized() seen that issue before.
i did have some odd bits of init code and based on your sample i moved it to one place - startup.cs hoping that would solve it but no joy.
only by going back to beta 1 did it stop.
was hoping to get to see a speed fix!!

in other news i found that one of my large api sets will be stuck back on the older packages.
some kind of problem came up where jwt tokens were not working when our angualr 5 client app got a token.  not your issue ....  but what a pain!  the calls just started to fail with no error results and no logged errors so i we left having to guess at what was going on.
something in the OWIN / jwt / authorize pipeline

**Comment by commonsensesoftware** [comment]
Anything you are able to share about your setup will be useful. I _suspect_ it is something related to controller settings being applied by an attribute. I can't say what for sure.

The _speed_ fix is now in, but it didn't make the cut for Beta 2. You can see the improvements in PR #398.  @LuukN2 has done some great work. He reported his scenario went from a couple of minutes (I believe) down to 10 seconds! I suspect you'll see equally significant improvements. Unfortunately, I have to draw the line in the sand somewhere or I'll never ship. There were a large number of changes that people have been waiting on for quite some time. _Slow_ isn't nearly as bad as _doesn't work_. ;) I expect the next round to be RC or even the official release. The performance fix will be there.

**Comment by commonsensesoftware** [comment]
Any chance you can up with anything that can be shared for the investigation? I haven't been able to reproduce your scenario - yet.

Based on the stack trace, I've dug in a little bit. This error is occurring when the direct routes (aka _attribute_ routes) are being initialized. I presume this means that you're either mixing OData and vanilla Web API routes or you just haven't removed the attribute route setup. I **strongly** discourage you from mixing attribute and convention-based routing. There are certain scenarios that simply will not work in API Versioning; it's a limitation of the routing in Web API. If your intent is to only use convention-based routes, then you must still have `configuration.MapHttpAttributeRoutes` in your setup. Despite OData having attributes, it does not use the direct routing feature at all.

**Comment by figuerres** [comment]
odata api has no attribute routing.

web api has a different prefix and has attributes.

in time i may be able to revise the api routes to remove almost all attributes but that will take time.

ms needs to start telling developers to stop using attributes .... have to look at my apis and see how to redo them, and posibly break them up into different apps  so i can isolate problems.

**Comment by commonsensesoftware** [comment]
The issue is specific to Web API and more to do with the OData implementation than anything else. Attributes were an after-thought in Web API. To exacerbate the situation, OData adds its own conventions on top of the routing system using a greedy _catch-all_ route segment (e.g. `odataPath*`). I've tried to make the choices in routing transparent to versioning, but throwing OData into the Web API mix introduces challenges. Thus far, I haven't encountered such issues in ASP.NET Core, but I had to rework a lot of OData's default implementation.

What I really need is a repro so I can investigate and fix this problem. It shouldn't be happening. Now that I know you're mixing things up, I can try modifying the _advanced_ sample to see if I can't replicate the issue.

>Prefix is irrelevant to the routing system in terms of matching a controller. The route template matches a controller name and the controller name maps to a controller descriptor with its backing type. As long as you don't have the same resource (ex: `api/resource` and `odata/resource`) using different routing styles, you should be fine. Mixing attribute routing with convention routes, in particular OData, _may_ not behave properly with versioning. I've attempted to resolve that issue more than once and have yet to achieve 100% success in all cases. I call this limitation out in the wiki. I'm happy to entertain a PR or collaboration to address it.

**Comment by figuerres** [comment]
to be sure i am getting things right:
the AspNet Core routing of Web APi and OData is cleaner than Asp.Net 4.xxx  
is that right ?

if the EF Core team have the Sql Geography support fixed  ( it looks like they might) then i think we will be looking at moving to Asp.Net Core in the near future.

do you know of any good guidance on this process ? Migrating  from Net 4.xx to .Net Core  for Web API and OData.

many projects are moving to Core and our big hold back has been EF Geography support.

**Comment by commonsensesoftware** [comment]
The routing in ASP.NET Core has been completely redesigned and rebuilt from the ground up. It's quite different from the old stack and much better. For one, there is _real_ concept of controllers in ASP.NET Core; it only cares about candidate actions and matching those. The controller base classes are merely a logical container for common functionality used by actions.

This is markedly different from Web API where there was always a controller and set of corresponding actions. I really had to shoehorn things into beat Web API into submission. Web API expects there to be a single controller implementation for every logically registered resource. So a route template like `api/resources` expects to map to `ResourcesController`  where `Resources` is the name by convention. I had to convince Web API there was only a single matching **HttpControllerDescriptor**, while having an implementation that actually represents multiple descriptors - one for each implementation.

In ASP.NET Core, the design discovers all possible candidates, regardless of defining controller, and asks the **IActionSelector** to pick the best one. This is much easier to implement for API versioning because there is no different in routing, the implementation only needs to disambiguate duplicate actions by the API version discriminator.

Sadly, the OData team didn't listen to the ASP.NET team and went with an implementation that still expects a single matching action in the configured EDM. This was quite a bit of work for me to rework their design to make it work for API versioning because there can not only be multiple matches, they can be mixed with non-OData matches too.

I'm not suggesting that you switch everything just yet, but the routing and mixing of routing in ASP.NET Core is way better than it was in Web API. There are likely a few more kinks to workout with API versioning (hence the Beta tag), but mixing the two should orders of magnitude more fluid without bizarre routing wonkiness. All the pain thus far has been on the implementation side - e.g. my pain, but seamless for service authors.

**Comment by commonsensesoftware** [comment]
I've tried without success to repro your scenario. I have no doubt that it's _real_, I just can't seem to reproduce a setup that triggers it.

Here's what I know to be true thus far (from the call stack):
1. The error is being triggered through execution of `IControllerConfiguration.Initialize`
2. **IControllerConfiguration** is typically implemented via an attribute that is applied to a controller
3. **IControllerConfiguration** is recursively invoked via the **HttpControllerDescriptor** constructor
    a. 3 calls in the stack trace prove the following: `YourController` → `ApiController` → `Object`
4. Exception appears to originate from a call to `configuration.MapHttpAttributeRoutes` to configure attribute routing

This leads me to a few other questions and/or oddities:
1. It would very unusual to map attribute routes by controller and is normally done for the entire app
2. Is the name `MapAttributeRoutes` in the call stack suggesting this might be coming from MVC. You aren't running MVC with Web API and OData too are you?

I added some attribute-routed controllers to the _advanced_ sample app with mixed routing and I could not repro this issue. I tried adding a custom **IControllerConfiguration** and that alone didn't change anything. I did, however, notice (and vaguely remember) that the order of route registration matters for this type of setup. I almost certain you **must** call `configuration.MapHttpAttributeRoutes` **before** all other routing configurations, including for OData. At least for me, that was the only way I got it to work.

I hope that helps. Any more information or a repro will greatly assist me in helping you iron this out.

**Comment by figuerres** [comment]
thanks for the feedback and info.
i have spoke with the two other developers and we are going to work on changes as we all see that we have a lot of api code and need to plan so that it is manageable and maintainable.

mvc, no we have no mvc views , all our ui is client based.

**Comment by commonsensesoftware** [comment]
Great! Thanks. If you happen to resolve the issue or have other feedback or repros, please share. Setting up and testing all the possible application combinations is difficult and there's certainly a chance that there is a bug somewhere. This is why I let the Beta releases burn in a little bit. It's also possible that there may have been an issue in your configuration that didn't previously surface. Regardless, there is clearly some difference between Beta 1 and Beta 2 that is affecting you and I would love to rule out that it's not a bug - if possible.

**Comment by commonsensesoftware** [comment]
Given that no one else seems to have reported this and I am unable to repro it myself, it would seem this issue has reached its conclusion. If you or anyone else can share additional information, I'm happy to reopen this and continue investigating.

**Comment by bigbl** [comment]
Hi, I just got the same error

**Comment by bigbl** [comment]
after upgrading to Microsoft.AspNet.OData v 7.1.0 from 6.1.0 and Microsoft.AspNet.OData.Versioning 3.0.0

**Comment by bigbl** [comment]
[InvalidOperationException: ValueFactory attempted to access the Value property of this instance.]
   System.Lazy`1.CreateValue() +411
   System.Lazy`1.LazyInitValue() +152
   System.Lazy`1.get_Value() +75
   System.Web.Http.Dispatcher.DefaultHttpControllerSelector.GetControllerMapping() +16
   System.Web.Http.Routing.AttributeRoutingMapper.AddRouteEntries(SubRouteCollection collector, HttpConfiguration configuration, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +48
   System.Web.Http.Routing.<>c__DisplayClass1_1.<MapAttributeRoutes>b__1() +57
   System.Web.Http.Routing.RouteCollectionRoute.EnsureInitialized(Func`1 initializer) +61
   System.Web.Http.Routing.<>c__DisplayClass1_0.<MapAttributeRoutes>b__0(HttpConfiguration config) +91
   System.Web.Http.HttpConfiguration.ApplyControllerSettings(HttpControllerSettings settings, HttpConfiguration configuration) +70
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +165
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +54
   System.Web.Http.Controllers.HttpControllerDescriptor..ctor(HttpConfiguration configuration, String controllerName, Type controllerType) +105
   System.Web.Http.Dispatcher.DefaultHttpControllerSelector.InitializeControllerInfoCache() +400
   System.Lazy`1.CreateValue() +411
   System.Lazy`1.LazyInitValue() +152
   System.Lazy`1.get_Value() +75
   System.Web.Http.Dispatcher.DefaultHttpControllerSelector.GetControllerMapping() +16
   Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetApiVersions() +166
   Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetEdmModels() +18
   IT.Applications.Delivery.Services.Platform.Startup.CreateHttpConfiguration() in C:\Users\p00015230\Source\Repos\IT.Applications.Delivery.Services.Platform\IT.Applications.Delivery.Services.Platform\Startup.cs:97
   IT.Applications.Delivery.Services.Platform.Startup.Configuration(IAppBuilder app) in C:\Users\p00015230\Source\Repos\IT.Applications.Delivery.Services.Platform\IT.Applications.Delivery.Services.Platform\Startup.cs:32

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +160
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
   Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +66
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +123
   Microsoft.Owin.Host.SystemWeb.<>c__DisplayClass2.<InitializeBlueprint>b__0(IAppBuilder builder) +71
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +462
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +40
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +70
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +115
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +106
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +536
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +173
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +218
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10074976
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +95
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

**Comment by commonsensesoftware** [comment]
This is nearly impossible for me to troubleshoot without a repro. I have tried unsuccessfully to repro the scenario myself. There is something specific about the setup that causes this - beyond the obvious cyclicular call.

One thing I do notice in the call stack is:

`System.Web.Http.Dispatcher.DefaultHttpControllerSelector.GetControllerMapping()`

This suggests you are calling `VersionedODataModelBuilder.GetEdmModels` before `configuration.AddApiVersioning`. The `configuration.AddApiVersioning` extension method replaces the default **IHttpControllerSelector** and **IHttpActionSelector** so it _should_ be called early in the setup. This might be cause. I would also recommend comparing the sample application setups to your own for other clues about how the configuration might be different.

I have nothing but a stack trace to go on here. I'm can't fix, nor even investigate, what I can't reproduce.

**Comment by bigbl** [comment]
it is was a wrong configuration on my part. not a bug

**Comment by bigbl** [comment]
httpConfig.MapHttpAttributeRoutes() this line is creating the error. I have controllers with different ApiVersion attribute and to use this setting. please advise! thank you!

**Comment by bigbl** [comment]
In my case,  I do have API and Odata Controllers mixed. for odata controllers APIVersion attribute is used and for the WEB API  the version is API specific. If add  httpConfig.AddApiVersioning(), the odata controllers work as expected, but the web api controllers don't ---> error: "API needs version". if add 
httpConfig.MapHttpAttributeRoutes(), I get error ---> "ValueFactory attempted to access the Value property..." Is there easy way to solve it, so I can mix api and odata controllers within same web api?

**Comment by bigbl** [comment]
and thank you so much for your attention!

**Comment by bigbl** [comment]
I had to upgrade the Odata package so I can use "IN" clause in my queries.

**Comment by bigbl** [comment]
the versioning was working with prior Odata package for both odata and api controllers with httpConfig.MapHttpAttributeRoutes() setting

**Comment by commonsensesoftware** [comment]
Ah … and I forgot one more thing. The order of route registration is important. If you are going to use _attribute routing_, it needs to be first. Things will not work otherwise (but it still doesn't repro the error described).

**Comment by commonsensesoftware** [comment]
Attached is a variant of the [Advanced OData Sample](../blob/master/samples/webapi/AdvancedODataWebApiSample), which enables _attribute routing_ and adds a few extra attribute-routed controllers. It doesn't repro the scenario, but perhaps it can help you troubleshoot or generate a repro on your side.

Attachment: [Advanced OData Sample with Attribute Routing](https://github.com/Microsoft/aspnet-api-versioning/files/2713726/AdvancedODataWebApiSample.zip)
