### ISSUE TITLE
Dispose the temporary service provider in the sample code

### ISSUE THREAD

**Issue by jramos-ceres-br** [Microsoft/aspnet-api-versioning#403]
In the examples, maybe the instance of IApiVersionDescriptionProvider will stay around in memory because of the temporary service provider is not disposed.

Current code:
```
// note: that we have to build a temporary service provider here because one has not been created yet
var provider = services.BuildServiceProvider().GetRequiredService<IApiVersionDescriptionProvider>();
```

Suggested code:
```
// note: that we have to build a temporary service provider here because one has not been created yet
using (var serviceProvider = services.BuildServiceProvider())
{
    var provider = serviceProvider.GetRequiredService<IApiVersionDescriptionProvider>();
    ... other code ...
}
```

**Comment by commonsensesoftware** [comment]
Fair point. While the examples are purely meant to an illustration and not necessarily _production_ quality code, there's no reason to not provide sound examples. I'll queue this change in an upcoming PR that will be tracked by this issue. Thanks for the feedback.
