### ISSUE TITLE
Updated version of  aspnetcore swagger sample needed for Swashbuckle.AspNetCore 5?

### ISSUE THREAD

**Issue by ThomasCronholm** [Microsoft/aspnet-api-versioning#429]
In the Swashbuckle v5 beta, SwaggerDefaultValues : IOperationFilter has changed the interface. It now uses Microsoft.OpenApi.Models and looks like this:
```
using Microsoft.OpenApi.Models;

namespace Swashbuckle.AspNetCore.SwaggerGen
{
    public interface IOperationFilter
    {
        void Apply(OpenApiOperation operation, OperationFilterContext context);
    }
}
```
This also means that the `parameter.Default = routeInfo.DefaultValue;` does not work as it does not exist.
Maby this needs a new sample.
I would also like a quick hint to how I can resolve the Default value please :)

**Comment by commonsensesoftware** [comment]
I only use Swashbuckle as one possible way to integrate Swagger. It's certainly not the only one and there are no dependencies on it here. There are plenty of other Swagger generators (ex: NSwag) and tools that make use of the API Explorer. In general, I do not support unreleased flavors of other libraries. It's simply too much for me to maintain and it's confusing for customers that only use released packages.

Your question is probably better answered in the [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) or [OpenAPI.NET](https://github.com/Microsoft/OpenAPI.NET) repos, but it appears you can set the default value via [OpenApiParameter.Schema.Default](https://github.com/Microsoft/OpenAPI.NET/blob/3cdbb175a1b72d3270b2582ee6d9c27675728d16/src/Microsoft.OpenApi/Models/OpenApiSchema.cs#L87) or [OpenApiParameter.Schema.Enum](https://github.com/Microsoft/OpenAPI.NET/blob/3cdbb175a1b72d3270b2582ee6d9c27675728d16/src/Microsoft.OpenApi/Models/OpenApiSchema.cs#L205).

In previous discussions with Swashbuckle, the meaning of _default_ is a value that can be used when no value is provided by the user (ex: query parameter). A path parameter, on the other hand, is typically required, but can still have a default value. In Swagger parlance, that would be modeled as an enumeration with a single value. I'm not sure which of these apply to you, but that's how you should be able to make it work.

**Comment by ThomasCronholm** [comment]
Thank you for the info :)

**Comment by natelaff** [comment]
@ThomasCronholm did you find any more elegant solution than

`                if (parameter.Schema.Default == null)
                {
                    parameter.Schema.Default = new OpenApiString(description.DefaultValue.ToString());
                }
`

Or is that the way to do it with the OpenApiString?

**Comment by commonsensesoftware** [comment]
@natelaff, I _believe_ that is the correct way. The [v4.0 Swagger Sample](../blob/release/4.0/samples/aspnetcore/SwaggerSample/SwaggerDefaultValues.cs) does it that way and it seems to work.

We still don't have the support from Swashbuckle to intrinsically support default values that I'm aware of. I'm hopeful that will happen sometime after the alignment to the new OpenAPI libraries.

For everyone's edification, there was some resistance to the meaning of `routeInfo.DefaultValue`. I had a discussion with the Swashbuckle team and we agreed on the Swagger consumption of a default value and how it should be modeled. After careful examination of the API Explorer APIs, the ASP.NET team agreed this meant something different as well, but a true default parameter value was missing and needed. There is now `ApiParameterDescription.DefaultValue`, which didn't exist prior to ASP.NET Core 2.1/2.2 (can't remember which one now). This should be the value that is used. The new examples in API Versioning illustrate this.

I hope that helps.

**Comment by natelaff** [comment]
Thanks @commonsensesoftware!

**Comment by ThomasCronholm** [comment]
@natelaff Sorry for the late reply, no I did not find a more elegant solution.

**Comment by krispenner** [comment]
@commonsensesoftware 
I noticed the suggested solution assumes the default value is always a string, is that safe?
I found a factory that appears to create the correct type based on the schema and object.
Just curious if that would be a safer/cleaner option?

```cs
if (parameter.Schema.Default == null && description.DefaultValue != null)
{
    parameter.Schema.Default = OpenApiAnyFactory.CreateFor(parameter.Schema, description.DefaultValue);
}
```

**Comment by commonsensesoftware** [comment]
@krispenner,@icnocop, <anyone else> know what the correct setup is now for `OpenApiAnyFactory.CreateFor`? @icnocop was kind of enough to submit a PR for the fix and now I'm seeing that things were refactored to `OpenApiAnyFactory.CreateFromJson`, seemingly without any path backward. I looked for an example in the tests, but can't find one. It's unclear how this should be constructed.

**Comment by icnocop** [comment]
@commonsensesoftware It looks like you were able to figure it out, right?

https://github.com/microsoft/aspnet-api-versioning/commit/569cdcc87a49b96a4980f6c63e5b32e1a02bb1af#diff-39b68268561ce9c7efc33b37100eef4622ee197309b5cbb7a59ef62b16606792

Thank you.

**Comment by commonsensesoftware** [comment]
@icnocop I went with my best guess. It doesn't blow up and _seems_ to do the right thing. I'll assume it's correct until someone says otherwise. If no one knows or it looks good, then we're solid.

**Comment by AsuraKev** [comment]
Did anyone get OpenApiAnyFactory doesnt contain method for CreateFromJson ?

**Comment by commonsensesoftware** [comment]
@AsuraKev which version of Swashbuckle, API Versioning, and .NET are you using? `CreateFromJson` has been the method for 3+ years now, which was first introduced in Swashbuckle `6.x` I believe.

**Comment by AsuraKev** [comment]
Hey @commonsensesoftware. Thanks for asking 

I thought I had latest installed but obviously not. After upgrade it to latest it alright now! Thanks 😃
