### ISSUE TITLE
The type name 'IApiVersionDescriptionProvider' could not be found

### ISSUE THREAD

**Issue by hasanaliagar07** [Microsoft/aspnet-api-versioning#434]
```c#
    using Microsoft.AspNetCore.Mvc.ApiExplorer;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Options;
    using Swashbuckle.AspNetCore.Swagger;
    using Swashbuckle.AspNetCore.SwaggerGen;
```

I was defined as above, but I am getting an error to below code.

<img width="767" alt="screen shot 2019-01-10 at 08 13 57" src="https://user-images.githubusercontent.com/31071157/50947532-d8c2fb00-14af-11e9-94fa-ef629508d68a.png">

**Comment by Discjoggy** [comment]
Is `Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer` referenced in your project? It looks like this reference could not be solved because this package is missing.

**Comment by commonsensesoftware** [comment]
Spot on @Discjoggy.

You'll want to make sure you've included the packages:
* Microsoft.AspNetCore.Mvc.Versioning
* Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer

I hope that helps.

**Comment by hasanaliagar07** [comment]
> Is `Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer` referenced in your project? It looks like this reference could not be solved because this package is missing.

The problem was solved when I include `Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer` reference. Thank you everyone.
