### ISSUE TITLE
How to handle HttpRequestMessage if use attribute routing?

### ISSUE THREAD

**Issue by ruslanlbondar** [Microsoft/aspnet-api-versioning#440]
I need to catch HttpRequestMessage so that I can get some information from header.
I have the following routing

           config.Routes.MapHttpRoute(
                name: "VersionBaseBusinessEnpointRoute",
                routeTemplate: "api/v{apiVersion}/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional },
                constraints: new { apiVersion = new ApiVersionRouteConstraint() },
                handler: routeHandler
            );

where routeHandler process HttpRequestMessage.
How can I handle HttpRequestMessage if I use attribute routing? (ASP.NET Framework)

**Comment by commonsensesoftware** [comment]
This _appears_ to be more of a generic question about Web API. From your description, it seems you are looking for a **DelegatingHandler**.

```c#
public class MyHandler : DelegatingHandler
{
  protected override Task<HttpResponseMessage> SendAsync(
    HttpRequestMessage request,
    CancellationToken cancellationToken)
  {
    // TODO: special processing
    return base.SendAsync(request, cancellationToken);
  }
}
```

Then you'd register it with:

```c#
configuration.MessageHandlers.Add( new MyHandler() );
```

This is just one of several possibilities however. This approach would execute in **every** request. If you want specific processing for controller actions, then using an **IHttpActionFilter** might be better.

I hope that helps.

**Comment by ruslanlbondar** [comment]
I forgot to say, but I can't do that.

I have several system controllers that take certain information from the header, but there are business controllers that also take information from the header. System and business controllers have own routing and routeHandler which takes info from the header. I can't do it anyway ( So I need to do handling in routing. Maybe it is possible to do it with this library?

**Comment by commonsensesoftware** [comment]
I'm not sure I completely follow. If the behavior is specific to set of controllers and/or routes, you can still use a custom **HttpMessageHandler** or **IHttpActionFilter**. If you want the behavior for everything under a specific route template, then a **HttpMessageHandler** might be a better choice.

First, make sure you pass the inner handler like so:

```c#
public class MyHandler : DelegatingHandler
{
  public MyHandler( HttpMessageHandler innerHandler ) : base( innerHandler ) { }
  protected override Task<HttpResponseMessage> SendAsync(
    HttpRequestMessage request,
    CancellationToken cancellationToken)
  {
    // TODO: special processing
    return base.SendAsync(request, cancellationToken);
  }
}
```

Then simply update your example as:

```c#
config.Routes.MapHttpRoute(
  name: "VersionBaseBusinessEnpointRoute",
  routeTemplate: "api/v{apiVersion}/{controller}/{id}",
  defaults: new { id = RouteParameter.Optional },
  constraints: new { apiVersion = new ApiVersionRouteConstraint() },
  handler: new MyHandler( routeHandler )
);
```

How your custom handler is implemented depends on whether you want preprocessing, postprocessing, or both. If I had a better understanding of what you are hoping to achieve, I might be able to give a better answer.

**Comment by ruslanlbondar** [comment]
I meant a little bit different :)
I have something like this:

Controllers

Business controller (I have a lot of these kind of controllers)
```
[RoutePrefix("api/v{version:apiVersion}/ALogic")]
public class AController : ApiController
{
// POST: api/v1/ALogic/12/fffffff/42
        [HttpPost, Route("{id1}/fffffff/{id2}")]
        public async Task<IHttpActionResult> PostAsync(int id1, int id2) { }

// GET: api/v1/ALogic
        [HttpGet]
        public async Task<IHttpActionResult> GetAsync(...) { }
}
```

System controller (I have a lot of these kind of controllers)
```
public class BController : ApiController
{
// GET: api/v1/BLogic
        [HttpGet]
        public async Task<IHttpActionResult> GetAsync(...) { }
}
```
Config1 (General route. This route is used by methods that do not have an attribute. For example AController.GetAsync method)

```
config.Routes.MapHttpRoute(
    name: "SomeName",
    routeTemplate: "api/v{apiVersion}/{controller}/{id}",
    defaults: new { id = RouteParameter.Optional },
    constraints: new { apiVersion = new ApiVersionRouteConstraint() },
    handler: routeBusinessHandler
);
```
Config2 (System route. This route is used by methods in BController)
```
config.Routes.MapHttpRoute(
    name: "SomeName2",
    routeTemplate: "api/v{apiVersion}/BController/{id}",
    defaults: new { id = RouteParameter.Optional },
    constraints: new { apiVersion = new ApiVersionRouteConstraint() },
    handler: routeSystemHandler
);
```

So, as you can see, there is a general route (config1) for controllers/methods without attribute. There is a list of system routes (I mean config2. Here I wrote only one route and one system controller). And there are methods with route attribute. 
For general route I have routeBusinessHandler. 
For system routes I have routeSystemHandler.
How to create a handler for routes that are registered in the attributes? I need a handler "routeBusinessHandler" for attribute routes.

Can I do it with aspnet-api-versioning package? If this is not supported, then I think it will be a good feature :)

**Comment by commonsensesoftware** [comment]
Well ... on personal note … I **strongly** discourage mixing attribute and convention-based routing together. Yes - you _can_ do it, but I've seen it cause teams nothing but grief. It can be very difficult to rationalize how routes are being evaluated; especially in Web API.

Your description of the setup helps, but you still didn't quite articulate what you're trying to achieve. You _could_ still use a **HttpMessageHandler** and then detect which path you are taking by inspecting the `Route.Handler` in the request pipeline.

A cleaner setup for this scenario is probably an **IHttpFilter** implemented as an **ActionFilter**. Something like this:

```c#
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Http.Filters;
using System.Web.Http.Controllers;
using static System.AttributeTargets;

[AttributeUsage( Class | Method, Inherited = true, AllowMultiple = false )]
public class SpecialAttributeRouteProcessorAttribute : ActionFilter
{
  public override Task OnActionExecutingAsync(
    HttpActionContext actionContext,
   CancellationToken cancellationToken )
  {
    // TODO: optional special handling BEFORE the action is invoked
    return Task.CompletedTask;
  }

  public override Task OnActionExecutedAsync(
    HttpActionExecutedContext actionExecutedContext,
    CancellationToken cancellationToken )
  {
    // TODO: optional special handling AFTER the action is invoked
    return Task.CompletedTask;
  }
}
```

Then you can apply it to a controller or action like so:

```c#
[SpecialAttributeRouteProcessor]
[RoutePrefix("api/v{version:apiVersion}/ALogic")]
public class AController : ApiController
{
  // POST: api/v1/ALogic/12/fffffff/42
  [HttpPost, Route("{id1}/fffffff/{id2}")]
  public async Task<IHttpActionResult> PostAsync(int id1, int id2) { }

  // GET: api/v1/ALogic
  [HttpGet]
  public async Task<IHttpActionResult> GetAsync(...) { }
}
```

Since filters can be inherited, you could also apply this to common base class. That decision is up to you. Regardless, these are intrinsic capabilities of Web API and aren't specific to anything about API versioning.

**Comment by ruslanlbondar** [comment]
@commonsensesoftware ok, I will use your solution with filter. I think setting handler for route attributes in your package will be good feature. Thank you for your time and solution :)

**Comment by commonsensesoftware** [comment]
Great! Looks like you're good to go now. Thanks.
