### ISSUE TITLE
Controller endpoints all return 404 status code after upgrading to latest version of Microsoft.AspNetCore.Mvc.Versioning

### ISSUE THREAD

**Issue by alec-lieberman-ef** [Microsoft/aspnet-api-versioning#448]
Hello,

We have a bunch of microservice .net core 2.2 projects running API controllers. After upgrading one particular project to the latest version of  Microsoft.AspNetCore.Mvc.Versioning Version="3.1.1", all of the controller endpoints in this project are returning 404s. I can confirm that the endpoints work as expected if I revert the version of the package to 2.3.0, which is what we were using previously.

We have a simple HealthCheck controller with one GET endpoint that I have been testing various fixes with. The endpoint looks like:

`[Route("api/v{version:apiVersion}/[controller]"), ApiVersion("1.0")]
    [ApiController]
    public class HealthCheckController : Controller
    {
        [HttpGet]
        public IActionResult CheckHealthAsync()
        {
            return Ok();
        }
    }`

When I try and call this endpoint like: 
http://localhost/api/v1.0/healthcheck, 

I get a 404, but with the older version of the package it returns 200 OK as expected.

Is there something I am missing when I did this package update?

Thank you.

**Comment by commonsensesoftware** [comment]
The change is almost certainly `options.UseApiBehavior`, which now defaults to `true` instead of `false`. The expectation is that that controllers are decorated with `[ApiController]` when the value is `true`. This behavior helps those that are a mixing API and non-API controllers together. Although it's called out in the release notes, I was leery of making this change. The transition to 3.1 is the lowest version that takes a direct reference to a version of ASP.NET Core that contains **ApiControllerAttribute**.

**Comment by alec-lieberman-ef** [comment]
The weird thing is that we have multiple .net Core microservice projects that we've been upgrading to use the [ApiController] attribute and we have not ran into any issues with those. We have identical packages between projects and this one specific project keeps throwing 404 status codes for every endpoint. I have tried both option 1 and 2 in this project and have not had any luck yet. But all of our other projects are using [ApiController] attribute and are working correctly. Not sure what to try next.

**Comment by commonsensesoftware** [comment]
Are you able to share your configuration, at least part of it? A full repro is always best, but just seeing the configuration might help.

A couple of things to possibly try to narrow things down:

1. Do things work if you disable API versioning (you'll need a controller with a single version)?
2. Are you able to take one of the working sample projects and get things to work or repro?

**Comment by alec-lieberman-ef** [comment]
I did notice that in in this project, we do have multiple controllers that have the same base route, like

ControllerOne : `[Route("api/v{version:apiVersion}/product")]`

Controller Two: `[Route("api/v{version:apiVersion}/product")]`

But all the endpoints are different.

Would this cause any issues?

**Comment by alec-lieberman-ef** [comment]
I don't think that is the issue. I just deleted every other controller from my project except the HealthCheck one I posted earlier and it is still returning a 404.

**Comment by alec-lieberman-ef** [comment]
I have resolved the issue. We were registering something in our startup that was breaking everything. Removing that fixed it all. Thank you for your help. I will close this.

**Comment by f4rukr** [comment]
Hi @alec-lieberman-ef can you post in the comments which part have you removed
