### ISSUE TITLE
VersionedODataModelBuilder Breaks PascalCase OData Model

### ISSUE THREAD

**Issue by greg-lomax** [Microsoft/aspnet-api-versioning#459]
The initialization of modelBuilderFactory in VersionedODataModelBuilder breaks PascalCase OData services by enforcing CamelCase:

Func<ODataModelBuilder> modelBuilderFactory = () => new ODataConventionModelBuilder().EnableLowerCamelCase();

How should I initialize ODataConventionModelBuilder to by-pass this problem?

**Comment by LuukN2** [comment]
I assume you mean the VersionedODataModelBuilder.

It's quite simple, set the ModelBuilder factory to return a new OdataModelBuilder instead.

Something like this:
`var versionedOdataModelBuilder = new VersionedODataModelBuilder 
{
ModelBuilderFactory = () => new ODataConventionModelBuilder();
}`

**Comment by greg-lomax** [comment]
Too obvious a solution for my tired brain.  Thank you!

**Comment by greg-lomax** [comment]
Worked as advertised
