### ISSUE TITLE
MapVersionedODataRoutes is not available

### ISSUE THREAD

**Issue by Danthar** [Microsoft/aspnet-api-versioning#461]
I am using ASP.NET WebApi with OData controllers.

My config currently looks like this:
```

config.MapODataServiceRoute("odata", "odata", BuildEdmModel(),
                pathHandler: new PathAndSlashEscapeODataPathHandler(), routingConventions: ODataRoutingConventions.CreateDefault());
```

where the BuildEdmModel() uses the _ODataConventionModelBuilder_

I installed the 3.0.1 version of the Microsoft.AspNet.WebApi.Versioning package, targetting net 4.6.1.

Following the documentation as described here: https://github.com/Microsoft/aspnet-api-versioning/wiki/New-Services-Quick-Start#aspnet-web-api-with-odata-v40

I added ApiVersioning:

            config.AddApiVersioning(o =>
            {
                o.AssumeDefaultVersionWhenUnspecified = true;
                o.DefaultApiVersion = new ApiVersion(1,0);
                o.ReportApiVersions = true;
            });

However the _MapVersionedODataRoutes_ extension method and _VersionedODataModelBuilder_ are both not available. I even went so far to decompile the DLL with ilspy and verified that those 2 things are not in the assembly.

I figured the docs are out of date and that these 2 things are no longer needed. 

However now swagger is dying.
The application does not properly detect that MyController and MyV2Controller are 2 different odata controllers, even though they target the same entityset type. When i disable api versioning, it works, so im guessing its some kind of routing or metadata issue.

I used the [ApiVersion] attribute to mark both controllers, but this does not seem to work. 

So am i forgetting something on the swagger side of things, and why is that extension method, and _VersionedODataModelBuilder_ gone ?

**Comment by commonsensesoftware** [comment]
It looks like you're missing some packages. For OData support, you need [Microsoft.AspNet.OData.Versioning](https://www.nuget.org/packages/Microsoft.AspNet.OData.Versioning). In fact, it depends on the Web API package so if you reference this package, you'll get them both. If you need/want Swagger support, then you'll also need the [Microsoft.AspNet.OData.Versioning.ApiExplorer](https://www.nuget.org/packages/Microsoft.AspNet.OData.Versioning.ApiExplorer) package.

I hope that helps.

**Comment by Danthar** [comment]
Thanks for the quick response. I definitely think that this is the issue at play there. Ill close this issue for now. Should i run into new problems ill open a new one. 👍

**Comment by commonsensesoftware** [comment]
Great! Glad you got things going. Thanks.
