### ISSUE TITLE
Error on the wiki

### ISSUE THREAD

**Issue by bdebaere** [Microsoft/aspnet-api-versioning#464]
The code below is missing from the second example at https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Versioning-with-OData#aspnet-core-and-odata-v40.
`
        var models = modelBuilder.GetEdmModels();`

**Comment by commonsensesoftware** [comment]
So right! I need wiki compilation and code analysis. =p

Fixed.

**Comment by commonsensesoftware** [comment]
The documentation was updated so all should be good again. Thanks for reporting it. Feel free to report any other discrepencies.
