### ISSUE TITLE
VersionByNamespaceConvention and Swagger

### ISSUE THREAD

**Issue by VeNoMiS** [Microsoft/aspnet-api-versioning#483]
I'm trying to integrate both.
But i receive a
```
System.NotSupportedException: 
HTTP method "POST" & path "v1/People" overloaded by actions - Test.Api.V2.Controllers.PeopleController.Post (Test.Api),
Test.Api.V1.Controllers.PeopleController.Post (Test.Api). 
Actions require unique method/path combination for Swagger 2.0. Use ConflictingActionsResolver as a workaround
```
My `Startup.cs` is equal to the [sample](https://github.com/Microsoft/aspnet-api-versioning/blob/master/samples/aspnetcore/SwaggerSample/Startup.cs) with 
` options.Conventions.Add(new VersionByNamespaceConvention());`

Any advice?

**Comment by commonsensesoftware** [comment]
I'm having to speculate here, but based on the error message, it looks like you're using inheritance. That's going to cause you grief. I know folks try and want to do it, but APIs cannot be _inherited_; it's purely an implementation convenience. Clearly, the POST action is being discovered from both v1 and v2.

If you can share your controller definitions (at least the relevant signatures), then I should be able to provide some suggestions.

**Comment by VeNoMiS** [comment]
```
 [ApiController]
    [Route("[controller]")]
    [Route("v{version:apiVersion}/[controller]")]
    public class PeopleController : ControllerBase
    {
        /// <summary>
        /// Gets a single order.
        /// </summary>
        /// <param name="id">The requested order identifier.</param>
        /// <returns>The requested order.</returns>
        /// <response code="200">The order was successfully retrieved.</response>
        /// <response code="404">The order does not exist.</response>
        [HttpGet("{id:int}")]
        [Produces("application/json")]
        [ProducesResponseType(typeof(Person), 200)]
        [ProducesResponseType(404)]
        public IActionResult Get(int id) => Ok(new Person() { Id = id, FirstName = "Foo", LastName = "Bar" });

        /// <summary>
        /// Places a new order.
        /// </summary>
        /// <param name="order">The order to place.</param>
        /// <returns>The created order.</returns>
        /// <response code="201">The order was successfully placed.</response>
        /// <response code="400">The order is invalid.</response>
        [HttpPost]
        [MapToApiVersion("1.0")]
        [Produces("application/json")]
        [ProducesResponseType(typeof(Person), 201)]
        [ProducesResponseType(400)]
        public IActionResult Post([FromBody] Person person)
        {
            person.Id = 42;
            return CreatedAtAction(nameof(Get), new { id = person.Id }, person);
        }
    }
```
Controller v2 is the same but different namespace

**Comment by commonsensesoftware** [comment]
Is it using _inheritance_?  It would seem may not.

Since you said they are the same, the issue is likely that you're using `[MapToApiVersion("1.0")]` in the POST action, which is unnecessary. This is a _copy & paste_ error causing the issue in v2.  If you called the v2 API, I won't even expect it to work/resolve.

**Comment by VeNoMiS** [comment]
Nevermind i'm an idiot i have MapToapi in both

**Comment by commonsensesoftware** [comment]
The infamous _Copy & Paste_ imp gets all us all from time-to-time. ;) No worries.
