### ISSUE TITLE
I try to add a "Content-Type" header to my HttpClient without success.

### ISSUE THREAD

**Issue by B4st13n** [Microsoft/aspnet-api-versioning#486]
Original question https://stackoverflow.com/q/55685234/196526

I try to add a "Content-Type" header using Media type versioning to my C# HttpClient without success. All my tentative are explained on [Stackoverflow](https://stackoverflow.com/q/55685234/196526). 

Here I will simply ask help for basic explanation about how to use versioning on C# client side with HpptClient when using Media Type versioning ?

**Comment by commonsensesoftware** [comment]
You can't (or at least _shouldn't_) use `Content-Type` when you don't send any content. Use the `Accept` header for `GET` and `DELETE` requests like this:

```c#
request.Headers.Accept.Add(MediaTypeWithQualityHeaderValue.Parse("application/json; v=2.0"));
```

**Comment by commonsensesoftware** [comment]
Did this solve your problem?
