### ISSUE TITLE
OData Routes return 404

### ISSUE THREAD

**Issue by vuchl** [microsoft/aspnet-api-versioning#488]
Hey!

I tried to follow these guides [here](https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Versioning-with-OData) and the [samples](https://github.com/Microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample) from this repo to create an OData RESTful API with Swagger integration. But I can not get it to work and my routes all return 404s.

Therefore I setup this replication repo: https://github.com/vuchl/ODataWithSwagger

Can someone point me what I am doing wrong?

Also what I do not get to work is this line: https://github.com/vuchl/ODataWithSwagger/blob/master/SwaggerDefaultValues.cs#L22

IntelliSense does not recognize this method call.

Cheers Sebastian!

**Comment by commonsensesoftware** [comment]
### Issue 1
This appears to be because you don't have any EDMs. API Versioning generates an EDM per API version. You should be able to easily confirm this by navigating to `api/$metadata` and seeing that the EDMX is empty.

To fix this, you need to either create a class that implements **IModelConfiguration** (which will be picked up by dependency injection) or define the model via the `VersionedODataModelBuilder.DefaultModelConfiguration` callback. These are outlined in the wiki in detail [here](../wiki/OData-Model-Configurations).

### Issue 2
The **IsDeprecated** extension method was introduced in the versioned [API Explorer 3.2.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/3.2.0), but you only referenced the OData API Explorer, which picking up 3.1.0 as the minimum, transitive dependency. You don't _have_ to update to achieve this functionality; it's merely a convenience. You either need add a direct, updated package reference to **Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer** 3.2.0+ or [this commit](../commit/1a1a6b6629ee0801d3334fbceeb8412aa3b7ce1f#diff-126080f6e7ca7df52a55a8ce543a4659) shows how to achieve the same result before the extension method was added.

**Comment by vuchl** [comment]
Hi @commonsensesoftware !

Thanks for pointing me to the right direction. I managed to get this working now. Another quertion:
I now have a Controller which has Select, Expand and Filter as the `AllowedQueryOptions` on a method.

In my `Configure` method I do **not** set
```
    ...
    routeBuilder.Select().Expand().Filter()
```

So now when I try to use any of the query options I get a "Filter is not allowed" message. But my Swagger is actually reporting them as being usable query paramters.

When I now add the line above and even add `OrderBy()`
```
    ...
    routeBuilder.Select().Expand().Filter().OrderBy()
```
the swagger frontend always gives me all 4 options as being available but when I try to use them I get the "Orderby is not allowed" message. 

How can i configer Swagger and OData to only pick up allowed methods but be able to have them available at all?

Regards Sebastian

**Comment by commonsensesoftware** [comment]
Support for the query options is relatively new. It's possible there's a bug. I'm sure not how much has changed, but looking at the example you provided, I do see `[EnableQuery]` on your API. Unless I'm mistaken, I though that configuring things using the `routeBuilder` configured the query options for the entire application, while attributes can be used on APIs and models. The intersection of the two is not entirely clear to me. I may have made a mistake.

Let me know if your example is up-to-date and what you expect the behavior to be. Then I'll be able to dig into this more.

Thanks

**Comment by vuchl** [comment]
@commonsensesoftware I tried to illustrate the problems in separate branches of my repo and update the READMEs:

- Edm Configuration fixed the 404: https://github.com/vuchl/ODataWithSwagger/tree/edm-configuration but but does not allow the use of `$Select`, `$Filter` or `$Expand` (see README of the branch for the error).
- adding the dependency injection: https://github.com/vuchl/ODataWithSwagger/tree/add-enable-di is not providing a difference though I am not really sure it actually should
- adding the global options for OData https://github.com/vuchl/ODataWithSwagger/tree/add-query-options-globally makes them work but the `EnableQueryAttribute` on the CompaniesController is not honored and all QueryOptions are listed in Swagger 

So right now I am stuck with either having a not working Swagger documention or a wrong Swagger doc.

Regards Sebastian

**Comment by commonsensesoftware** [comment]
That helps. I'll have to dig more. As I recall, the global settings supersede other settings. This is why although you reduced the settings in the attribute, they are still displayed.

I tried a couple of quick runs of the examples and it appears there may be issues outside of API Versioning.

### Issue 1
I see that Swagger is generating the following URL for _Orders_ 3.0:
`http://localhost:5000/api/Orders?api-version=3.0&%24select=select%3DcreatedDate`
which is incorrect. The query parameter characters should not be escaped. This lead to a 400 which reads: `The query specified in the URI is not valid. Term 'select=createdDate' is not valid in a $select or $expand expression.`.

However, if I issue the following request in PostMan or just the browser itself, it works fine:
`http://localhost:5000/api/Orders?api-version=3.0&$select=createdDate`

This suggests some part of Swashbuckle is encoding stuff when it shouldn't. I'm not sure how to turn that off - yet.

### Issue 2
The same action is decorated with `[EnableQuery( MaxTop = 100, AllowedQueryOptions = Select | Top | Skip | Count )]`, yet if you request `http://localhost:5000/api/Orders?api-version=3.0&$top=2` you get a 400 reading `The query specified in the URI is not valid. The limit of '0' for Top query has been exceeded. The value from the incoming request is '2'.` This appears to be a bug in OData or I haven't setup the action correctly. I would think that with the **Skip** query option enabled and **MaxTop** set, it should work just fine. I vaguely recall when adding this support that one path in OData uses `int?` for `$top` and another place uses `int` with a default value of `0`.

**Comment by vuchl** [comment]
I followed the escaping you mentioned a bit:
Hitting `https://localhost:5001/api/v1/Companies?$select=Id` from my repo gives me 2 results based on the  configuration:

1. including `routeBuilder.EnableDependencyInjection()` and `routeBuilder.Select().Expand().Filter().Count().OrderBy()` 
1.1. Swagger is displaying all available options on each action
1.2. the query from above succeeds
1.3. if I use the swagger UI I get `&%24count=false` auto appended
1.4. the escaped dollar signs still work
      `https://localhost:5001/api/v1/Companies?%24select=Id` and
      `https://localhost:5001/api/v1/Companies?$select=Id`
      both yield
```json
{
  "@odata.context": "https://localhost:5001/api/v1/$metadata#Companies(id)",
  "value": 
  [
    {
      "id": 0
    },
    {
      "id": 1
    }
  ]
}
```

2. commenting the above setup out in the `Configure` method yields the error message `The query specified in the URI is not valid. The property 'id' cannot be used in the $select query option.`

```json
{
  "error": {
    "code": "",
    "message": "The query specified in the URI is not valid. The property 'id' cannot be used in the $select 
 query option.",
    "details": [],
    "innererror": {
      "message": "The property 'id' cannot be used in the $select query option.",
      "type": "Microsoft.OData.ODataException",
      "stacktrace": "   at Microsoft.AspNet.OData.Query.Validators.SelectExpandQueryValidator.ValidateSelectItem(SelectItem selectItem, IEdmProperty pathProperty, IEdmStructuredType pathStructuredType, IEdmModel edmModel)\r\n   at Microsoft.AspNet.OData.Query.Validators.SelectExpandQueryValidator.ValidateRestrictions(Nullable`1 remainDepth, Int32 currentDepth, SelectExpandClause selectExpandClause, IEdmNavigationProperty navigationProperty, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.Validators.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.<>c__DisplayClass1_0.<OnActionExecuted>b__3(ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"
    }
  }
}
```

**Comment by vuchl** [comment]
@commonsensesoftware Is there something I can provide so we can get further here?

**Comment by commonsensesoftware** [comment]
Do you have a repro you're able to share? That would help me provided better guidance and ensure I use the same configuration you're using.

**Comment by vuchl** [comment]
@commonsensesoftware 

The first setup is checked into here: https://github.com/vuchl/ODataWithSwagger/tree/swagger-showing-all-odata-options

The second issue here: https://github.com/vuchl/ODataWithSwagger/tree/swagger-remove-global-odata-config

Thanks @commonsensesoftware for having a look at this.

**Comment by vuchl** [comment]
This can also be reproduced when you clone this repository, build it, and start the SwaggerOData Project. And before that edit the `v3/OrderController`s `Get` method to expand from
```
[EnableQuery( MaxTop = 100, AllowedQueryOptions = Select | Top | Skip | Count)]
```
to
```
[EnableQuery( MaxTop = 100, AllowedQueryOptions = Select | Top | Skip | Count | OrderBy | Filter )]
```

In the setup as it is in this repo, the $count is also not displayed in the swagger browser. When you add the OrderBy and Filter, the available options are also not represented in the swagger browser.

**Comment by commonsensesoftware** [comment]
There is definitely a bug where global settings are being overwritten in some cases.

The combination of OData query options is not entirely straight forward nor I do I think it's comprehensively documented anywhere. It's also not clear what happens when you mix styles of applying options - e.g. is it a union, intersection, or override?

The goal of API Explorer is apply them in order as:

1. By explicit convention (e.g. though the API Explorer for things that OData does expose)
    a. This is also the case for imperative options/valiation performed in actions
2. Global query settings
3. Action query settings
4. Model bound query settings

Only an explicit setting at a lower level is meant to override a previous value. I'm honestly not sure whether this is the same order that OData actual evaluates things, but it seems the most rational. I wouldn't be surprised if there are inconsistencies in how OData handles 2-4.

I'm sure anyone will find this specific comment since the title suggests something different, but if anyone knows or can link to the documentation for how query options should be resolved, it will help ensure things get fixed correctly. The API Explorer needs to document the options the way OData expects as opposed to what logically may make sense.

**Comment by vuchl** [comment]
Hey @commonsensesoftware !

Thanks for putting so much effort into this!

I was able to get it working with the new version and some more explicit model configuration (adding Count, Page, Filter, OrderBy attributes), removing configuration from the `Startup.ConfigureServices()`.

I will try to see if it fints my scenario now. Thanks man!
