### ISSUE TITLE
how to find the latest version down

### ISSUE THREAD

**Issue by Varorbc** [microsoft/aspnet-api-versioning#498]
API version Support:
1.1
2.0

How to achieve the latest version (v2) less than the v3 version when requesting /api/v3/values instead of returning UnsupportedApiVersion

**Comment by commonsensesoftware** [comment]
This will be more difficult to achieve using the URL segment method as you cannot have an _optional_ segment anywhere in the path except at the end.

First, you'd have to have double routes, one of which has a default, _floating_ route. For example:

```c#
[ApiVersion("2.0")]
[Route("api/[controller]")]
[Route("api/v{version:apiVersion}/[controller]")]
```

Second, you'll have to allow implicit versioning (e.g. the client doesn't have to specify) by configuring:

```c#
options.AssumeDefaultVersionWhenUnspecified = true;
```

This is required for all versioning methods.

Finally, to select the specific version that you want, you'll need a custom version selector. This would be similar, but slightly different from the **CurrentImplementationApiVersionSelector**. Something like:

```c#
public class CurrentMinusOneApiVersionSelector : IApiVersionSelector
{
    readonly ApiVersioningOptions options;

    public CurrentMinusOneApiVersionSelector( ApiVersioningOptions options )
    {
        Arg.NotNull( options, nameof( options ) );
        this.options = options;
    }

    public virtual ApiVersion SelectVersion( HttpRequest request, ApiVersionModel model )
    {
        switch ( model.ImplementedApiVersions.Count )
        {
            case 0:
                return options.DefaultApiVersion;
            case 1:
                var version = model.ImplementedApiVersions[0];
                return version.Status == null ? version : options.DefaultApiVersion;
        }

        var currentMinusOne = model.ImplementedApiVersions
                                   .Where( v => v.Status == null )
                                   .OrderByDescending( v => v )
                                   .Skip( 1 )
                                   .FirstOrDefault();

        return currentMinusOne ?? options.DefaultApiVersion;
    }
}
```

Then you hook it up to the options a la:

```c#
options.ApiVersionSelector = new CurrentMinusOneApiVersionSelector( options );
```

With all this in place and configured, a request to `api/values` will match v2 (assuming 1, 2, 3) and `api/v2/values`.

I hope that helps.

**Comment by Varorbc** [comment]
> Second, you'll have to allow implicit versioning (e.g. the client doesn't have to specify) by configuring:
> 
> ```cs
> options.AssumeDefaultVersionWhenUnspecified = true;
> ```

Translated by Google

Thank you for your reply, this does not seem to be what I want, because it requires the client to specify the version number to work, but I now specify the v3 version number, but can not find v3, need to request v2.

I will describe my problem in detail. I have two Apis, a and b. They also support the v1 version. At this time, there are new requirements. I need to add the v2 version of a. At this time, I do not add the v1 version of b. We tell the client that need to request the v2 version of the Api. At this time, the client will request the v2 version of a, b instead of telling the client to request the v2 version of the a, v1 version of b, which will undoubtedly increase the complexity of the client.

**Comment by commonsensesoftware** [comment]
OK ... I see. In that case, forget everything I just said. What you are trying to achieve is what I call _version symmetry_ (e.g. you want all of your APIs to have the same version).

The way you go about setting up versioning symmetry is largely an implementation detail and preference. There are several ways to do it and the client never knows anything about how it's implemented.

Here's one of many, many possibilities. I'll use namespaces for the sake of keeping the type names the same, but that has no bearing on anything. You can put stuff in the same namespace and/or organize things however you want.

```c#
namespace My.Api.Controllers.V1
{
  [ApiVersion("1.0")]
  [Route("api/v{version:apiVersion}/[controller]")]
  public class AController : ControllerBase
  {
    [HttpGet]
    public IActionResult Get() => Ok();
  }

  [ApiVersion("1.0")]
  [ApiVersion("2.0")]
  [Route("api/v{version:apiVersion}/[controller]")]
  public class BController : ControllerBase
  {
    [HttpGet]
    public IActionResult Get() => Ok();
  }
}

namespace My.Api.Controllers.V2
{
  [ApiVersion("2.0")]
  [Route("api/v{version:apiVersion}/[controller]")]
  public class AController : ControllerBase
  {
    [HttpGet]
    public IActionResult Get() => Ok();
  }
}
```

Here's how things map:

| URL | Controller |
| ---- | ----------- |
| api/v1/a | V1.AController |
| api/v2/a | V2.AController |
| api/v1/b | V1.BController |
| api/v2/b | V1.BController |

Don't let the _code_ side of things confuse you. How things map in code is orthogonal and largely irrelevant from the perspective of the API (which is HTTP). It's perfectly fine to map multiple versions to a single type; especially if nothing has changed. I call this _version interleaving_. In the simplest form, a controller implements multiple API versions; however, it's possible to have different actions map to specific API versions. It's kind of like API overrides/overloads - if there was such a thing.

Can this become a manageability issue? Yes - yes it can. That's part of the cost of version symmetry. Another approach is to use the _Copy and Paste_ method where each folder is a namespace that contains everything for that version. When a new version is created the previous version's folder is copied, pasted, and updated. This is common enough that there is now a built-in convention for it. You can see what it looks like in the [Version By Namespace](../tree/master/samples/aspnetcore/ByNamespaceSample) example.

The method you choose is whatever makes sense to you from a management point.

I hope that helps.

**Comment by Varorbc** [comment]
Thank you for providing me with a solution. It seems that this applies when there is less Api. If I have 100 Api, but only one of them needs to be upgraded to V2, then the other 99 Apis need to add the V2 version. Is there a global management method?

**Comment by commonsensesoftware** [comment]
There is - sort of. The term _global_ would be a misnomer. You can use the _conventions_ support to apply conventions to all your APIs. There are several built-in conventions or you can author your own. The approach to choose depends on your environment and how you plan to implement things. For example, if you're using a single controller type for all versions, then applying convention that adds versions to all controllers is simple. On the other hand, if you split the implementation across different controllers, then the convention cannot be blindly, universally applied or you'll end up with duplicates. 

I'll reiterate that there many ways to achieve this and I can't say there is one _best_ approach. Here's a few ideas:

- Use conventions
- Use custom attributes
- Organize by namespace
- Organize by controller per API

Ultimately, version symmetry can be convenient for clients, but comes at a management cost for service authors. If you really have 100+ APIs, then consider organizing the APIs into smaller _bounded contexts_ that have version symmetry within that context. Azure, for example, does not use the same version for all APIs, but has version symmetry within a particular product/service/API. If you all your APIs haven't to have universal symmetry, that's great, but by breaking things up into smaller pieces you ease the management cost. I would only consider this for an external API. For enterprise scenarios, I've found it easier to let each service and it's version evolve independently.

I hope that helps.

**Comment by Varorbc** [comment]
I hope you can understand that my English is too poor.

I think this place is the best in this way. It shouldn’t work only if the client doesn’t specify a version number, but it should also work if the version is not found.

https://github.com/microsoft/aspnet-api-versioning/blob/1a1a6b6629ee0801d3334fbceeb8412aa3b7ce1f/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs#L193-L199

```csharp
if ( requestedVersion == null ||
     Options.AssumeDefaultVersionWhenUnspecified)
{
     context.RequestedVersion = requestedVersion = ApiVersionSelector.SelectVersion( 
     context.HttpContext.Request, context.AllVersions );
}
```

I hope you can adopt my suggestion.



In addition, if it is to provide a behavior processing provider, not a provider of error information, will it be better?

https://github.com/microsoft/aspnet-api-versioning/blob/c8d7ff7c4a9012c389a98c36d56e833e240e8346/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs#L277-L294

**Comment by commonsensesoftware** [comment]
### Suggestion 1
API Versioning relies on having discrete API versions to ensure it has deterministic behavior. The one and only exception is the _default_ or _initial_ version, which is meant to ease the transition to versioning and/or grandfather in existing services. In this context, only you know what the default version should be. There are several out-of-the-box policies to handle this such as taking a constant version, the lowest version, the highest version, and so on. You can also define your own policy though a custom **IApiVersionSelector**, which is the only scenario where this is currently used.

This policy, however, does **not** apply when an API version is not found. When it's not found, that means it does not exist; at least from the server's perspective. If that wasn't the case, you won't be able to ever remove an API version, which naturally happens over time.

Providing hooks to control this behavior would add significant complexity on your part and diminish much of the intrinsic value API versioning provides. Your job is to define/describe API versioning metadata and it's API versioning's job to enforce it. Technically, there are ways you can do this today, but it will take you down a very deep rabbit hole. I don't recommend it.

If you provide some additional context about what you're thinking for version management or specific challenges, I may be able to give more guidance.  There are more supported options to provide API version metadata than you can probably imagine.

### Suggestion 2
I _think_ what you're asking here is whether you are able to hook into the error response pipeline. The answer is - yes. You change this by creating a custom **IErrorResponseProvider** or extending the default provider. You can only change the response. You cannot change the execution behavior. You wire it up in the options a la: `options.ErrorResponses = new MyCustomErrorResponses();`.

API Versioning requires a single API version to be matched. In the scenario you've outline, a request is ambiguous because the client has specified multiple, different API versions. If you want to alter this behavior, one approach would be to implement a custom **IApiVersionReader** that understands how to deal with the ambiguity. Requesting ambiguous API versions should be pretty rare.

------------------
I hope that helps. I'm happy to answer more questions or provide additional guidance.

**Comment by Varorbc** [comment]
> This policy, however, does **not** apply when an API version is not found. When it's not found, that means it does not exist; at least from the server's perspective. If that wasn't the case, you won't be able to ever remove an API version, which naturally happens over time.

If the adjustment the `AssumeDefaultVersionWhenUnspecified ` option is not enabled also works, so that there is better scalability, i can write the corresponding logical processing version is removed or does not exist, and `IApiVersionSelector ` as the name suggests should be the version selector, and should not be in the Effective when the `AssumeDefaultVersionWhenUnspecified ` option is enabled

**Comment by commonsensesoftware** [comment]
Did this ulimtately answer your question or was there something more? It seems as though this issue may be resolved. Thanks.

**Comment by Varorbc** [comment]
@commonsensesoftware 
> This policy, however, does **not** apply when an API version is not found. When it's not found, that means it does not exist; at least from the server's perspective. If that wasn't the case, you won't be able to ever remove an API version, which naturally happens over time.

If the adjustment the `AssumeDefaultVersionWhenUnspecified ` option is not enabled also works, so that there is better scalability, i can write the corresponding logical processing version is removed or does not exist, and `IApiVersionSelector ` as the name suggests should be the version selector, and should not be in the Effective when the `AssumeDefaultVersionWhenUnspecified ` option is enabled

**Comment by commonsensesoftware** [comment]
Is there a question in there?

Your suggestion above does not work in this context. If the API version is `null`, then it has not been specified. If, and only if, the configuration allows an implicit API version (e.g. it's `null`), then the **IApiVersionSelector** can be used to determine what the API version should be. If the client sends an API version, the **IApiVersionSelector** absolutely cannot choose something else. The server's responsibility to fulfill the match or indicate to the client that it cannot be matched.

If you truly wanted this type of behavior, you'd be better off using a redirect via 301/302 or 307/308. Even that has issues though because unless things are the same response, there's no guarantee the client understands the response. Assuming that anything is backward compatible to a client is a fallacy.

It sounds like you have a very specific behavior you want. You can achieve you goals simply by subclassing the **ApiVersionActionSelector**, changing the behavior, and replacing it in your service configuration.

**Comment by Varorbc** [comment]
> You can achieve you goals simply by subclassing the ApiVersionActionSelector, changing the behavior, and replacing it in your service configuration.

![image](https://user-images.githubusercontent.com/5714438/60365736-23afdb00-9a1c-11e9-8136-1759e3b4a958.png)

I think this place is the best in this way. It shouldn’t work only if the client doesn’t specify a version number, but it should also work if the version is not found.

https://github.com/microsoft/aspnet-api-versioning/blob/1a1a6b6629ee0801d3334fbceeb8412aa3b7ce1f/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs#L193-L199

```csharp
if ( requestedVersion == null ||
     Options.AssumeDefaultVersionWhenUnspecified)
{
     context.RequestedVersion = requestedVersion = ApiVersionSelector.SelectVersion( 
     context.HttpContext.Request, context.AllVersions );
}
```

**Comment by commonsensesoftware** [comment]
You're certainly entitled to your opinion. Aside from breaking existing behaviors, this approach would be counter to the design principles of the project. The matching of API versions is discrete. Ranges, fallbacks, and other concepts are intentionally not supported out-of-the-box. If a client asks for v3, then the only answer the server should give is v3 or 400 (e.g. doesn't exist). There's no scenario were a client asks for v3 and gets v2.  **You** can enable that capability in your project, but that's not something that is going to be an intrinsic capability.

Another, arguably more straight forward, way for you to implement your behavior is to define a custom [IApiVersionRoutePolicy](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/IApiVersionRoutePolicy.cs). You _could_ even extend the built-in [DefaultApiVersionRoutePolicy](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs). You need only override [DefaultApiVersionRoutePolicy.OnUnmatched](blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs#L115). In this method, you can get the requested API version, matching candidates, and find a suitable fallback. If you cannot find a fallback, then default to the base implementation.

I'm not a fan of this approach, but it will allow you to get the behavior you want. You need only update the **IApiVersionRoutePolicy** service in your configuration.

**Comment by Varorbc** [comment]
I feel that you need to provide a custom implementation that doesn't find the api version, instead of making the user feel helpless.

i  update the `IApiVersionRoutePolicy ` service in my configuration,but I found that I didn't enter this method. Is it wrong for me?

`services.Replace(ServiceDescriptor.Singleton<IApiVersionRoutePolicy, Class1>());`

**Comment by commonsensesoftware** [comment]
What type of routing are using? I forgot that there are two types of routing now. >_< If you're using the new _Endpoint Routing_, then things will be different. Let me know and I can probably put together an example for.

I'm only one guy and it's simply impossible to make a framework that will be everything to everyone. I've ensured the 80% is covered with well-established and proven best practices. For everything else, I provide hooks to change things. I provide numerous examples for customizations, but there are limits on the capacity I have.

Thanks for you patience and understanding.

**Comment by Varorbc** [comment]
Yes, I use endpoint routing, so how to solve it?

Thank you for your patience, and I hope my problem can be solved as soon as possible.

**Comment by commonsensesoftware** [comment]
This should get you what you want:

```c#
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.AspNetCore.Mvc.Versioning;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Routing.Matching;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Microsoft.AspNetCore.Mvc.Versioning.ApiVersionMapping;

public sealed class PreviousApiVersionMatchPolicy : MatcherPolicy, IEndpointSelectorPolicy
{
    public PreviousApiVersionMatchPolicy(
        IOptions<ApiVersioningOptions> options,
        IReportApiVersions reportApiVersions,
        ILoggerFactory loggerFactory )
    {
        DefaultMatcherPolicy = new ApiVersionMatcherPolicy(
            options,
            reportApiVersions,
            loggerFactory );
        Order = DefaultMatcherPolicy.Order;
    }

    private ApiVersionMatcherPolicy DefaultMatcherPolicy { get; }

    public override int Order { get; }

    public bool AppliesToEndpoints( IReadOnlyList<Endpoint> endpoints ) =>
        DefaultMatcherPolicy.AppliesToEndpoints( endpoints );

    public async Task ApplyAsync(
        HttpContext httpContext,
        EndpointSelectorContext context,
        CandidateSet candidates )
    {
        var requestedApiVersion = httpContext.GetRequestedApiVersion();
        var highestApiVersion = default( ApiVersion );
        var index = -1;

        // evaluate the default policy
        await DefaultMatcherPolicy.ApplyAsync( httpContext, context, candidates );

        for ( var i = 0; i < candidates.Count; i++ )
        {
            if ( candidates.IsValidCandidate( i ) )
            {
                // we're done if there are any valid candidates
                return;
            }

            var candidate = candidates[i];
            var action = candidate.Endpoint.Metadata?.GetMetadata<ActionDescriptor>();

            if ( action == null )
            {
                continue;
            }

            var model = action.GetApiVersionModel( Explicit | Implicit );
            var maxApiVersion = model.DeclaredApiVersions.Max();

            // remember the candidate with the next highest api version
            if ( maxApiVersion < requestedApiVersion &&
               ( highestApiVersion == null || maxApiVersion > highestApiVersion ) )
            {
                highestApiVersion = maxApiVersion;
                index = i;
            }
        }

        if ( index < 0 )
        {
            return;
        }

        // if there's a match:
        //
        // 1. make the candidate valid
        // 2. clear any existing endpoint (ex: 400 response)
        // 3. set the requested api version to the resolved value
        candidates.SetValidity( index, true );
        context.Endpoint = null;
        httpContext.Features.Get<IApiVersioningFeature>().RequestedApiVersion = highestApiVersion;
    }
}
```

Then you have to update your service configuration like this:

```c#
// IMPORTANT: must be configured after AddApiVersioning
services.Remove( services.Single( s => s.ImplementationType == typeof( ApiVersionMatcherPolicy ) ) );
services.TryAddEnumerable( ServiceDescriptor.Singleton<MatcherPolicy, PreviousApiVersionMatchPolicy>() );
```

In the **BasicExample**, the _Values_ API only supports `1.0` and `2.0`. If you request `api/values?api-version=3.0`, you'll get the response for `2.0`. You can change the logic further to suit your needs.

**Comment by Varorbc** [comment]
Wow, this solution is great. another issue is how to report the version currently in use. I found that the `ReportApiVersions` options is a supported version of the report.

**Comment by commonsensesoftware** [comment]
There isn't anything out-of-the-box that would facilitate that because the expectation is that you get a response that matches the API version you asked for; however, you can use a custom **ActionFilterAttribute** (you can review how **ReportApiVersionsAttribute** itself works) or middleware if you need the behavior to be common. 

To get the current/resolved API version, you simply use the `HttpContext.GetRequestedApiVersion` extension method. This is the short form of `httpContext.Features.Get<IApiVersioningFeature>().RequestedApiVersion`. This is also backed by model binding, so you can get the current API version simply by declaring a `ApiVersion apiVersion` parameter in your controller actions. I presume you'd use this information to write a custom header or something in the response.

I hope that helps.

**Comment by Varorbc** [comment]
Thank you very much. I will close this issue

**Comment by Varorbc** [comment]
@commonsensesoftware how to achieve the same implementation on asp.net?
