### ISSUE TITLE
$expand parameter being added to ODataControllers Swagger output

### ISSUE THREAD

**Issue by davidyee** [microsoft/aspnet-api-versioning#514]
### Issue summary

We've been on `Microsoft.AspNetCore.OData.Versioning` 3.1.0 and `Microsoft.AspNetCore.OData.Versioning.ApiExplorer` 3.1.1 but we noticed after upgrading to 3.2.0 for both packages that some of our OData endpoints that aren't defined to have an OData `$expand` parameter setup are being added to our Swagger generated output. 

### Further Details

I'm not sure if this is an issue directly related to changes introduced in the new 3.2.0 versions or if it is a side-effect that occurs in conjunction with our Swagger packages (we have package references to `Swashbuckle.AspNetCore`, `Swashbuckle.AspNetCore.Annotations`, `Swashbuckle.AspNetCore.Swagger`, `Swashbuckle.AspNetCore.SwaggerGen`, `Swashbuckle.AspNetCore.SwaggerUI` 4.0.1); however, downgrading backwards to 3.1.0 and 3.1.1 aspnet api versioning packages seems to resolve the issue.

Typically, as [per the documentation in this project's wiki](https://github.com/microsoft/aspnet-api-versioning/wiki/OData-Model-Configurations), our ODataControllers are configured through implementing `IModelConfiguration` such as:

```csharp
public class MyModelConfiguration : IModelConfiguration
{
	public void Apply(ODataModelBuilder builder, ApiVersion apiVersion)
	{
		if (apiVersion.MajorVersion >= 1)
		{
			var entityType = builder.EntitySet<MyModel>(nameof(MyModel)).EntityType;
			entityType.Select().OrderBy().Filter().Count().Page(ApiDefaultLimits.MaxTop, ApiDefaultLimits.PageSize);
		}
	}
}
```

**Note that in the above model configuration we do not define `Expand()` support.**

Our ODataControllers are configured with a GET method such as the following:

```csharp
[ProducesResponseType(typeof(ODataValue<IEnumerable<MyModel>>), StatusCodes.Status200OK)]
[HttpGet]
[ODataRoute]
public override IQueryable<MyModel> Get()
{
	return DbContext.Set<MyModel>().AsQueryable();
}
```

**Comment by commonsensesoftware** [comment]
There aren't any dependencies or side-effects with regard to Swashbuckle. All of this information is provided via the API Explorer. For completion, you don't happen to have any query options defined at the model level do you?

There's a chance that there's a bug. Testing all possible permutations is quite complex and time consuming. There might be a regression with respect to the `$expand` operator. I'll take a look based on your example.

Thanks

**Comment by davidyee** [comment]
Thanks for the update Chris. If I understand your question correctly as referring to [model-bound attributes](https://github.com/microsoft/aspnet-api-versioning/wiki/OData-Query-Options#attribute-model): no, we do not have any additional query option definitions on our models.

**Comment by commonsensesoftware** [comment]
After looking at this, I initially missed that you _are_, in fact, using _Model-Bound_ query options. The example that you provided demonstrates how you apply them using the fluent interface provided by the EDM builder.

I tried to reproduce the scenario by applying your _Model-Bound_ configuration to the sample project. I saw `$select` appear, but not `$expand`. Is there any chance you have `routeBuilder.Expand()` enabled or configured in your `app.UseMvc( routeBuilder => { ... } )` setup?

The union of these configurations is not entire clear nor do I feel documented; at least not well. My understanding is that the global level specified in `app.UseMvc` is the default applied to everything. Additional capabilities can be enabled via _Model Binding_ using attributes or the fluent interface. These settings, however, typically turn things on not off, but there does seem to be a way to override the global, default setting. Specifying `entityType.Expand(SelectExpandType.Disabled)` _should_ do the trick.

It's also entirely possible that I have the rules wrong. There are many, many combinations and I've been finding some incongruencies with the configuration versus what OData ends up allowing. The rules are applied as follows in order of precedence:

1. Global query settings
2. Action query settings (e.g. `[EnableQuery]`)
3. Model-Bound query settings by attribute and/or fluent interface
4. Explict conventions specified in the API Explorer options that cannot be specified by other means

Hopefully that gives you a few clues as to where things may be misconfigured or you can help confirm where something is wrong. It's also worth nothing that if \#4 above is misconfigured, it will show up in a Swagger document, but has no runtime effect (e.g. it can say that `$expand` is supported, but it will fail if requested).

**Comment by davidyee** [comment]
Thanks Chris your explanation of the rule precedence is very helpful. 

I took a second look and we do indeed have a global query setting as you suspected:

```csharp
app.UseMvc(routeBuilder =>
{
    routeBuilder.Select().Expand().OrderBy().MaxTop(ApiDefaultLimits.MaxTop).Count().Filter();

    var oDataRoutes = routeBuilder.MapVersionedODataRoutes("odata", "api/v{version:apiVersion}/odata", models,
        configureAction =>
        {
            foreach (var edmModel in models)
            {
                configureAction
                    .AddDefaultODataServices()
                    .AddService(ServiceLifetime.Singleton, s => edmModel)
                    .AddService<ODataUriResolver>(ServiceLifetime.Singleton,
                        s => new AlternateKeysODataUriResolver(edmModel) { EnableCaseInsensitive = true });
            }
        });

    routeBuilder.EnableDependencyInjection();
});
```

It also does fail when we attempt to use `$expand`; however, the models we observed `$expand` being added are very simple and they just so happen to not have any navigation properties to fully verify the runtime effect after upgrading the `Microsoft.AspNetCore.OData.Versioning` packages.

**Comment by commonsensesoftware** [comment]
Good news. Armed with all of this information, were you able to refactor and get something working the way you want?

**Comment by commonsensesoftware** [comment]
Seems like you were able to resolve this issue or at least get to working state. If weren't able to solve it or have additional questions, feel free to come back or reopen the issue. Thanks.
