### ISSUE TITLE
Getting a list of versions on .Net Framework

### ISSUE THREAD

**Issue by PDRDaveF** [microsoft/aspnet-api-versioning#518]
Due to a third party requirement, I am having to use framework and would like to list out all API versions.

We currently do this in core by injecting IApiVersionDescriptionProvider and querying it, however not sure how to go about the same in Framework using Autofac as DefaultApiVersionDescriptionProvider also requires injected values.

Any pointers would be appreciated.

Thanks in advance

**Comment by PDRDaveF** [comment]
Thanks for the response @commonsensesoftware - my situation is that we have a .NET 4.7 Web API 2 solution, and need to version it along the lines we do with out Core ones. We can't have it in Core due to third party DLLs.

So ideally we want inject IApiVersionDescriptionProvider into the controller, and then loop through ApiVersionDescriptions and emit the groupname, as we do with Core.

Easy enough in Core as the middleware injects what we need, however in Framework we need to use the likes of Autofac to register the dependencies. What you've pointed me towards should be of help, thank you.

**Comment by commonsensesoftware** [comment]
Oh ... I see. I didn't realize this was Web API. The API Explorer API is quite different between Web API and Core. The **IApiVersionDescriptionProvider** doesn't exist in Web API, but don't fret, you can still achieve your goal. In addition, Web API doesn't provide any type of dependency injection out-of-the-box; therefore, you don't need Autofac or any other DI framework for things to work.

After you've brought in the package for Web API, the setup would look like this:

```c#
var apiExplorer = configuration.AddVersionedApiExplorer();
var apiVersions => apiExplorer.ApiDescriptions.Select(group => group.ApiVersion).ToArray();

// TODO: loop through all API versions
```

The API descriptions are already collated and sorted by API version if you just want to loop through everything. If you haven't already, you might want to look at the [Web API Swagger example](../blob/master/samples/webapi/SwaggerWebApiSample/Startup.cs#L37) for an example of end-to-end usage.

I hope that helps.

**Comment by PDRDaveF** [comment]
I've probably not explained myself very well @commonsensesoftware - we need to emit a list of versions from a controller.

We're using Autorest to create versioned SDKs, so it needs a list of versions so it can then go get the definitions from swagger/docs/vX, swagger/docs/vY, swagger/docs/vZ, etc. and create our versioned SDKs.

By looping through the versions and emitting them as an array of strings, if we create a new version the process will automatically create a new SDK to consume it as part of the build chain.

**Comment by commonsensesoftware** [comment]
You can still that in a controller without the need for DI. Here's a simple example you can use as a starting point:

```c#
[ApiVersionNeutral]
[RoutePrefix("api/versions")]
public class VersionsController : ApiController
{
    [HttpGet]
    [Route]
    public IHttpActionResult Get()
    {
        var apiExplorer = (VersionedApiExplorer) Configuration.Services.GetApiExplorer();
        var apiVersions = apiExplorer.ApiDescriptions.Select(group => group.ApiVersion).ToArray();

        // TODO: real processing
        return Ok(apiVersions.Select(version => version.ToString());
    }
}
```

Now a request to `GET api/versions` will list all versions in the application. Obviously you can change things to suite your needs.

**Comment by PDRDaveF** [comment]
Fantastic! Thank you @commonsensesoftware for that, works a treat :)
