### ISSUE TITLE
OData APIExplorer route template with KeyAsSegment should not quote strings

### ISSUE THREAD

**Issue by Rob4001** [microsoft/aspnet-api-versioning#526]
Related to #502 
Paths being generated for our Swagger docs are including paths such as /API/v1/Resource/'{key}'/SubResource

While the server side routes are /API/v1/Resource/{key}/SubResource

Creating the issue where swagger "try it out" includes the quotes which will be passed to the controller as "'key'". 

It looks like the ODataRouteBuilder has the functionality to bypass quotation when KeyAsSegment is set to true but is not passing through to ExpandParameterTemplate when only a single (or first) key

Thanks in advance, really appreciate the library

**Comment by commonsensesoftware** [comment]
Doh! Thought I fixed this. Looks like there are a couple of cases where the wrong overload is used. This should be a quick fix.

I've been trying to find a comprehensive breakdown of what the _Key As Segment_ rules are, but I've never found them. Do you happen to know? I've mostly been going off of knowledge of the protocol and occassionally spelunking the OData source code.

Here's things I've been looking for:

- Are composite keys supported?
  - If so, how? `/entity-set/{key1}/{key-n}`?
- Do key segments **never** use OData URL encoding? (ex: string, GUID, binary, duration, geometry, geography, etc)
- Do the _Key As Segment_ rules apply to non-entity sets, such as unbound actions or functions?

If you happen to have or know of a sample project that uses this setup, that would be useful too. I feel like every time I've tried to set it up myself it ends up not working as expected. Thanks.

**Comment by commonsensesoftware** [comment]
FYI ... the patch for this has been published.
