### ISSUE TITLE
multi-part keys not supported when using keys as segments

### ISSUE THREAD

**Issue by Discjoggy** [microsoft/aspnet-api-versioning#538]
This issue relates to #533. I am still missing a working example with the use of slashes and multi-part keys. I read the official specs and found [here](http://docs.oasis-open.org/odata/odata/v4.01/csprd05/part2-url-conventions/odata-v4.01-csprd05-part2-url-conventions.html#sec_KeyasSegmentConvention) an example of the usage of multi-part keys (see example 26):

```
https://host/service/OrderItems(OrderID=1,ItemNo=2) 
https://host/service/OrderItems/1/2
```

So this tells us how the route template must be specified, but I was not able to create a working example of the last part. Let's reuse the working example of the related issue:

**Model with two fields**

```cs
public class Doublekey
{
    public int Id { get; set; }
    public string Customer { get; set; }
}
```

**Controller**

```cs
[ApiVersion( "1.0" )]
[ODataRoutePrefix( "Doublekey" )]
public class DoublekeyController : ODataController
{
    [ODataRoute( "(Id={key},Customer={cust})")]
    [ODataRoute( "{key}/{cust}")] // should not be nessecary but it is not working anyway
    [EnableQuery( AllowedQueryOptions = AllowedQueryOptions.Select )]
    public SingleResult<Doublekey> Get([FromODataUri] int key, [FromODataUri] string cust)
        => SingleResult.Create(new[] { new Doublekey {Id = key, Customer = cust } }.AsQueryable());
}
```

**Configuration**

```cs
var doublekey = builder.EntitySet<Doublekey>("Doublekey").EntityType.HasKey(o => new { o.Id, o.Customer });
```

Is it relevant to specify a route or should this automatically translated?

**Comment by commonsensesoftware** [comment]
I just heard back from the OData team. I was going to cite the specification as it is apparently in there - now, but you've already found the link. However, it's important to note that this specification is for the **4.01** version of the protocol. Only 4.0 has been supported up to this point.

In short, this is the information I got:

>_...Because of this weirdness, and because we implemented key-as-segment before it was added to the protocol, in our libraries we currently require the use of parens-style access for multipart keys. Now that 4.01 defines rules around use of key-as-segment for multipart keys we could add that limited support to our libraries, but so far services have been content using the cleaner parens style syntax for multipart keys..._

Ultimately, this means that the protocol official supports composite keys using the _Key as Segment_ method with slashes, but the OData implementation libraries do **not** support it yet. I presume this is on the OData team's roadmap to implementation, but I don't really know. You'd have to search and/or poke at them on their repo.

With respect to API Versioning, I'd been guessing that this is what the convention would so things _should_ just work whether this functionality is enabled.

**Comment by Discjoggy** [comment]
Thanks for the fast response. Well then I will move to the official OData repository and close this issue.
