### ISSUE TITLE
Latest preview of .NET Core 3.0 hitting duplicate route names with URL versioning

### ISSUE THREAD

**Issue by theezak** [microsoft/aspnet-api-versioning#539]
Hi,

Latest preview of .NET Core now hits the following issue:
`Action: 'WebApplication2.Controllers.V2_1.DefaultController.Get (WebApplication2)' - Template: 'api/v{version:apiVersion}/Default/{id}'
Action: 'WebApplication2.Controllers.V2_1.DefaultController.Get (WebApplication2)' - Template: 'api/Default/{id}'
Action: 'WebApplication2.Controllers.V1_1.DefaultController.Get (WebApplication2)' - Template: 'api/v{version:apiVersion}/Default/{id}'
Action: 'WebApplication2.Controllers.V1_1.DefaultController.Get (WebApplication2)' - Template: 'api/Default/{id}'
Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory.Flatten<TResult>(ApplicationModel application, Func<ApplicationModel, ControllerModel, ActionModel, SelectorModel, TResult> flattener)`

It appears that a flattener was introduced that requires unique templates before the ApiVersionExplorer can fill in the versions ?

**Comment by commonsensesoftware** [comment]
What's the specific error that you're getting? Just to confirm, you are talking about **route names** and not **route templates**, yes? Route names have never been version-aware. If want to use the name within the same controller, your best bet is to use one of the local resolution methods such as **CreatedAtAction**. If you're trying to resolve a route by name externally, then you'll have to give the route a name with some type of convention; for example, **DefaultV1.1** and **DefaultV2.1**.

**Comment by theezak** [comment]
It turned out to be a duplication of the version attributes. Changes for the versioning were actually easy to deal with compared to for example Swashbuckle  : ). Is there an expected date for the final 4.0 version of this package to be released? Nuget is still giving me preview-8.

**Comment by commonsensesoftware** [comment]
It's still preview, but I'm working on getting it out ASAP.

Sounds like you were ultimately able to resolve your problem. Feel free to come back if you have additional questions.

Thanks.
