### ISSUE TITLE
SwaggerODataSample error

### ISSUE THREAD

**Issue by spaasis** [microsoft/aspnet-api-versioning#542]
Hi, and thanks for the brilliant library!

I was studying the SwaggerODataSample and noticed that doing a GET to `/api/Orders?api-version=2.0&%24count=false` (default values from swagger) returns an error:

> The query specified in the URI is not valid. The entity set 'Orders' cannot be used for $count.

The query works fine if we remove `Count` from the `AllowedQueryOptions`.

I don't yet know enough about OData to propose a fix, so just a heads up this time.

**Comment by spaasis** [comment]
On a sidenote, when I navigate to V2 on swagger and click either of the `Order`-methods, both of them open/close. The same happens with `People`. Does anyone else see this behavior?

**Comment by commonsensesoftware** [comment]
Apologies for the long delay in the response.

First, you likely need to enable the global `$count` operation in the setup via `routeBuilder.Count()`. It's not clear why it doesn't work when it's enabled at the action level. I suspect it's a bug in OData.

The Swagger examples use Swashbuckle. Oddities in the UI behavior would need to be directed in their repo. I'll be updating the versions shortly and I suspect that issue may have been fixed.

I hope that helps. Thanks.

**Comment by spaasis** [comment]
Added a PR https://github.com/microsoft/aspnet-api-versioning/pull/567  to fix the bug, and can confirm that the UI stuff is fixed in at least some later version of Swashbuckle. Closing now.
