### ISSUE TITLE
How to manually specify new Swagger definition

### ISSUE THREAD

**Issue by Lonli-Lokli** [microsoft/aspnet-api-versioning#545]
We have several middlewares on our .NET Core project available which comes with nuget package.
As it's middleware and not controller we do not see them in Swagger.
Is there any sample code for manually inserting data like path\definition which can be used for updating swagger definitions?

**Comment by commonsensesoftware** [comment]
The API Explorer operates on API Descriptions, which usually correspond to actions. If you have just pure middleware, I'm not sure if that will work from the ASP.NET Core side of things. It _might_, but most consumers of the API description, such as a Swagger generator, will expect the action to be non-null. To use this approach, you'll need to author and register a custom **IApiDescriptionProvider**.

You _should_ be able to modify the Swagger document yourself, but exactly how you do that will depend on the Swagger generator that you're using (ex: Swashbuckle, NSwag, etc). You'd have to look at the documentation for those libraries on how to best achieve that.

**Comment by commonsensesoftware** [comment]
As there's been no other activity on this issue and the resolution is external, I'm going to close this out. If you have other questions, feel free to come back. Thanks.

**Comment by Lonli-Lokli** [comment]
For those who will come into this - here is the sample implementation
https://github.com/aspnet/AspLabs/blob/master/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.Swagger/Internal/GrpcHttpApiDescriptionProvider.cs
