### ISSUE TITLE
System.AggregateException with netcoreapp3.0

### ISSUE THREAD

**Issue by spaasis** [microsoft/aspnet-api-versioning#549]
Sample repo: https://github.com/spaasis/apiversioningcore3 

I created a new asp.net core app with asp.net core 3.0 and added latest pre-release packages of Swashbuckle and Microsoft.AspNetCore.OData.Versioning.ApiExplorer. Doing the bare minimum config (see sample repo), the project doesn't start, but hits the same exception as in #499 

```TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.ActionConstraintCache' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.``` 

Did I miss something obvious or is there still some growing pains in the aspnetcore 3.0 transition?

**Comment by spaasis** [comment]
Hmm, so [ActionConstraintCache is not available on Core 3.0](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.internal.actionconstraintcache?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-3.0). Microsoft.AspNetCore.OData.Versioning contains a reference to Microsoft.AspNetCore.MVC.Core version 2.0.0. Could this be related to the issue?

**Comment by commonsensesoftware** [comment]
OData doesn't not support ASP.NET Core 3.0; therefore, API versioning doesn't support it either. The forthcoming 4.0 release of API Versioning will multi-target the build so OData will get the latest API Versioning features, but it will still be on ASP.NET Core 2.2. I don't have any control over that. You'd have to ask the OData repo about when they plan on supporting it.

**Comment by spaasis** [comment]
Ah, so that's the obvious thing I missed :) Thanks for clearing it up. Here's hoping the OData team gets around it soon.

**Comment by spaasis** [comment]
OData discussion here: https://github.com/OData/WebApi/issues/1748
