### ISSUE TITLE
Don't assume port 80 for nextLink when request was HTTPS

### ISSUE THREAD

**Issue by vbray1979** [microsoft/aspnet-api-versioning#550]
I just realized that the issue found and fixed in https://github.com/OData/WebApi/issues/1559 is still replicable in Microsoft.AspNetCore.OData.Versioning version 3.2.4.

Do you confirm ? When is the fix going to be integrated in Microsoft.AspNetCore.OData.Versioning?

**Comment by commonsensesoftware** [comment]
Do you have a repro? Where are you seeing this occur? I can't think of place where API Versioning gets involved with link generation - certainly not for **nextLink**. If you can provide an example or repro of where it happens, I can take a look. My expectation would be that you upgrade your version of the OData package with the fix and things just start working.

**Comment by vbray1979** [comment]
Hi Chris, that was it. I upgraded Microsoft.AspNetCore.OData and problem resolved. I thought Microsoft.AspNetCore.OData was embeded with aspnet-api-versioning. Thank you for your quick answer!!!
