### ISSUE TITLE
i use .netcore3.0 and i ues aspnet-api-versioning 3.1.0  i met also this question like this :  An error occurred while starting the application. TypeLoadException: Method 'ApplyAsync' in type 'Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy' from assembly 'Microsoft.AspNetCore.Mvc.Versioning, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

### ISSUE THREAD

**Issue by kdkler** [microsoft/aspnet-api-versioning#554]
how i can done it?

**Comment by commonsensesoftware** [comment]
You need to the preview version for now. It's the only .NET Core 3.0 compatible version. I'm working on getting the release build out. Expect it within the next week. There are no planned changes or known bug fixes, I've just been up to my eyeballs with my paying day job. ;)  Thanks for your patience.

**Comment by kdkler** [comment]
> You need to the preview version for now. It's the only .NET Core 3.0 compatible version. I'm working on getting the release build out. Expect it within the next week. There are no planned changes or known bug fixes, I've just been up to my eyeballs with my paying day job. ;) Thanks for your patience.

I see.  but i need which version?

**Comment by commonsensesoftware** [comment]
The following package should work:

https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/4.0.0-preview8.19405.7

**Comment by kdkler** [comment]
> The following package should work:
> 
> https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/4.0.0-preview8.19405.7

The problem has been solved. very ths!!!

**Comment by commonsensesoftware** [comment]
Keep an eye out for the official release. It **is** coming - soon. ;)

**Comment by eduardoxvii** [comment]
> The following package should work:
> 
> https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/4.0.0-preview8.19405.7

Man, ur the best!!!

**Comment by commonsensesoftware** [comment]
It would seem that this issue has been resolved. Feel free to come back if you have more questions. Thanks.
