### ISSUE TITLE
Support for patched versions - i.e. {major}.{minor}.{patch} 

### ISSUE THREAD

**Issue by danmcmanus** [microsoft/aspnet-api-versioning#560]

**Comment by commonsensesoftware** [comment]
I'll just come out and say that you wouldn't be the first to ask from something like this. Semantic versioning has been asked in the past. Honestly, a _patch_, _build_, or _revision_ makes no sense in the context of API. Clients should never care about such things. They should only care when the contract changes. While major and minor versions do not imply can specific behavior by a server, many people infer that a major version is a _big_ change and _minor_ version is a small change. Some people consider a _backward compatible_ change _minor_, but this is a false assumption. A server simply cannot assumption any change, even additive, will not break a client. Of course, if you control both sides, then you know whether this assumption holds true.

The rules and semantics for API versions in this project follow the [versioning semantics](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#12-versioning) set forth by the Microsoft REST API guidelines. Love 'em or hate 'em, but that's how this project got started.

There are currently a number of intrinsic comparisons and other assumptions about the API version that are not easily changeable. The only foreseeable feature I can see surfacing is providing extensibility in the API version format itself.  This is easier said that done. An API version format has to support:

- Parsing
- Equality (and inequality)
- Comparison (for sorting and ranking)
- Hashing
- Formatting (to various string formats)

That's probably enough work that most will not ever want to change it. I'm still open to such an idea, but it's not high on the priority list. You have to _really, really_ want to change to API version for such behaviors. The most practical scenario are those that have existing, incompatible API version formats that they cannot change.
