### ISSUE TITLE
OData Swashbuckle 5.0.0 rc-4 swagger.json generation for requestbody

### ISSUE THREAD

**Issue by spaasis** [microsoft/aspnet-api-versioning#562]
AspNetCore 2.2
Swashbuckle.AspNetCore 5.0.0-rc4
AspNetCore.OData.Versioning.ApiExplorer v.3.2.3

Original issue: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1331 

When I have an OData API controller with a PATCH/PUT/POST method that requires an [FromBody]-parameter, the generated swagger.json does not have any content on `requestbody`.  See the original issue for a code and result sample. GET works beautifully.

Is this an issue of the api-versioning package or OData itself?

**Comment by commonsensesoftware** [comment]
I haven't tried it - yet, but there's a chance the attributes are confusing the API Explorer. **Delta\<T\>** is _special_ as are a few other types in OData. These types have their own _model binders_. Part of the model binder API requires that they indicate where the value comes from. I've actually not need `[BindRequired]` before, but there's **no** scenario (that I'm aware) where OData will not provide the **Delta\<T\>**. The request fails if the binding cannot be satisfied.

I'd first try removing the attributes and see if that makes a difference. You can also work backward from [this example](../blob/master/samples/aspnetcore/SwaggerODataSample/V3/OrdersController.cs) with OData and Swashbuckle.

**Comment by spaasis** [comment]
Thanks for the response, sounds even more complex than I feared... Just a quick comment - I tried replacing the last parameter type with just a string and without the `BindRequired`, with the same results. In hindsight, should've left the simplest example stand.. I'll see if I have a chance to test further this weekend

**Comment by spaasis** [comment]
Okay, simple steps to verify:
In the OData+Swagger sample, the swagger.json POST works fine with [RequestBody].
Update Swashbuckle.AspNetCore to latest 5.0 release candidate and fix the build errors (SwaggerDefaultValues, ConfigureSwaggerOptions) and the POST method stops generating a valid swagger.json.

**Comment by commonsensesoftware** [comment]
It seems that Swashbuckle has changed a bunch of things under the hood. Specifically, there are some changes related to model generation that is breaking the OData support. I also found some actual issues that apparently Swashbuckle was being _generous_ about that I would consider a bug. 

This is now the final blocker to the v4.0 release. I thought I had everything ironed out. I'm hoping to have it resolved soon. In the meantime, if this is blocking you, then I would recommend an older version of Swashbuckle. Things were definitely working in 4.0.1. I'm not sure how far you can advance before things fall down.

Thanks.

**Comment by spaasis** [comment]
Hm, hopefully the end result will be worth the effort. Thank you for your hard work! Luckily I'm not in a hurry :)
