### ISSUE TITLE
Same endpoint with two route names , one works other one 404 "The resource cannot be found"

### ISSUE THREAD

**Issue by mayureshs** [microsoft/aspnet-api-versioning#563]
I have a single route with the same version and with two names. One route name works where as the other one throws an error 404 "The resource cannot be found"
Here is the setup for the versioning.

//WebApi Routes
config.AddApiVersioning();
var constraintResolver = new DefaultInlineConstraintResolver()
{ ConstraintMap =  {  ["apiVersion"] = typeof( ApiVersionRouteConstraint )  } };
config.MapHttpAttributeRoutes(constraintResolver);
config.Routes.MapHttpRoute("DefaultApi", "{controller}/{id}", new {id = RouteParameter.Optional});

Controller --->
`using System.Web.Http;
using Microsoft.Web.Http;

namespace Service.Controllers
{
    [ApiVersion("1.0")]
    [RoutePrefix("api/v{version:apiVersion}")]
    public class HealthController : ApiController
    {
        [HttpGet]
        [Route("issitelive")]
        [Route("islive")]
        public IHttpActionResult GetIsLiveResponse()
        {
            return Ok($"Service is Live");
        }
}`

**Comment by commonsensesoftware** [comment]
You didn't say which route worked and which one didn't. Based on your configuration, you have actually have 3 routes defined. I **strongly** advise against mixing attribute and convention-based routing. It typically leads to nothing but problems and confusion.

**Comment by mayureshs** [comment]
Thanks for responding. /api/v1/islive throws 404 but /api/v1 /issitelive does work. 
Can you provide details what is the third route configured. Also how can I change it to either attribute or conventional routing ?

**Comment by commonsensesoftware** [comment]
```c#
config.Routes.MapHttpRoute(
  "DefaultApi",
   "{controller}/{id}",
   new {id = RouteParameter.Optional});
```
is a convention-based route. This would define the route `health/{id?}`, which doesn't make sense in this context. It doesn't even have the route constraints for the API version the way you want.  I would remove this route definition.

I cannot seem to repro your scenario. I took your controller definition and dropped it into the [Basic Web API Sample](../tree/master/samples/webapi/BasicWebApiSample) and both routes work for me just fine. Is there something else about your configuration that you haven't shared? How are you hosting? Is it on IIS? It's not _supposed_ to matter, but there have been some edge cases in runtime differences based on the host.

Do you have a repro you can share?

**Comment by mayureshs** [comment]
Let me try to make those changes. Unfortunately I can’t share the repo, but I can try to create a new project and share if the changes don’t work.thanks !

**Comment by commonsensesoftware** [comment]
Were you able to finally resolve this?

**Comment by mayureshs** [comment]
This is resolved. It was x64 program trying to execute in x32 environment
