### ISSUE TITLE
Support of list of Accept header versions parameters

### ISSUE THREAD

**Issue by larsrjonsson** [microsoft/aspnet-api-versioning#575]
I have this situation where I need to be able to handle a list of Accept header versions parameters.
For example this header `application/json;v=3,application/json;v=2,application/json;v=1`.
Since there exists a client which will run against a couple of different versions of the API server.

And the client will ask for something like this:
If version 3 exists give me that, or else give me version 2, or else give me version 1.

I am using the aspnet-api-versioning with direct routing, and as it's working now if I send this request and version 3 does not exist then I will receive a **400 Bad Request, UnsupportedApiVersion.**

Is this something that can be configured or do I need to create some sort of custom selector or dispatcher to be able to support this?

Or is this something that shouldn't be supported at all?

**Comment by commonsensesoftware** [comment]
This is possible, but there's not really a way to support it out of the box. In order for this to work, you'd have to know which API versions are acceptable when the `Accept` header is parsed. The built-in implementation won't know this until later on in the pipeline (which an action is selected). If the selected API version doesn't exist, there's way for it to fallback.

You, on the other hand, know all of the API versions supported in your application so it's possible for you to extended or customize the built-in **MediaTypeApiVersionReader** or create your own variant implementing **IApiVersionReader**. Since you know that `3.0` won't exist, you can reject it is a possible candidate.

>As an aside, note that mixing and matching different versions by media type is not supported. While that is completely RESTful, there's simply no way to map that in code. In other words, you cannot have `Accept: application/json; v=3.0` combined with `Content-Type: application/json; v=2.0` in the same request. You didn't ask for that, but I thought I would mention it.

**Comment by larsrjonsson** [comment]
Ok, thanks for the fast reply. Think I understand the problem and maybe I can live with that only single Accept header is acceptable and using that empty accept header gets the latest implemented version instead.

Or else I will try to create my own customized MediaTypeApiVersionReader

**Comment by larsrjonsson** [comment]
> This is possible, but there's not really a way to support it out of the box. In order for this to work, you'd have to know which API versions are acceptable when the `Accept` header is parsed. The built-in implementation won't know this until later on in the pipeline (which an action is selected). If the selected API version doesn't exist, there's way for it to fallback.
> 
> You, on the other hand, know all of the API versions supported in your application so it's possible for you to extended or customize the built-in **MediaTypeApiVersionReader** or create your own variant implementing **IApiVersionReader**. Since you know that `3.0` won't exist, you can reject it is a possible candidate.
> 
> > As an aside, note that mixing and matching different versions by media type is not supported. While that is completely RESTful, there's simply no way to map that in code. In other words, you cannot have `Accept: application/json; v=3.0` combined with `Content-Type: application/json; v=2.0` in the same request. You didn't ask for that, but I thought I would mention it.

Ok, thanks for the fast reply. Think I understand the problem and maybe I can live with that only single Accept header is acceptable and using that empty accept header gets the latest implemented version instead.

Or else I will try to create my own customized MediaTypeApiVersionReader

**Comment by commonsensesoftware** [comment]
Also, it it wasn’t clear, your scenario is supported as long as all of the requested API versions exist. Ranking them by quality for preference is also supported. Providing a fallback isn’t really supported however. 

Another alternative would be to have _something_ clear the original, resolved values in the **IApiVersiongFeature** and allow an API version to be unspecified. This would then trigger the **IApiVersionSelector** path, which will include an aggregation of all supported versions and the current request. You could perform the resolution then, which - I believe - will get you the desired behavior

**Comment by commonsensesoftware** [comment]
It would appear this issue is now resolved. If it isn't, feel free to reopen it or post a new issue. Thanks.
