### ISSUE TITLE
SwaggerODataSample how add controller ?

### ISSUE THREAD

**Issue by franfr57** [microsoft/aspnet-api-versioning#577]
Hello,

I want to test the ASP.NET Core example with OData API Explorer (https://github.com/microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample))

I wanted to create a controller inspired by People:
`using DTO;
using Microsoft.AspNet.OData;
using Microsoft.AspNet.OData.Query;
using Microsoft.AspNet.OData.Routing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Examples.Models;
using Microsoft.OData;
using System;
using System.Collections.Generic;
using System.Linq;
using static Microsoft.AspNet.OData.Query.AllowedQueryOptions;
using static Microsoft.AspNetCore.Http.StatusCodes;

namespace Microsoft.Examples.Controllers
{
    [ApiVersion("3.0")]
    [ODataRoutePrefix("Exemple")]
    public class ExempleController : ODataController
    {
        [Produces("application/json")]
        [ProducesResponseType(typeof(ODataValue<IEnumerable<ExempleDTO>>), Status200OK)]
        public IActionResult Get(ODataQueryOptions<ExempleDTO> options)
        {
            try
            {
                //return Ok(_Mapper.Map<List<ExempleDTO>>(_ExempleService.get()));
                return Ok();
            }
            catch (Exception e)
            {
                return BadRequest(e.InnerException.ToString());
            }
        }
    }
}`

At runtime, I have a route /API under Example.
Why do not I have the route /API/Example?

**Comment by commonsensesoftware** [comment]
Fundamentally, it looks like all the pieces are in place; however, you did say you expect the route to be `api/example`, but you've used the name **Exemple** instead of _Ex**a**mple_. Perhaps it's just misspelled?

**Comment by franfr57** [comment]
Thank you I found the problem.
I had to create a SampleModelConfiguration file.

In the example for the People service, the top criterion does not work unless you set 0.
This returns me Bad Request.
How can I make it work?

**Comment by franfr57** [comment]
I found, you have to add this in the configuration model:
person.Page();


Is it possible to have a controllerBase inherit controller with an OData controller? How?

**Comment by franfr57** [comment]
I found a solution that works in my case where I want to register the version that is in a json file :
services.AddApiVersioning(
            o =>
            {
                o.AssumeDefaultVersionWhenUnspecified = true;
                o.DefaultApiVersion = new ApiVersion(MajorVersion, MinorVersion);
                o.ReportApiVersions = true;
            });

NB: I only use one version for my controllers.
