### ISSUE TITLE
Define controllers version with application json file

### ISSUE THREAD

**Issue by franfr57** [microsoft/aspnet-api-versioning#578]
Hello,

I want to test the ASP.NET Core example with OData API Explorer (https://github.com/microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample))

Is it possible to define the version of the controllers at the level of Startup.cs (to recover in a file json of configuration).
I want to use only one version in the code and set the version number in an appsettings.json file.

**Comment by commonsensesoftware** [comment]
Yes - this is possible. This can be achieved using the _[Conventions API](../wiki/API-Version-Conventions)_. There are number of variations shown in the wiki or you can also look at the [Conventions Example](../blob/master/samples/aspnetcore/ConventionsSample/Startup.cs). You can load your versions from a file and apply them with the fluent API or you can create your own convention that is configured to read the API versions from the file to apply them.

**Comment by franfr57** [comment]
I wish to be able to modify the url of the swagger:
options.SwaggerEndpoint($"/swagger/{description.GroupName}/swagger.json", description.GroupName.ToUpperInvariant());

If I modify description.GroupName by my version variable it does not work anymore.

How can I do ?

**Comment by franfr57** [comment]
I found a solution that works in my case where I want to register the version that is in a json file :
services.AddApiVersioning(
o =>
{
o.AssumeDefaultVersionWhenUnspecified = true;
o.DefaultApiVersion = new ApiVersion(MajorVersion, MinorVersion);
o.ReportApiVersions = true;
});

NB: I only use one version for my controllers.
