### ISSUE TITLE
Updated custom convention to asp.net core 3. Add to docs?

### ISSUE THREAD

**Issue by srpeirce** [microsoft/aspnet-api-versioning#579]
Hello @commonsensesoftware ,

You might remember that helped me to write an extension to this library a while back. #458 

https://github.com/purplebricks/PB.ITOps.AspNetCore.Versioning

It adds the attributes `IntroducedInApiVersion` and `RemovedAsOfApiVersion`.

I've just updated this to support asp.net core 3.

I think you were going to add this as an example of how to extend functionality of the library to the docs? Would you still like to do this? If so, would you like me to send a PR?

**Comment by commonsensesoftware** [comment]
Interesting question. I hadn't really spent a ton of time thinking about how to include external examples. I really only have two primary concerns. First, I have to consider that I'll end up _owning_ the example. In general that's not a huge deal. Second, I make it a point that the 1st party examples are complementary between Web API and ASP.NET Core, which may be a bit much for 3rd party examples.

There's some stuff in the wiki, but I suspect that may be _buried_ too far down for people to find. An alternative would be to include a markdown page (or pages) that reference 3rd party examples like yours. This would make it easy for people to find from here without me having to own it and would also enable you to make future enhancements without having to submit new PRs. I envision that this would be one uber page under `/samples` or there can be a separate page under the respective ASP.NET Core and Web API folders. The goal is to make things as discoverable as possible.

Thoughts?

**Comment by commonsensesoftware** [comment]
I'm circling back and trying to burn down issues.

After some thought, I think linking it via the wiki probably makes the most sense. If you have a one-paragraph description, we can add an entry for external examples. I'll add a link on the landing page that will jump to the wiki as _Additional Examples_ as well. I presume this would be something like the text in the first paragraph of your **readme.md** on the landing page. A Gist would work too.

Let me know. Thanks.

**Comment by commonsensesoftware** [comment]
I've linked to your project in the [3rd party section](../wiki/Extensions-and-Customizations#third-party-extensions) of **Extensions and Customizations**. If you'd like more text or a description, let me know. Thanks for sharing.
