### ISSUE TITLE
Is it possible to use ASP.NET core with OData support without versioning ?

### ISSUE THREAD

**Issue by Temppus** [microsoft/aspnet-api-versioning#596]
I struggled for long time when trying to get OData/Api controller explorers working with Swagger to generate swagger document, but was unable to solve it. Then I saw this project and reference to sample project that should integrate Swagger with OData and ASP .NET core and it worked like cham 👌 

However, because backwards compatibility (we are migrating from Owin/Katana), we cannot use versioning API.

Do you know (@commonsensesoftwar) if it is possible to get OData/Api controller explorers to work with swashbuckle to generate swagger document without using of versioning?

Thank you for your answer.

**Comment by commonsensesoftware** [comment]
Succinctly, I'll say - not really. If it did, I probably wouldn't have written any of this code; certainly, it would have been a lot less.

For out-of-the-box support without versioning, there are only two options I know of:

- Use the built-in [ODataSwaggerConverter](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/ODataSwaggerConverter.cs)
- Use an OSS EDMX-to-Swagger/OpenAPI transform (there are a few standard XSLTs out there)

These methods come with limitations, but provide _something_. Neither approach provides direct integration with a Swagger generator such as Swashbuckle or NSwag. You'll have to create and plug-in your own, custom document generator using one of the above listed methods. If the provided implementation is insufficient, you can always fork it and add the functionality you need.

I've asked the OData team before to include the required capabilities as part of their design. They are about to revamp a bunch of their routing infrastructure for .NET 5.0. Hopefully, they will add the missing pieces to make it easier for us all.

**Comment by Temppus** [comment]
Thank you very much for clarification.
