### ISSUE TITLE
Swagger schema for OData Functions/Actions are not generated properly.

### ISSUE THREAD

**Issue by Temppus** [microsoft/aspnet-api-versioning#598]
I am using OData EDM model builder to add additional additional OData Functions/Actions to model.
But when I am doing it, swagger will not generate proper input parameters for them, because those Actions/Functions are taking ODataActionParameters and then generated schema for these Functions/Actions schema looks like this:
```
-schema: {
type: "object",
-additionalProperties: {
type: "object"
}
}
```

And example models looks like this:
```
{
  "additionalProp1": {},
  "additionalProp2": {},
  "additionalProp3": {}
}
```

It seems like Action/Functions parameters that are defined when created are not used for swagger schema generation. Can I setup/configure EDM model exploration to get this working or do I need to implement custom IOperationFilter in swashbuckle and hack fix it manually ?

Thank you for answer.

**Comment by commonsensesoftware** [comment]
I presume this must be outside the scope of API versioning. All of the Swagger/OpenAPI generators that I know of such as Swashbuckle or NSwag use Reflection to build their documents. In the case of an OData action, the ODataActionParameters is nothing more than a dictionary so there is nothing for it to generate a model from (remember that they know nothing of the EDM). The API Explorer support provided by API versioning addresses this by generating a new, dynamic, non-executable type per API version that looks exactly the way the EDM says it should using Reflection Emit. Now, when handed off to a generator, things work as expected. The sample project demonstrates this in action.

You're welcome to fork that logic for your own purposes, but be warned that it's very advanced Reflection code. This same code is used to handle generating sub-models (aka _Model Substitution_). OData will only expose the part of your model defined in the EDM, but a Swagger/OpenAPI generator will show everything. The same technique is used to generate a new type that is a subset of the original type based on the EDM. When you start considering child collections, self-referencing properties, and so, it gets very complicated.

It _looks_ like you are using Swashbuckle. You should be able to use a custom **IOperationFilter** or a document generator to add this information explicitly. I'm not an expert in those libraries so it's probably best to ask on the appropriate repo or SO.

I hope that helps.

**Comment by commonsensesoftware** [comment]
Did this answer your question?

BTW: custom filters or other API Explorer extension are required if you're using _Open Types_ because there is simply no source for defined members anywhere. I don't think this was the question, but I thought it was worth mentioning.

**Comment by commonsensesoftware** [comment]
This issue has gone dark. It was never clear whether this was vanilla OData or with API Versioning. This project and repository only handles issues related to API Versioning. For OData issues not related to API Versioning, you'll want to ask the question in the OData repo. If this issue is related to API Versioning and you can provide additional context, I'm happy to elaborate further. Thanks.
