### ISSUE TITLE
Not able to generate unique operation id based on routes

### ISSUE THREAD

**Issue by SailleshPawar** [microsoft/aspnet-api-versioning#602]
I am trying to support old routes and url segment routes as well. 
But swagger fails because of duplicaton operation id while depoying swagger to APIM. 

I have following Controller

[Route("api/[controller]")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [Produces("application/json")]
    [ExcludeFromCodeCoverage]
    [ApiController]
    public class SampleController : ControllerBase
    {
       [HttpGet("{id}")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
        [SwaggerOperation(OperationId = "GetId")]
        public async Task<IActionResult> Get(int id)
{
//
}

Swagger file generated for this API with routes is as shown below:

1. Old API route

/api/Mortgage/{id}: {
get: {
tags: [
"Mortgage"
],
summary: "Retrieve the mortgage by Id",
description: "This endpoint is responsible for retrieving Mortgage by Id",
operationId: "GetId",
consumes: [ ],
produces: [
"application/json"
],

2. New Url Segment 
/api/v{version}/Mortgage/{id}: {
get: {
tags: [
"Get"
],
summary: "Retrieve the mortgage by Id",
description: "This endpoint is responsible for retrieving Mortgage by Id",
operationId: "GetId",
consumes: [ ],
produces: [
"application/json"
],

The swagger file fails in azure devlops build pipeline because of duplicate operation id. Is there any way to generate unique operation id.

**Comment by commonsensesoftware** [comment]
There are several options, but it all depends on your configuration. From what I can tell you are versioning by URL segment and using Swashbuckle to generate the documents. I'm going to assume that you have included the API Explorer extensions package for API Versioning. If all of my previous assumptions are correct, then you should be able to achieve the result you want by updating your configuration as follows to generate unique URLs in the document:

```c#
services.AddVersionedApiExplorer(
    options =>
    {
        options.GroupNameFormat = "'v'VVV";
        options.SubstituteApiVersionInUrl = true;
    } );
```

This will have the following effects:
- API version `1.0` will be formatted as `v1`, `2.1` will be `v2.1`, and so on
- The API version route parameter will be removed from the descriptor and the route template will have the corresponding token replaced by the formatted value

This means that based on your first example, the routes `api/sample` ,  `api/v1/sample`, and so on will be produced.

The other option is to create a document per API version. This is typically the approach used by the self-host Swagger/OpenAPI endpoints. I suspect for APIM you have to create a document which collates all versions in a single document.

I hope that helps.

**Comment by SailleshPawar** [comment]
Thanks Chris for replying you are correct  this approach is fine for self-host swagger. 
But for APIM swagger step is failed due to duplicate operation id being generated for old and version route.
Is there any way to create a document which collates all versions in a single document.
I tried searching the for the solution but there is no straight forward way to that in azure devops.
I found below blog which tries to solve the problem with powershell script.

https://www.hakantuncer.com/2018/09/16/api-versioning-with-swagger-azure-api-management-services-and-asp-net-core-a-frictionless-devops-experience/

**Comment by commonsensesoftware** [comment]
I'm not sure if Swashbuckle or any other OpenAPI document generator has out-of-the-box support for this behavior. They _might_, but I'm just not familiar with it. Ultimately, this will be a consequence of this particular style and configuration of versioning. You have essentially have two routes that refer to the same thing.

There are several possible solutions:
- Generate the OpenAPI/Swagger document yourself (programatically) where you generate distinct `operationId` members or filter them out
- Create a custom **IOperationFilter** and filter out unnecessary duplicates (you only really need one of the two routes)
- Create a custom **IOperationFilter** that updates/regenerates a distinct `operationId` (I believe this is possible)
- Create a custom **IApiDescriptionProvider** which filters out the descriptors which would produce duplicates (I can't remember what `operationId` is mapped to, so you may not be able to fix name generation with this approach; you want this to run after API Versioning's provider)

I don't have any examples of these approaches, but any one of them should work. Swashbuckle specific questions might be better answered on that repo or Stackoverflow.

I hope that helps you get started.
