### ISSUE TITLE
XmlFormatter XmlSerializer issue with VersionedApiExplorer

### ISSUE THREAD

**Issue by lucamazzanti** [microsoft/aspnet-api-versioning#603]
At bootstrap of a web api 2 application, in the owin Startup Configuration:

```
var apiExplorer = GlobalConfiguration.Configuration.AddVersionedApiExplorer(options => { options.GroupNameFormat = "'v'VVV"; options.SubstituteApiVersionInUrl = true; });

var issue = apiExplorer.ApiDescriptions;

GlobalConfiguration.Configure((config) => { config.Formatters.XmlFormatter.UseXmlSerializer = true; });
```
If i access to ApiDescritpions I have isssue during xml serialization in request, it not use XmlSerializer but datacontracts instead. I see in ApiExplorer code some usage of Formatters, need to investigate.

I solved not using apiExplorer, but i want to reinsert that asap.

**Comment by commonsensesoftware** [comment]
If you're using _Attribute Routing_, this is almost certainly because you're using the global **HttpConfiguration** before it's ready. To be safe, you shouldn't access it outside of the `Configure` method. Once you access the `ApiDescriptions` property, this will trigger API discovery and descriptor generation. At minimum, you need to set `UseXmlSerializer` and any other required setup before using the API Explorer.

I hope that helps.

**Comment by lucamazzanti** [comment]
```
public class Startup {
public void Configuration(IAppBuilder app)  {
    GlobalConfiguration.Configure(WebApiConfig.Register);
    GlobalConfiguration.Configure((config) => {  config.Formatters.XmlFormatter.UseXmlSerializer = true; });
    GlobalConfiguration.Configure(SwaggerConfig.Register);
 }
 }
```
This is my bootstrap. This is a web api 2 projecte template, global.asax is empty, startup is registered as OwinStartup, SaggerConfig is called manually in the snippet code. I'm hosting that app on IIS.
I tried to use a new HttpConfiguration instead of globalconfiguration and pass it at the end of method in app.UseWebApi(config), but I have strange beahaviours on api-versioning and swagger.
So I remain that way, and avoid to use apiExplorer, I probably don't understand how to prepare a web api project.

**Comment by lucamazzanti** [comment]
reordering operations seems to work properly.
