### ISSUE TITLE
ASP.NET Profile doesn't persist data for anonymous users without error message

### ISSUE THREAD

**Issue by DSivtsov** [microsoft/aspnet-api-versioning#606]
ASP.NET Profile doesn't persist data for anonymous users, It's Ok.
But it did **without any error message**
I'm trying to use ASP.NET Profile to persist user data with default machine.config (.Net Framework 4.5.2) to web.config Site's was added only.
```
    <system.web>
      <profile>
        <properties>
          <add name="AddressInfo" type="UserAddress" serializeAs="Binary"/>
        </properties>
      </profile>
    </system.web>
```
I tested it by simple code-behind (on Page 3 TextBox and Button)
```
public partial class _Default : System.Web.UI.Page
{
  protected void Page_Load(object sender, EventArgs e)
  {
    GetUserAddress();
  }
  protected void btnSubmit_Click(object sender, EventArgs e)
  {
    // Database writes happening here!
    Profile.AddressInfo.City = txtCity.Text;
    Profile.AddressInfo.Street = txtStreetAddress.Text;
    Profile.AddressInfo.State = txtState.Text;
    // Get settings from database.
    GetUserAddress();
  }
  private void GetUserAddress()
  {
    // Database reads happening here!
    lblUserData.Text = String.Format("You live here: {0}, {1}, {2}",
      Profile.AddressInfo.Street, Profile.AddressInfo.City,
      Profile.AddressInfo.State);
  }
}
[Serializable]
public class UserAddress
{
  public string Street = string.Empty;
  public string City = string.Empty;
  public string State = string.Empty;
}
```
Application started, "OnClick" **without errors executes the methods** (btnSubmit_Click(...) and GetUserAddress()) and updating value of lblUserData Label, but is nothing write to DB (also didn't created the DB itself - ASPNETDB.mdf in App_Data folder Site's). After reopen Page corresponding Profile properties and lblUserData Label was empty.
I also describe it on [stackoverflow.com](https://stackoverflow.com/questions/60423328/asp-net-profile-doesnt-persist-data/60423329#60423329) and also wrote decision of the problem.

**Comment by commonsensesoftware** [comment]
I’m not sure I follow how this is related to API Versioning. This repo is only about API Versioning. For general ASP.NET questions, I recommend Stackoverflow or the classic ASP.NET repo.

**Comment by commonsensesoftware** [comment]
There hasn't been follow up and this issue appears to not be related to API Versioning. If I'm mistaken, please feel free to reopen the issue and elaborate on the issue you are facing. Thanks.
