### ISSUE TITLE
URL path based versioning without attributes using conventions

### ISSUE THREAD

**Issue by baharedankoyuncu** [microsoft/aspnet-api-versioning#607]
Hi,

I was wondering if it was possible to use URL path based versioning e.g. `https://example.com/api/1.0/members` but without attributes on the controller level i.e. 

```
    [ApiVersion("1.0")]
    [ApiController]
    [Route("api/{version:apiVersion}/[controller]")]
    public class MembersController : ControllerBase
    {
    }
```

Can we somehow specify in our `Startup.cs` (ASP.NET Core 3.1) that we would like to use conventions _and_ path based versioning without the attributes?

```
            services.AddApiVersioning(options =>
            {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true;
                options.DefaultApiVersion = new ApiVersion(1, 0);
                options.ApiVersionSelector = new CurrentImplementationApiVersionSelector(options);

                options.Conventions.Controller<MetaController>().IsApiVersionNeutral();
                options.Conventions.Controller<MembersController>().HasApiVersion(new ApiVersion(1, 0));
            });
```
I haven't been able to find anything in the docs regarding this.

// Baha

**Comment by commonsensesoftware** [comment]
The two methods are complementary. There isn’t anything to turn on or off. If you use conventions, then you can remove the attributes. You can use both if you really want too. The results are always a union.

The AssumeDefaultVersionWhenUnspecified option will probably not work the way you hope. It will only work with _double route_ registration as described in the wiki. There is no way to have an optional path fragment in the middle of a URL for obvious reasons. This is one the numerous issues why caution people who choose versioning by path segment; it’s the least RESTful.

You can also author your own conventions. This is useful if you have some organic convention based on code organization, etc. There is a built-in convention that uses the controller’s namespace as a convention. There is a sample app that demonstrates things end-to-end. More information is available in the wiki.

I hope that helps

**Comment by baharedankoyuncu** [comment]
Hi @commonsensesoftware,
Thanks for the great answer, that was all I needed 👍
