### ISSUE TITLE
Port hotfixes to support .net core 2.1

### ISSUE THREAD

**Issue by Lonli-Lokli** [microsoft/aspnet-api-versioning#609]
Starting from 3.1.0 only .net core 2.2 is supported.
However, this version of net core is deprecated, while 2.1 is still LTS.

Is it possible to release 3.2.0 with netcore 2.1 support and all fixes from 3.1.0?

**Comment by commonsensesoftware** [comment]
3.1.0 required the updated references to ASP.NET 2.2. I _believe_ that means any patching that targets .NET 2.1 will have to start from 3.0.0. That was quite some time ago so I'll have to carefully review things to be sure.

Back-porting fixes is a capacity issue more than anything. It's technically possible to include 2.1 support in a single package, but I don't know that I want to do that - again. Multi-targeting can be complicated and the previous release that supported 2.2 for OData proved to be confusing for several people that thought ASP.NET Core 3.0+ references still supported .NET Standard 2.0, which it doesn't; however, you can reference other .NET Standard libraries (ASP.NET Core 3.0+ is .NET Core 3.0+).

Is there some specific issue or fix that you need in 2.1? In general, I don't patch old versions, but on occasion, I've been known to do so. Understanding the need helps. As a one man show, it's difficult to actively maintain multiple branches.

**Comment by commonsensesoftware** [comment]
Checking back in. I realize it's been a while. I've been quite backed up. Is this still something you need or a hypothetical? Is there something specific you need or you really need/want a backport of all fixes. I'm inclined to backport a fix for a bug, but much less so to backport a feature. I'm looking to start queuing back up work and I'm trying see if I need to track this. Honestly, it will probably be lower priority unless it only involves a few specified fixes. Nevertheless, I don't want it to fall off the radar if it's something needed. Thanks.

**Comment by Lonli-Lokli** [comment]
@commonsensesoftware I believe we can close this issue - 2.1Core project is not supported by our team anymore and in next projects we do not use OData anymore, just pure API versioning.

**Comment by commonsensesoftware** [comment]
I didn't realize this included OData too. Glad you were able to come up with a solution. Thanks.
