### ISSUE TITLE
Null parameter on post data for inherited models

### ISSUE THREAD

**Issue by pil0t** [microsoft/aspnet-api-versioning#618]
I have very strange behavior for model classes with inheritance and Versioning features.
Following the [example ](https://github.com/microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample) I created a very simple model and controllers.
If I have two classes inherited from the same base class, I faces null during the Post method in OData controller with Versioning features. This not reproduces with plain objects (without inheritance), also this not reproduces without Versioning Features. Any suggestions what can be wrong?

Here is  my example:

    public class EntityBase<T> {
        public T Id { get; set; }
    }
    public class Bar : EntityBase<Guid> { }
    public class Foo: EntityBase<Guid> { }

    // Foo-Bar without inheritance works fine!!!
    // public class Bar
    // {
    //     public Guid Id { get; set; }
    // }
    // public class Foo{
    //     public Guid Id { get; set; }
    // }

    public class FoosController : ODataController
    {
        public IActionResult Post( [FromBody] Foo item )
        {
            // Item is null
            return Created(item);
        }
    }

    public class BarsController : ODataController
    {
        public IActionResult Post( [FromBody] Bar item )
        {
            // Item is NOT null
            return Created(item);
        }
    }
    public class FooBarConfiguration : IModelConfiguration
    {
        public void Apply( ODataModelBuilder builder, ApiVersion apiVersion )
        {
            builder.EntitySet<Foo>( "Foos" ).EntityType.HasKey( p => p.Id );
            builder.EntitySet<Bar>( "Bars" ).EntityType.HasKey( p => p.Id );
        }
    }

Full Solution with working and non-working examples you can find at:
https://github.com/pil0t/VersionedODataBugExample
Simple way to reproduce:
Run `VersionedOdataBug` project
Go to swagger
`​/api​/Bars`  - Works fine
`/api/Foos` - Returns 500

with:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'entity')
   at Microsoft.AspNet.OData.ODataController.Created[TEntity](TEntity entity)
   at ModelAndControllers.BaseController`1.Post(T item) in C:\work\WebApplication\ModelAndControllers\BaseController.cs:line 10
```

**Comment by commonsensesoftware** [comment]
Thanks for the repro. That helps immensely. I was able to repro the scenario. In comparing the work and non-working flavors, I noticed a very subtle difference.

### Working
You have this model configuration:

```c#
odataBuilder.EntitySet<Foo>("Foos");
odataBuilder.EntitySet<Bar>("Bars");
```

### Non-Working
You have this model configuration:

```c#
builder.EntitySet<Foo>( "Foos" ).EntityType.HasKey( p => p.Id );
builder.EntitySet<Bar>( "Bars" ).EntityType.HasKey( p => p.Id );
```

### Observation (Solution?)
Just to ensure they are the same, I changed the non-working solution to:

```c#
builder.EntitySet<Foo>( "Foos" );
builder.EntitySet<Bar>( "Bars" );
```

... suddenly ... :boom: It works!!!

I have absolutely no idea why. More interesting is that if I add `.EntityType.HasKey( p => p.Id )` to the working example, they both start failing. I don't get why only one fails with versioning. This indicates to me that it's probably a bug somewhere in OData. API Versioning doesn't mess with the media type formatters or model binding. The _versioned_ model builder isn't a custom builder, it's merely a builder of (built-in) builders. I have seen this type of behavior before when model binding fails; you just get `null`.

It would seem your options are:

- Don't use inheritance
- Remove the explicit property key configuration

I hope that helps.

**Comment by pil0t** [comment]
@commonsensesoftware thank you for help! 
It took me too much time to make the final check (I started with quite a big model, and suddenly faced with null in POSTs). And I was really frustrated when one Class works fine and not another. 
Going to raise a bug in the OData repo.
