### ISSUE TITLE
Unable to route to endpoint when using ApiVersion and controllers in ApplicationParts

### ISSUE THREAD

**Issue by marlonreid** [microsoft/aspnet-api-versioning#620]
I am creating an API that can load plugins at application start. These plugins are not known at build time (the API project does not reference the assemblies directly) and are loaded as ApplicationParts at startup.

In this example, ClassLibrary is a plugin. The API does not have a dependency on ClassLibrary.dll.

```
            var builder = services.AddControllers();
            var loadContext = new PluginLoadContext(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "ClassLibrary.dll"));
            var assembly = loadContext.LoadFromAssemblyName(new AssemblyName("ClassLibrary"));
            builder.AddApplicationPart(assembly);
```

I then proceed to enable versioning.
```
            services.AddApiVersioning((o =>
            {
                o.UseApiBehavior = true;
                o.ReportApiVersions = true;
            }));
            services.AddVersionedApiExplorer(
                options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });
```
I then create a 2 versions of the ValuesController in ClassLibrary.dll.
```
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public string Get()
        {
            return "v1";
        }
    }
```
```
    [ApiVersion("2.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public string Get()
        {
            return "v2";
        }
    }
```
Finally, in the configure method I have the following
```
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
```
The output from trying to hit the 2 different endpoints follow:
```
GET api/v1/Values
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

ClassLibrary.V2.ValuesController.Get (ClassLibrary)
ClassLibrary.V1.ValuesController.Get (ClassLibrary)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```
```
GET api/v2/Values
{
    "error": {
        "code": "UnsupportedApiVersion",
        "message": "The HTTP resource that matches the request URI 'http://localhost:58203/api/v2/Values' does not support the API version '2'.",
        "innerError": null
    }
}
```
The following debug output is also shown.
```
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      2 candidate(s) found for the request path '/api/v1/Values'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'ApplicationPartsTest.V2.Controllers.ValuesController.Get' with route pattern 'api/v{version:apiVersion}/Values' is valid for the request path '/api/v1/Values'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'ApplicationPartsTest.V1.Controllers.ValuesController.Get' with route pattern 'api/v{version:apiVersion}/Values' is valid for the request path '/api/v1/Values'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
```

When referencing the assembly directly in the API and disabling the explicit loading of the application parts, it works as expected.

Any guidance would be appreciated.

[MultipleRoutesApplicationParts.zip](https://github.com/microsoft/aspnet-api-versioning/files/4492351/MultipleRoutesApplicationParts.zip)

**Comment by commonsensesoftware** [comment]
This _looks_ right thus far. This type of configuration is certainly possible and I've even built one out with versioning myself. The repro helps. I'll give it a look as soon as I can.

**Comment by marlonreid** [comment]
I believe I know what the issue is.

In the method, Microsoft.AspNetCore.Mvc.Versioning.ApiVersioningApplicationModelProvider.IsDecoratedWithAttributes we check to see if the controller has an attribute of either IApiVersionProvider or IApiVersionNeutral. This check always fails, since the types are loaded into separate AssemblyLoadContext. 

The solution appears to be to load shared assemblies into the Default assembly load context, which _should_ result in the above type checks succeeding. 

[](https://stackoverflow.com/questions/58912559/how-to-ensure-typeof-and-cast-operators-operate-on-a-different-load-context-not)

[](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext)

**Comment by commonsensesoftware** [comment]
That sounds like a reasonable solution that should work. It doesn't cost anything extra because you already have to load the API versioning library into the default context anyway. You might also check your AssemblyLoadContext implementation. Depending on _when_ and _where_ you start loading external assemblies, the API Versioning library should have already been loaded into the default context (if not, you may want to make that the case). If the plug-in context doesn't find the API Versioning library, you're custom AssemblyLoadContext should resolve it from the default context. That's pretty typical for plug-in type applications anyway.

**Comment by marlonreid** [comment]
For the others that run into this issue, the issue gets resolved by changing the custom AssemblyLoadContext's load method from 

```
        protected override Assembly Load(AssemblyName assemblyName)
        {
            var assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
            return assemblyPath != null ? LoadFromAssemblyPath(assemblyPath) : null;
        }
```

to 
```
        protected override Assembly Load(AssemblyName assemblyName)
        {
            var defaultContext =  Default.Assemblies.FirstOrDefault(x => x.FullName == assemblyName.FullName);

            if (defaultContext != null)
            {
                return defaultContext;
            }
            
            var assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
            return assemblyPath != null ? LoadFromAssemblyPath(assemblyPath) : null;
        }
```
