### ISSUE TITLE
IApiDescriptionGroupCollectionProvider for OData?

### ISSUE THREAD

**Issue by ignatandrei** [microsoft/aspnet-api-versioning#621]
If I want to inspect the controlers and definition and everything, I use IApiDescriptionGroupCollectionProvider 

What is the equivalent for OData ?( .NET Core 3.x)
( and you can provide an example about how it provides routing , parameters, and so on)(
Thanks

**Comment by commonsensesoftware** [comment]
With versioning, there's nothing _special_ about it. You use **IApiDescriptionGroupCollectionProvider** just like you would in any other context. This is why it works with OpenAPI/Swagger generators like Swashbuckle, NSwag, etc.

Tests _are_ the documentation. :wink: Here's an example that demonstrates how to setup an OData application and request the API descriptions: [OData API Explorer Should Group and Order Descriptions After OnProvidersExecuted](../blob/master/test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNetCore.Mvc.ApiExplorer/ODataApiDescriptionProviderTest.cs#L16).

>NOTE: This will **only** work with API Versioning. If you're trying to use plain 'ol OData, you're out of luck I'm afraid. I've had to build out API Explorer support because OData doesn't provide support for it.

I hope that helps.

**Comment by ignatandrei** [comment]
I see . This was my intention. If I do not reproduce your code ( e.g. GetApiVersions() ) , the error is " The entity model (EDM) does not have the required ApiVersionAnnotation annotation. . "

Thanks for your answer.
Just for curiosity :
I see in the code 
routeBuilder.MapVersionedODataRoutes( "odata", "api", modelBuilder.GetEdmModels() ) );

Do your code work with endpoint routing from .NET Core 3 ? 
( i.e.   app.UseEndpoints(endpoints =>
            {

                endpoints.MapControllers();
)

**Comment by commonsensesoftware** [comment]
With Endpoint Routing - yes. With OData + Endpoint Routing - no. I think the OData package is still beta. I’ve started looking at it. Hopefully it won’t be too much work, but that hasn’t historically been the case. No OData and everything just works. OData and you have to use legacy routing - for now. The code is otherwise the same.

**Comment by ignatandrei** [comment]
Yeah. Look, what I have tried to do is to map the OData routes to Blockly . See     https://github.com/ignatandrei/NETCoreBlockly . But I doubt that anyone that have OData will go this path . Thanks for your help.

**Comment by commonsensesoftware** [comment]
Interesting concept. It would seem what you are trying to achieve _is_ technically possible albeit with a few limitations. Mixing and matching OData with non-OData may require some adjustments on your side due to a a bug in how OData registers on of their **InputFormatter** and **OutputFormatter** types. There is obviously the limitation on _Endpoint Routing_, but I'm hoping to resolve that in the near future.

**Comment by ignatandrei** [comment]
Keep me posted, please. I need a sample project to showcase with Webapi and Odata ( and GraphQL)

**Comment by NetTecture** [comment]
@commonsensesoftware Odata API 7.4 got released ;)

**Comment by ignatandrei** [comment]
And that means endpoint routing works ?

**Comment by NetTecture** [comment]
Well, i am on 7.4 since quite some time for that reason (and finally happy to leave the nightly builds). So, yes, at least from what I do configure - endpoint routing works.

**Comment by ignatandrei** [comment]
could you share code from startup.cs?

**Comment by commonsensesoftware** [comment]
@NetTecture this is good and interesting news. IMHO if the OData team implemented things correctly, then _Endpoint Routing_ should just work. Endpoint Routing has policies that are meant to be composable. I'm not sure what they may have changed. I reached out to the lead dev internally, but got no response. This should mean minimal work for lighting up the rest of API Versioning

**Comment by NetTecture** [comment]
@ignatandrei My startup.cs code is like this:

            app.UseEndpoints(e => {
                var timezoneCentralEurope = TimeZoneInfo.FindSystemTimeZoneById("Central European Standard Time");
                e.SetTimeZoneInfo(timezoneCentralEurope);
                e.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
                var model = ODataSetup.ConfigureEdmModel();

                e.EnableDependencyInjection();
                e.MapODataRoute(
                    "odata", String.Empty,
                    b => {
                        b.AddDefaultODataServices(ODataVersion.V401);
                        b.AddService(ServiceLifetime.Singleton, sp => model);
                        b.AddService<ODataDeserializerProvider>(ServiceLifetime.Singleton, sp => new EntityReferenceODataDeserializerProvider(sp));
                        b.AddService<IEnumerable<IODataRoutingConvention>>(ServiceLifetime.Singleton, sp =>
                            ODataRoutingConventions.CreateDefaultWithAttributeRouting("odata", e.ServiceProvider));
                    }
                );
            });
            app.UseODataBatching();

Complex overload in use because I uave a special deserializer that handles @odata.bind statements in a way that allows me to work with them.

**Comment by ignatandrei** [comment]
With the new ODATA  it works - thanks !

**Comment by NetTecture** [comment]
You mean it works with odata - or did you get versioning working? How would you put in the versioning if it is supposed to possibly work? Asking because I would love to try this out this week.

**Comment by ignatandrei** [comment]
just made an endpoint with EnableQuery. Download demo zip from here
https://github.com/ignatandrei/NETCoreBlockly/issues/34 
( it is an issue just because I want to recognize ODATA endpoints and  generate blocks with Filter, query and so on - not because ODATA has problems)

**Comment by commonsensesoftware** [comment]
This thread has been idle and marked answered. I believe the original question has been driven to conclusion. Further discussion about _Endpoint Routing_ support should move to that specific issue. Thanks.
