### ISSUE TITLE
@Giuseppe Innocenti

### ISSUE THREAD

**Issue by kookoorikoo** [microsoft/aspnet-api-versioning#622]
How can we get in contact friend?

**Comment by commonsensesoftware** [comment]
@kookoorikoo how can I help?

**Comment by kookoorikoo** [comment]
Would like to ask @Giuseppe Innocenti for help with deck of cards

**Comment by commonsensesoftware** [comment]
I'm sorry - deck of cards? How is this related to API Versioning?

**Comment by kookoorikoo** [comment]
Sorry...not related....but I haven't found any other way to contact Giuseppe Innocenti

**Comment by commonsensesoftware** [comment]
I wish I could help, but I don't know who @ginnocenti is nor how to contact them.

**Comment by commonsensesoftware** [comment]
This doesn't appear to be a relevant issue, but I hope you find your friend. Best wishes.
