### ISSUE TITLE
Core 3 Odata url path versioning

### ISSUE THREAD

**Issue by spaasis** [microsoft/aspnet-api-versioning#623]
Hi,
Just a quick question since I couldn't find a definite answer in the docs (probably just missed it);

Is URL path versioning supported in OData + ASP NET Core 3? [The URL path docs](https://github.com/microsoft/aspnet-api-versioning/wiki/Versioning-via-the-URL-Path) do not mention that specific configuration, and it's not mentioned in the [Known Limitations](https://github.com/microsoft/aspnet-api-versioning/wiki/Known-Limitations) either.

I dimly remember reading that URL path versioning cannot work because endpoint routing is not yet supported by OData, but could not find it now.

The reason why this would be preferable to other versioning methods for us is that Excel and PowerBI OData functionality would work with url-segmented api versioning out of the box, but have issues with version query parameters.

**Comment by commonsensesoftware** [comment]
There are no limitations on which versioning methods can be used with specific frameworks. You can definitely version by URL segment in OData if you want to. The [Basic OData Sample](../blob/master/samples/aspnetcore/ODataBasicSample/Startup.cs#L49) demonstrates how to do this. Note that the example sets up the default query string method and the URL segment method, which requires a route prefix in OData. You do **not** need both. It's a convenience to show both without having to create two sample applications that differ only by a single configuration line.

I hope that helps.

**Comment by spaasis** [comment]
That's great, thanks for the quick answer and example! 
Could've sworn I tried the exact same configuration yesterday and it threw an error `An error occurred while creating the route with name 'odata-bypath-Unversioned' and template 'api/v{version:apiVersion}//{*odataPath}'.'`. Guess there was some difference in the config since now it works like a charm :)

Thanks for the great library!

**Comment by commonsensesoftware** [comment]
Glad you got it working.

Your additional details reveal 2 interesting things, which may be helpful in the future:

- Route names with **-Unversioned** are _special_ auto-generated routes meant to be a _catch-all_ so that failure to match a versioned OData route responds with an appropriate 400 or 404 (consistent with non-OData) instead of always 404
- The template `api/v{version:apiVersion}//{*odataPath}` has an extra `/` in it. I suspect that may have been the culprit
