### ISSUE TITLE
Wiki: ASP.NET Core Versioned API Explorer - Info() has been replaced by OpenApiInfo()

### ISSUE THREAD

**Issue by patrickvslalom** [microsoft/aspnet-api-versioning#625]
In this quickstart, Info() has been replaced by OpenApiInfo():
https://github.com/microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-core

Thanks for all you do to maintain this site.

**Comment by commonsensesoftware** [comment]
Ah ... thanks. It's probably time to do a full review of the Swashbuckle examples as a number of things changed in 5.0+. Thanks for calling it out.

**Comment by commonsensesoftware** [comment]
Sorry it took so long. Finally updated this. Thanks for calling it out. Keep the feedback coming.
