### ISSUE TITLE
Is there any way to declare api version like V2 in asp.net core rather then 2.0.

### ISSUE THREAD

**Issue by SailleshPawar** [microsoft/aspnet-api-versioning#629]
I am facing issues to support versioning in asp.net core 2.2 with Azure Api management.
Azure Api Management has Version identifier to be started with v. 
But asp.net core doesn't support  identifier with v for query and headers.
Is there any way to achieve this behaviour?

**Comment by commonsensesoftware** [comment]
Do you have some examples and/or links to documentation. I have limited knowledge of the particulars of API Management other than I know that they impose some of their own rules (which is just _wrong_ IMHO).

Thanks

**Comment by SailleshPawar** [comment]
I will share the snapshot shortly.
Just wanted to ask is there any way I create my api version with v2 rather then 2.0 in asp.net core 2.2.

**Comment by SailleshPawar** [comment]
![image](https://user-images.githubusercontent.com/16855395/81096527-6d036d80-8efe-11ea-96c4-d4948c028d2b.png)

APIM allows version header as V1. That is fine if we are using url based routing but for header based it's causing issue.

**Comment by commonsensesoftware** [comment]
No. `v` is not part of an API Version. This is also outlined in the Microsoft REST Guidelines.

I've looked at [these documents](https://docs.microsoft.com/en-us/azure/api-management/api-management-get-started-publish-versions) and I don't see anything that says you need to use `v`. In fact, all the query string examples I can find use the format `api-version={date}`, which is the same thing that Azure itself uses.

**Comment by commonsensesoftware** [comment]
There is no scenario in API Versioning where `v` is part of the API Version and it's not needed. While it's common for `v` to be present in the URL segment method of versioning, it's **not** part of the version. A prefix of `api/v2` has the API version `2.0`.

In the picture you've provided, the **Version Identifier** is the API Version value. This should **not** include the `v`. For `2.0`, it can be either `2.0` or just `2` as the minor version is implicit. The **Version Header** must match whatever you configured. This is commonly **api-version**, but you can make it just **v** if you want to like this:

```c#
services.AddApiVersioning(o => o.ApiVersionReader = new HeaderApiVersionReader( "v" ) );
```

I hope that helps

**Comment by SailleshPawar** [comment]
let me try and get back to you.

**Comment by SailleshPawar** [comment]
I have already implemented this.

**Comment by SailleshPawar** [comment]
In the request header the version is being passed as:

Key:v
Value: v2

**Comment by commonsensesoftware** [comment]
You're using different names. Are you saying that **Key** == **Version Identifier** and **Value** == **Version Header** in the UI?  The **Version Header** value or **Value** must be `2`. Just get rid of the `v` and it will work

**Comment by SailleshPawar** [comment]
This how Azure API Management is sending request to the application.
I have just reproduced in local machine.
![image](https://user-images.githubusercontent.com/16855395/81098637-8fe35100-8f01-11ea-8c1f-e23aecbe3af8.png)

Strange part is I can get rid of it manually from APM and everything works fine.
But If I try to set the version identifier in devops release pipeline it fails.

![image](https://user-images.githubusercontent.com/16855395/81098813-cc16b180-8f01-11ea-9a96-3d9bf18e21db.png)

So might be issue of the API Import (Azure) package that we are using to import swagger file.

**Comment by commonsensesoftware** [comment]
Here's what I can say:

- Versioning by header in API Versioning is 100% supported
   - The original use case for that was the legacy Azure header **x-ms-version**
- You can test this in Postman, but specifying `Key=v` and `Value=2` in your header list
- You have several moving parts. To avoid conflation, start with the simplest, working thing and _then_ build up:
   - Start with getting your API to work locally
   - Integrate with OpenAPI/Swagger and make sure that works
   - Integrate with APIM
   - Verify your ADO build definition automates the process correctly

This will narrow down where the problem is. I suspect it's some combination of the OpenAPI document and APIM configuration that is giving you grief.

**Comment by SailleshPawar** [comment]
Thanks @commonsensesoftware 
I wrote a powershell script yesterday and fixed the issue of version identifier.

**Comment by commonsensesoftware** [comment]
Great news! If there's anything else about APIM integration you feel worth sharing, please do so. I occasionally get asked about it, but I don't have much experience with it to guide people. Thanks.
