### ISSUE TITLE
Swagger UI only showing $select and $expand parameters

### ISSUE THREAD

**Issue by ikemtz** [microsoft/aspnet-api-versioning#634]
First off thanks so much for your effort, being a one-man team can be a burden.  In the .net core 2.1 version of this library, you would see all of the parameters you would expect given the correct [EnableQuery] attribute usage ($count, $expand, $top, $sort, etc.).

In the .net core 3.x version, most of these parameters went away and the only two parameters remaining are $select and $expand.  I've tried:
````
  [EnableQuery(MaxTop = 100, AllowedQueryOptions =
      AllowedQueryOptions.Count
      | AllowedQueryOptions.Expand
      | AllowedQueryOptions.Filter
      | AllowedQueryOptions.OrderBy
      | AllowedQueryOptions.Select
      | AllowedQueryOptions.Skip
      | AllowedQueryOptions.Top)]
````
as well as 
````
  [EnableQuery(MaxTop = 100, AllowedQueryOptions = AllowedQueryOptions.All]
````
Both attempts don't work as expected.  I have a GitHub repo for a running OData Microservice:
https://github.com/ikemtz/NurseCron/tree/master/src/MicroServices/Employees/src/IkeMtz.NRSRx.Employees.OData

And here it is running in Azure.
https://im-wa-empo-nrsr.azurewebsites.net/index.html#/Employees/get_odata_v1_Employees

If you can give me a hint on where to l look or anything else that would help, it would be much appreciated.

Thanks,
Isaac Martinez

**Comment by commonsensesoftware** [comment]
First question, are the query options observed and executed they way you expect at runtime? I've observed behaviors in OData, which I can only describe at a bug. It seems like the global and local query options are sometimes incongruent; particularly with `[EnableQuery]`. Model-based query options and global options seem to work.

As an example, I seem to recall that setting `[EnableQuery(AllowedQueryOptions = Count)]` will yield the correct query options in the OpenAPI document, but OData will claim it's not allowed at runtime. If you enable `$count` globally, then it works.

I won't rule out any bugs on the API Versioning side, but I want to make sure you have the expected runtime behavior before diving in. These nuances in OData have left me chasing my tail in the past. ;)

**Comment by commonsensesoftware** [comment]
Following up on this. Did you ever get it working?

Interestingly, I was able to take the query options you are trying to use and applied them to [V3/OrdersController.cs](../blob/master/samples/aspnetcore/SwaggerODataSample/V3/OrdersController.cs#L30). I definitely see `$select` and `$expand` show up when I apply `All`, but not if I don't.

I also noticed that you are using `ODataEnvelope<T>` versus the `ODataValue<T>` provided by the OData API Explorer. There are some considerations for this type. It _may_ be affecting the results. In addition, the `ODataEnvelope<T>` isn't providing an `IEnumerable<T>` result. Again - that _might_ be affecting things.

It's probably worth taking at least one API and line up things in a way we expect it to work and then start tweaking things to see where it might be going wrong.

**Comment by ikemtz** [comment]
Hey Chris,

Thanks for following up.  I was able to implement a workaround in my framework by adding a custom IOperationFilter.  
https://github.com/ikemtz/NRSRx/blob/master/src/IkeMtz.NRSRx.Core.OData/ODataCommonOperationFilter.cs

Here's a sample OData service that's based on my framework (NRSRx) which is based on your library.
https://im-wa-empo-nrcrn.azurewebsites.net/index.html#/Employees/get_odata_v1_Employees

I will try switching it up to use the ODataValue to see if I get the desired results.

Thanks again,
Isaac M

**Comment by commonsensesoftware** [comment]
It sounds like you have a workable solution - one way or the other. [5.0.0-RC.1](https://www.nuget.org/packages/Microsoft.AspNetCore.OData.Versioning/5.0.0-rc.1) is now available with support for _Endpoint Routing_ and a myriad of OData API Explorer fixes. The official release will likely occur after 2 weeks of _burn-in_. Feel free to reopen this or open a new issue if you continue to face issues. Thanks.

**Comment by strandman** [comment]
> Interestingly, I was able to take the query options you are trying to use and applied them to [V3/OrdersController.cs](../blob/master/samples/aspnetcore/SwaggerODataSample/V3/OrdersController.cs#L30). I definitely see `$select` and `$expand` show up when I apply `All`, but not if I don't.

SwaggerODataSample  [V3/OrdersController.cs] is not working, because the entity [Order] is not allowed to perform for example Top or Count

If you for example add order.Select().Filter().OrderBy() in [OrderModelConfiguration], you will se that this will honor over [EnableQuery(AllowedQueryOptions = Select)] in the swagger documentation, which is wrong. Swagger should only display '$select'.
