### ISSUE TITLE
OData query paramaters formatting in swagger ui

### ISSUE THREAD

**Issue by Graph2133** [microsoft/aspnet-api-versioning#640]
Hi! I've a question about formatting of odata query parameters.
I'm using ODataApiExplorer which allows me to generate swagger Open API schema but generated routes do not have 'canonical' look in swagger ui [https://www.odata.org/documentation/odata-version-3-0/url-conventions/](url). 
![image](https://user-images.githubusercontent.com/23173060/84763756-607e3480-afd5-11ea-85c0-c5946e597bf2.png)

Is there any possibility (out of the box) to display routes like `odata/Products({key})` and more complex scenarios like `odata/Products({key})/Something({key})` without adding an ODataRoute attribute for example:  `[ODataRoute("({key})")]`. 

Please note that both routes should work `Products/key` and `Products({key}) ` but from swagger I want to see only second version.

Expected look, after adding ODataRoute attribute
 
![image](https://user-images.githubusercontent.com/23173060/84765591-206c8100-afd8-11ea-82ff-b2fc1c522ec6.png)

After some investigation I've noticed that changing of UrlKeyDelimiter  will fix an issue with displaying of in swagger ui but the problem is that routes like Products/key become broken and I receive 404 status code, Products({key}) works fine.
```
routeBuilder.ServiceProvider
            .GetRequiredService<ODataOptions>()
            .UrlKeyDelimiter = ODataUrlKeyDelimiter.Parentheses;
```

Currently I'm using following versions of nuget packages:
```
 <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.2.1" />
 <PackageReference Include="Microsoft.AspNetCore.OData.Versioning.ApiExplorer" Version="4.0.0" />
  <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-rc2" />
```
I

**Comment by commonsensesoftware** [comment]
To my knowledge, you cannot configure OData to use both key segment styles. It can be either a slash or parentheses. Explicit attributes will always trump convention-based behaviors. The default style in the Microsoft implementation has been a slash for a while now, presumably to more closely align with conventional URLs.

Even if OData could support both at the same time, this would be difficult for API Explorer to handle. The behaviors are driven by whether you use attributes.

That's probably not the answer you're looking for, but hopefully that clarifies things.

**Comment by Graph2133** [comment]
Thanks ! Probably custom swashbuckle document filter may also be considered as a solution
