### ISSUE TITLE
.Net Core 3.0 Error No route matches the supplied values.

### ISSUE THREAD

**Issue by fMboys99** [microsoft/aspnet-api-versioning#646]
I'm using .Net Core 3.0 for a WebApi project, if I return a CreateAtRoute result then it fails with a "No route matches the supplied values" error.
Here are Get & Post methods of my MessagesController.

        [HttpGet("{id}", Name = "GetMessage")]
        public async Task<IActionResult> GetMessage(int userId, int id)
        {
            if (userId != int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value))
            return Unauthorized();

            var messageFromRepo = await _repo.GetMessage(id);

            if (messageFromRepo == null)
                return NotFound();

            return Ok(messageFromRepo);
        }

        [HttpPost]
        public async Task<IActionResult> CreateMessage(int userId, MessageForCreationDto messageForCreationDto)
        {
            if (userId != int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value))
            return Unauthorized();

            messageForCreationDto.SenderId = userId;

            var recipient = await _repo.GetUser(messageForCreationDto.RecipientId);

            if(recipient == null)
                return BadRequest("Could not find user");

            var message = _mapper.Map<Message>(messageForCreationDto);

            _repo.Add(message);

            if (await _repo.SaveAll())
                return CreatedAtRoute("GetMessage", new {id = message.Id}, message);

                throw new Exception("Creating the message failed at save");

        }

When call the CreateMessage method this then generates the exception:

      
      fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
     System.InvalidOperationException: No route matches the supplied values.
     at Microsoft.AspNetCore.Mvc.CreatedAtRouteResult.OnFormatting(ActionContext context)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult 
    result, Type  objectType, Object value)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
    at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, 
    Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
    --- End of stack trace from previous location where exception was thrown ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, 
    Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
    --- End of stack trace from previous location where exception was thrown ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker 
    invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task 
    task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint 
    endpoint, Task requestTask,  ILogger logger) at Microsoft.AspNetCore.Authorization. 
    AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication. 
    AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics. 
    DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Please help I'm stuck on it.

**Comment by fMboys99** [comment]
@commonsensesoftware can you help me with this.

**Comment by commonsensesoftware** [comment]
You didn't show the controller, which is a critical part of the question; however, without seeing it, I'd bet money that you're versioning by URL. This is one of the common issues with versioning that way. The API Version route parameter is _special_ so you need to provide it when generating routes. In addition, I highly recommend using `CreatedAtAction` over `CreatedAtRoute`. The route table is **not** API version-aware.

Things should work with these adjustments.

```c#
[HttpGet("{id}")]
public async Task<IActionResult> GetMessage(int userId, int id)
{
   // ommitted
}

[HttpPost]
public async Task<IActionResult> CreateMessage(
    int userId,
    MessageForCreationDto messageForCreationDto,
    ApiVersion version)
{
    // ...

   return CreatedAtAction(nameof(GetMessage), new {id = message.Id, version = version.ToString()}, message);

    // ...
}
```

**Comment by fMboys99** [comment]
Thanks for your help @commonsensesoftware 
here is my controller so you better guide me.

    [ServiceFilter(typeof(LogUserActivity))]
    [Authorize]
    [Route("api/users/{userId}/[controller]")]
    [ApiController]
    public class MessagesController : ControllerBase
    {
        private readonly IDatingRepository _repo;
        private readonly IMapper _mapper;
        public MessagesController(IDatingRepository repo, IMapper mapper)
        {
            _mapper = mapper;
            _repo = repo;          
        }

**Comment by fMboys99** [comment]
Really appreciated your effort. Thanks

**Comment by commonsensesoftware** [comment]
Unless I misunderstood your response, my answer solved your issue. If not, I'm happy to re-open this and help you resolve the problem. Thanks.
