### ISSUE TITLE
Endpoint routing with apiversioning support for OData core 7.4.1

### ISSUE THREAD

**Issue by dxynnez** [microsoft/aspnet-api-versioning#647]
Endpoint routing for OData core seems to be supported since 7.4.0, I am just wondering whether the apiversioning can work with it or not?

I have the following code in my startup:

```         
            services.AddApiVersioning(options =>
            {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true;
                options.DefaultApiVersion = new ApiVersion(1, 0);
            });

            services.AddVersionedApiExplorer(options =>
            {
                options.GroupNameFormat = "'v'VVV";
                options.SubstituteApiVersionInUrl = true;
            });

            services.AddODataApiExplorer(options =>
            {
                options.GroupNameFormat = "'v'VVV";
                options.SubstituteApiVersionInUrl = true;
            });

            services.AddOData().EnableApiVersioning();

            services.AddControllers(options =>
                {
                    foreach (var outputFormatter in options.OutputFormatters.OfType<ODataOutputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
                    {
                        outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                    }

                    foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
                    {
                        inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                    }
                }).AddControllersAsServices().SetCompatibilityVersion(CompatibilityVersion.Latest);
```
And
```            
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.Select().Filter().OrderBy().Count().MaxTop(10);
                endpoints.MapODataRoute("odata", "odata", this.GetEdmModel());
                endpoints.EnableDependencyInjection();
            });
```

I can sort of get the ApiVersioning to work for a GET OData API, but it doesn't seem to work for POST - I always hit the following NRE:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy.EvaluateApiVersion(CandidateSet candidates, ApiVersion apiVersion)
   at Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
```

NOTE: even for the get API, it doesn't work properly - If I call the GET API with a non-existent version, I get the same NRE.

Did I misconfig something or it's indeed not supported? Thanks in advance!

**Comment by dxynnez** [comment]
Hi @commonsensesoftware , can you take a look at this?

**Comment by Mhirji** [comment]
@dxynnez , from my understanding, Endpoint routing with OData is not supported at this time.
  
https://github.com/microsoft/aspnet-api-versioning/issues/613
https://github.com/microsoft/aspnet-api-versioning/issues/616

From the issues, it looks like @commonsensesoftware will be looking at it, but has not had a chance as yet.  He has made a comment in in one of the above issues that it might just work, but without MapVersionedODataRoutes being implemented, unless you have only one version, I am not sure how it does.  I should say that I could very well be wrong about this point, and if you have got it somewhat working, I would be interested to see what you have done as in my case I only have GET requests.

**Comment by david-ernstsson-stratsys** [comment]
Having the exakt same issue and I cant for the world figure out how to solve it. Still no solution available for Microsoft.AspNetCore.OData 7.4.1 and Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer? Real shame

**Comment by david-ernstsson-stratsys** [comment]
After looking through some code I found out how to do it. Order of registration is important, below code seems to work perfectly

```csharp        
public static IServiceCollection AddCustomApiVersioning(this IServiceCollection services)
        {
            services.AddVersionedApiExplorer(
                options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });

            services.AddApiVersioning(o =>
            {
                o.ReportApiVersions = true;
                o.AssumeDefaultVersionWhenUnspecified = true;
                o.DefaultApiVersion = new ApiVersion(1, 0);
            });

            //services.AddOData().EnableApiVersioning() MUST come after services.AddApiVersioning
            services.AddOData().EnableApiVersioning();

            services.AddODataApiExplorer(
                options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });
            return services;
        }
```

**Comment by StevenLiekens** [comment]
@david-ernstsson-stratsys can you include a sample of your IApplicationBuilder code? I can't get it to work.

**Comment by rusdawg400** [comment]
@david-ernstsson-stratsys Can you show and example of where you are setting up the Version in the URL?

**Comment by david-ernstsson-stratsys** [comment]
@StevenLiekens  @rusdawg400 Fully working code above.

Also note that `builder.EntitySet<WeatherForecast>("WeatherForecast");` cant be changed to WeatherForecasts (with an s at the end) or anything similar change or it'll fail

**Comment by StevenLiekens** [comment]
@david-ernstsson-stratsys, there's still a problem because you can't use `VersionedODataModelBuilder` in the call to `MapODataRoute`.

I've tried many different things and I feel confident to say that there's no way to get API versioning to work with OData endpoint routing right now.

**Comment by commonsensesoftware** [comment]
[5.0.0-RC.1](https://www.nuget.org/packages/Microsoft.AspNetCore.OData.Versioning/5.0.0-rc.1) is now available with support for _Endpoint Routing_. There are some significant changes. Be sure to review the release notes and sample applications. The official release will likely occur after 2 weeks of _burn-in_. Please report any difficulty as a new issue. Thanks.
