### ISSUE TITLE
Microsoft.AspNet.WebApi.Versioning DefaultInlineConstraintResolver in VB.NET

### ISSUE THREAD

**Issue by grgrcn** [microsoft/aspnet-api-versioning#648]
I need to use Microsoft.AspNet.WebApi.Versioning in VB.NET but I cannot translate the following code:

config.AddApiVersioning(o =>
{
   o.AssumeDefaultVersionWhenUnspecified = true;
   o.DefaultApiVersion = new Microsoft.Web.Http.ApiVersion(1, 0);
});

var constraintResolver = new DefaultInlineConstraintResolver()
{
   ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) }
};
config.MapHttpAttributeRoutes(constraintResolver);

In particular I have an error when I define DefaultInlineConstraintResolver, maybe the translation is wrong...

Dim constraintResolver = New DefaultInlineConstraintResolver() With
{
   .ConstraintMap = { ["apiVersion"] = GetType(ApiVersionRouteConstraint) }
}

How resolve? Tks.

**Comment by commonsensesoftware** [comment]
My VB is a little rusty, but if I'm not mistaken, this would be the translation:

```vbnet
config.AddApiVersioning(
  Sub(options)
    options.AssumeDefaultVersionWhenUnspecified
    options.DefaultApiVersion = new ApiVersion(1, 0) ' FYI, this is already the default
  End Sub
)
```
C# has a 2 forms of dictionary initializers. There's the original key/pair form, which is also supported by VB.NET and a new indexer assignment style, which I do not believe VB.NET supports. This _should_ be the translation:

```vbnet
Dim constraintResolver = New DefaultInlineConstraintResolver() With
{
  .ConstraintMap From {{"apiVersion", GetType(ApiVersionRouteConstraint)}}
}
```

Alternatively, you can just use:

```vbnet
Dim constraintResolver = New DefaultInlineConstraintResolver()
constraintResolver.ConstraintMap.Add("apiVersion", GetType(ApiVersionRouteConstraint))
```

I hope that helps

**Comment by grgrcn** [comment]
Thank you very much Chris,
with your suggestion I solved it.
I used the second solution:

```
Dim constraintResolver = New DefaultInlineConstraintResolver()
constraintResolver.ConstraintMap.Add("apiVersion", GetType(ApiVersionRouteConstraint))
```
because the first one you suggest gives me some errors:

![image](https://user-images.githubusercontent.com/64634677/88038200-2d840f00-cb46-11ea-8337-8e4612141921.png)

Thanks again.

G.

**Comment by commonsensesoftware** [comment]
Sweet! Glad you got it working.

**Comment by grgrcn** [comment]
Tks, 
I close the issue... ;)
