### ISSUE TITLE
API Version Selector Documentation Misleading

### ISSUE THREAD

**Issue by AndrewKnieriem** [microsoft/aspnet-api-versioning#649]
https://github.com/microsoft/aspnet-api-versioning/wiki/API-Version-Selector says for the "Default" and "Constant" version selectors that the specified version will be selected "_regardless of the request or available API version information_". I don't believe this is true as all the version selectors only are used when a version is not specified in the request. 

In my example I'm using Microsoft.AspNetCore.Mvc.Versioning Version=4.1.1, I have 2 controllers, with version 1.0 and version 2.0 with the constant version selector set to 1.0;

GET /api/values?api-version=1.0  => controller 1.0
GET /api/values?api-version=2.0  => controller 2.0   < according to the documentation, this should be 1.0
GET /api/values                             => controller 1.0

**Comment by commonsensesoftware** [comment]
Yes - and no ...

With respect to the _design_, the **IApiVersionSelector** _can_ be used in any number of scenarios. Currently (and perhaps always), the only scenario where that is relevant is when no API version has been specified **and** that behavior is allowed (a la `ApiVersioningOptions.AssumeDefaultVersionWhenUnspecified`). If a client asks for `1.0` explicitly, the server should **never** be allowed to arbitrarily match something else - not even by the **IApiVersionSelector**. The one exception to this rule is something that is _API version-neutral_, which accepts any and all versions, including no version at all. There can only ever be one such implemented action that handles such a request, so the **IApiVersionSelector** isn't useful there.

With respect to the documentation, the descriptions are _probably_ clear, but the differences or use cases _might_ not be.

- **Default**: simply maps to `ApiVersioningOptions.DefaultApiVersion` - **always**
- **Constant**: maps to an explicitly specified **ApiVersion**, which _should_ be different from `ApiVersioningOptions.DefaultApiVersion` (the use cases for this are arguably very low)

I hope that helps clarify things. If you think there is an opportunity for additional, clarifying language, I'm happy to oblige. I don't mind discussing additional ways the **IApiVersionSelector** can be used, but pretty much every other use case thus far has led down a path that didn't make sense or negated all the benefits of versioning in the first place. The primary use case is a satisfy a hook for: _"If no API version is provided, which one should be selected?"_. Once API versioning is enabled, **every** action has at least one corresponding API version - implicit or explicit, unless they are API version-neutral (which accept all versions).

**Comment by AndrewKnieriem** [comment]
Hi @commonsensesoftware, thanks for the reply. That's good information to know. I think it's just the "_regardless of the request or available API version information_" that is misleading to me. As you said if a client requests version 1, then IApiVersionSelector is basically out of the picture. Maybe some more clarity around what "regardless of the request" means in that scenario. 

My team was initially going to try "upgrading" clients by using the version selector to push clients up to newer non-breaking versions, but have decided on a better strategy since. 

The document also says "This service is **typically** only used when a client has not requested an explicit API version", but having that guidance to **only** use it when no version is specified could clarify the role of the version selector. 

Thanks!

**Comment by commonsensesoftware** [comment]
I've added some clarifying text to the wiki that indicates when the **IApiVersionSelector** is currently used. Hopefully that clears things up for others in the future. If you think this still isn't enough, let me know and I can elaborate further. Thanks.
