### ISSUE TITLE
CreatedAtAction returns wrong location when versioning by url segment with multiple routes

### ISSUE THREAD

**Issue by defteame** [microsoft/aspnet-api-versioning#651]
I have versioning specified as follows:

Configuration:
```
services.AddControllers(opts => { opts.SuppressAsyncSuffixInActionNames = false; });
services.AddApiVersioning(opts =>
               {    
                     opts.ApiVersionReader = new UrlSegmentApiVersionReader();
                     opts.AssumeDefaultVersionWhenUnspecified = true;
                     opts.DefaultApiVersion = new ApiVersion(1, 0);
                });
```
Controller:
```
[ApiVersion("1")]
[Route("[controller]")]
[Route("{version:apiVersion}/[controller]")]
[ApiController]
public class TestController : ControllerBase

//...

public async Task<ActionResult> CreateAsync([FromBody] Item item, ApiVersion version)
{
	...
	return this.CreatedAtAction(nameof(this.GetByIdAsync), new { id = item.Id, version = version.ToString()}, item);
}

//...

[HttpGet("{id:int}")]
public async Task<ActionResult<Item>> GetByIdAsync([FromRoute] int id)
{
	Item item = await this.repo.GetByIdAsync(id);
	return this.Ok(item);
}
```
The problem is, version in location header of CreateAsync response is specified as query:
`location: http://localhost/Item/1?version=1`

When i only leave
`[Route("{version:apiVersion}/[controller]")]`
location generates correctly:
`location: http://localhost/1/Item/1 `

Is there a way to force it to generate correct location while having multiple routes in controller?
I use multiple routes to overcome this limitation: https://github.com/microsoft/aspnet-api-versioning/wiki/Known-Limitations#url-path-segment-routing-with-a-default-api-version

**Comment by commonsensesoftware** [comment]
Without testing it, but based on your example, I'm 99% sure this is caused by the known, breaking change: [Async suffix trimmed from controller action names](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#mvc-async-suffix-trimmed-from-controller-action-names). It affects link generation. Everything else looks correct to me.

**Comment by defteame** [comment]
@commonsensesoftware Well i tried to do it without SuppressAsyncSuffixInActionNames set, using hardcoded action name, with same result.
It seems it's not really related to this change. 

I tried to test it on BasicSample example from samples (which don't have SuppressAsyncSuffixInActionNames set), changing it as follows:
```
Startup:
...
options.AssumeDefaultVersionWhenUnspecified = true;
...
HelloWorldController:

[ApiController]
[ApiVersion( "1.0" )]
[Route("api/[controller]")]
[Route( "api/v{version:apiVersion}/[controller]" )]
public class HelloWorldController : ControllerBase
```

Location header that returns:
`http://localhost:1237/api/HelloWorld/42?version=1`

**Comment by commonsensesoftware** [comment]
I see ... with double route registration, I'm not sure how the routing system decides which one to use. It _might_ be the first one it finds, which means the order might matter. You can try controlling that with the `RouteAttribute.Order` property. I'm not sure how or if you can make route names works in this scenario. The only sure fire way is to build the route yourself. You may need to create your own extension method to deal with this. It's pretty straight forward to do.

>This is an other example of the grief that versioning by URL causes. If you have the option, I would reconsider. No other versioning method has this problem.

**Comment by defteame** [comment]
@commonsensesoftware It seems route order worked, thank you!
