### ISSUE TITLE
Passing  api-version in Batch API

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [microsoft/aspnet-api-versioning#655]
My API will support api-version in header not in query string. I am trying to use batch API for calling my api's .When i passed api-version in header it is not supporting .

**Sample request Body for Batch:**

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http; msgtype=request

GET /api/abc/PMBB HTTP/1.1
Host:  localhost:34876
api-version:2018-01-13

GET /api/abc/PMBN HTTP/1.1
Host:  localhost:34876
api-version:2018-01-13

--batch_36522ad7-fc75-4b56-8c71-56071383e77b--

**Response Error message**

{"Error":{"Code":"ApiVersionUnspecified","Message":"An API version is required, but was not specified."}}
--6515da49-b7ed-4c7c-9dc2-d139e88b67a4--

**Comment by commonsensesoftware** [comment]
You haven't specified, but I presume this is for ASP.NET Core. To my knowledge, batching _just works_ in ASP.NET Web API. For OData in ASP.NET Core, you have to make some changes to the order and way that the middleware is registered. The correct configuration is documented in the wiki [here](../wiki/OData-Batching).

**Comment by commonsensesoftware** [comment]
Did this suggestion solve your issue?

**Comment by commonsensesoftware** [comment]
It would seem you resolved the issue or abandoned your approach.

You didn't provide any details about your setup, but I see 2 possible issues:

1. Make sure you've configured the **HeaderApiVersionReader**. I assume you already had this working for non-batch scenarios.
2. Make sure you disabled automatic middle registration and explicitly register it after OData (as linked to in the wiki above)

The batch endpoint itself has no version and, in fact, isn't even a controller - it's middleware. I see that each individual request is specifying an API version. This is the correct behavior. This _Uniform Interface_ constraint allows a client to make a single request this way where each request _might_ be a different API version, even those they are the same in your example. If you want a different behavior, you'll probably have to customize the OData batch handler.

If this doesn't solve your problem, we can re-open the issue and walk through additional details.

Thanks
