### ISSUE TITLE
Adding additional context specific to api-version

### ISSUE THREAD

**Issue by kilroyFR** [microsoft/aspnet-api-versioning#661]
Great API so far.
Just one question.
I am using http header to version my API (api-version). But we deliver same API for all our customers.
But sometimes some of our customers have special needs that we would not like to make available to all customers).

We would like to add an additional parameter in the http header to specifify some custom project oriented features (not available to everyone). Is there a way to add this ? (it would be like adding an 'api-project' parameters that would work in conjunction with api-version).

**Comment by commonsensesoftware** [comment]
The scenario you are describing sounds like it would be better served by some form of authorization. This would keep your implementation from exploding (version * customer mapping). Knowing the customer appears to be some type of filter. There are several ways this can be achieved, but this is the one I would probably go with.

In a similar fashion, you could just add a whole other HTTP header. Something like `tenant: contoso`. The only problem with this is that any who knows the tenant names can request it without restriction. This takes things back to first suggestion. If you can make this work, it's simpler than conflating the parameter with an API version.

To answer your question, if you _really_ want a header parameter, then - yes - it's possible. To implement that, you'll almost certainly need a custom **IApiVersionReader**. You might be able to extend the existing **HeaderApiVersionReader**. To keep things simple, use a _real_ header parameter. It _might_ look something like: `api-version: 1.0; tenant=contoso`. In theory, this may work _as is_, but I haven't tried it. You'll certainly need something to read the header parameter value.

Hopefully this gives you a few ideas.

**Comment by kilroyFR** [comment]
Thanks i now have to try what's best for me. Many thanks for your time
