### ISSUE TITLE
Conflict with AutoFac and UseEndpointRouting

### ISSUE THREAD

**Issue by redtaped** [microsoft/aspnet-api-versioning#664]
When adding .AddApiVersioning(), it causes this error when registering routes with UseEndpointRouting(builder => builder.MapControllerRoute(xxx))

> System.ObjectDisposedException: 'This resolve operation has already ended. When registering components using lambdas, the IComponentContext 'c' parameter to the lambda cannot be stored. Instead, either resolve IComponentContext again from 'c', or resolve a Func<> based factory to create subsequent components from.'

**Comment by commonsensesoftware** [comment]
I'm afraid this isn't enough context to provide any meaningful feedback - yet. This appears to be something related to AutoFac, which I don't have much experience with. API versioning doesn't do anything all that special for _Endpoint Routing_. In fact, it's less and much simpler than the old **IRouter** model.

- Do you have a full stack trace?
- Which component or registration triggered this?
- Do you have a repro?

The API Versioning libraries support SourceLink as well. That may help debug this type of issue.

**Comment by redtaped** [comment]
Upon researching this, the error is not a defect in aspnet-api-versioning package.
When adding .AddApiVersioning() it is indirectly causing MvcDataAnnotationsLocalizationOptions to be resolved before the first views are, and that's exposing an issue with how I've registered that in autofac. I need to figure out how to fix, but it's clearly not an issue with this library.
