### ISSUE TITLE
VersionedApiExplorer.InitializeApiDescriptions() throws null object exception

### ISSUE THREAD

**Issue by KeithBarrows** [microsoft/aspnet-api-versioning#666]
> Object reference not set to an instance of an object.
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

> Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

> Line 50:                         versionBuilder =>
> Line 51:                         {
> Line 52:                             foreach (var group in apiExplorer.ApiDescriptions)
> Line 53:                             {
> Line 54:                                 var description = "";

> [NullReferenceException: Object reference not set to an instance of an object.]
>    System.Object.GetType() +0
>    Microsoft.Web.Http.Routing.ParsedRouteAdapter`1.Bind(IDictionary`2 currentValues, IDictionary`2 values, HttpRouteValueDictionary defaultValues, HttpRouteValueDictionary constraints) +136
>    Microsoft.Web.Http.Description.VersionedApiExplorer.TryExpandUriParameters(IHttpRoute route, IParsedRoute parsedRoute, ICollection`1 parameterDescriptions, String& expandedRouteTemplate) +2463
>    Microsoft.Web.Http.Description.VersionedApiExplorer.PopulateActionDescriptions(HttpActionDescriptor actionDescriptor, IHttpRoute route, String localPath, Collection`1 apiDescriptions, ApiVersion apiVersion) +181
>    Microsoft.Web.Http.Description.VersionedApiExplorer.ExploreDirectRouteControllers(HttpControllerDescriptor controllerDescriptor, IReadOnlyList`1 candidateActionDescriptors, IHttpRoute route, ApiVersion apiVersion) +464
>    Microsoft.Web.Http.Description.VersionedApiExplorer.InitializeApiDescriptions() +777
>    System.Lazy`1.CreateValue() +708
>    System.Lazy`1.LazyInitValue() +184
>    Citrix.Transaction.Api.<>c__DisplayClass0_0.<Register>b__2(VersionInfoBuilder versionBuilder) in C:\devteam\transaction\API\Citrix.Transaction\Citrix.Transaction.Api\App_Start\SwaggerConfig.cs:52
>    Citrix.Transaction.Api.<>c__DisplayClass0_0.<Register>b__0(SwaggerDocsConfig c) in C:\devteam\transaction\API\Citrix.Transaction\Citrix.Transaction.Api\App_Start\SwaggerConfig.cs:48
>    Swashbuckle.Application.HttpConfigurationExtensions.EnableSwagger(HttpConfiguration httpConfig, String routeTemplate, Action`1 configure) +99
>    Citrix.Transaction.Api.SwaggerConfig.Register(HttpConfiguration config) in C:\devteam\transaction\API\Citrix.Transaction\Citrix.Transaction.Api\App_Start\SwaggerConfig.cs:44
>    Citrix.Transaction.Api.Startup.Configuration(IAppBuilder app) in C:\devteam\transaction\API\Citrix.Transaction\Citrix.Transaction.Api\App_Start\Startup.cs:34

It appears the Route table is not yet populated.  I have the exact same code in 2 different API solutions and in one it runs just fine, but in this one it bombs.  

I wanted to step through the code in VersionedApiExplorer but am having a hard time getting VS2015/VS2017 setup to do that.

If I switch to the Single version setup (see below) everything runs fine.  When I try the multi version I get the null exception on startup.

Here is what I have setup for Swagger config:

```
public static void Register(HttpConfiguration config)
{
    var xmlDocPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"bin\Citrix.Transaction.Api.xml");
    var simpleApiExplorer = config.Services.GetApiExplorer();
    var apiExplorer = new VersionedApiExplorer(config);  // <-- the error is in this object!
    config.Services.Replace(typeof(IApiExplorer), apiExplorer);

    config.EnsureInitialized();

    config
        .EnableSwagger("{apiVersion}/swagger", c =>
        {
            //c.SingleApiVersion("v1", "Citrix.Transaction.Api - V1 End Points");
            c.MultipleApiVersions((apiDesc, version) =>
                apiDesc.GetGroupName() == version,
                versionBuilder =>
                {
                    foreach (var group in apiExplorer.ApiDescriptions)
                    {
                        var description = "";
                        if (group.IsDeprecated) description += "This API deprecated";

                        versionBuilder.Version(group.Name, $"Citrix.Transaction.Api - v{group.ApiVersion} End Points")
                            .Description(description);
                    }
                });
            c.GroupActionsBy(apiDesc =>
            {
                var attr = apiDesc.GetControllerAndActionAttributes<DisplayNameAttribute>().FirstOrDefault();
                // use controller name if the attribute isn't specified
                return attr?.DisplayName ?? apiDesc.ActionDescriptor.ControllerDescriptor.ControllerName;
            });
            c.ApiKey("Bearer").Description("API Key Authentication").Name("Authorization").In("header");
            c.OperationFilter<AddRequiredHeaderParameter>();  // Make sure CKey is visible
            c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
            c.UseFullTypeNameInSchemaIds();
            c.OperationFilter<AssignBearerAuthSecurityRequirement>();
            c.RootUrl(req => ResolveFullUrl(req, "/TransactionApi2"));
            c.IncludeXmlComments(xmlDocPath);
            c.DocumentFilter<VersionFilter>();
            c.OperationFilter<VersionOperationFilter>();
            c.Schemes(new[] { "https" });
        })
        .EnableSwaggerUi(c =>
        {
            c.DisableValidator();
            c.EnableApiKeySupport("Authorization", "header");
            c.EnableDiscoveryUrlSelector();
        });

    config.EnsureInitialized();
}

```

**Comment by commonsensesoftware** [comment]
Based on your code, my best guess is that you've missed something in the setup. Is there some reason you are creating the **VersionedApiExplorer** instead of calling the extension method `var apiExplorer = configuration.AddVersionedApiExplorer();` as [shown in the example](../blob/master/samples/webapi/SwaggerWebApiSample/Startup.cs#L37)?

In addition, I don't see API Versioning setup via the first call to `configuration.AddApiVersioning()`. The **VersionedApiExplorer** will not work without it. You should _add_ API versioning before attempting to add or create the **VersionedApiExplorer**.

**Comment by commonsensesoftware** [comment]
If you want to debug things, all of the libraries support SourceLink. You need to make sure you have the **Enable Source Link Support** option checked. You also need to make sure the **Just My Code** option is **not** checked. For additional details, have a look at [Scott Hanselman's article](https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx).

**Comment by KeithBarrows** [comment]
Thanks for the link to Scott's article!

Let me see if I can further clarify the code base I inherited as the `AddApiVersioning(...)` is done in a different, earlier, config step:

```
    public class Startup
    {
        /// <summary>
        /// Configures the specified application.
        /// </summary>
        /// <param name="app">The application.</param>
        public void Configuration(IAppBuilder app)
        {
            app.UseCors(CorsOptions.AllowAll);

            ConfigureOAuth(app);

            GlobalConfiguration.Configure(config =>
            {
                WebApiConfig.Register(config);
                app.UseNinjectMiddleware(NinjectWebCommon.CreateKernel);
                app.UseNinjectWebApi(config);
                app.UseWebApi(config);
                SwaggerConfig.Register(config);
            });
        }

        private void ConfigureOAuth(IAppBuilder app)
        {
            app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions());
        }
    }
```

```
    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API routes
            var constraintResolver = new DefaultInlineConstraintResolver
            {
                ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) }
            };
            constraintResolver.ConstraintMap.Add("apiVersionConstraint", typeof(ApiVersionContstraint));
            config.MapHttpAttributeRoutes(constraintResolver);

            // Reporting api versions will return the headers "api-supported-versions" and "api-deprecated-versions"
            config.AddApiVersioning(o => o.ReportApiVersions = true);

            // Formatting
            config.Formatters.Remove(config.Formatters.XmlFormatter);
            config.Formatters.Remove(config.Formatters.JsonFormatter);

            var jsonFormatter = new MaxDepthJsonFormatter
            {
                SerializerSettings = { NullValueHandling = NullValueHandling.Include }
            };
            config.Formatters.Add(jsonFormatter);
        }
    }
```

Will be trying to step through code once I get it setup correctly.

**Comment by KeithBarrows** [comment]
I have tried stepping into `apiExplorer.ApiDescriptions` several times now and each time Visual Studio locked up completely, requiring a reboot.

```
config
    .EnableSwagger("{apiVersion}/swagger", c =>
    {
        //c.SingleApiVersion("v1", "Citrix.Transaction.Api - V1 End Points");
        c.MultipleApiVersions((apiDesc, version) =>
            apiDesc.GetGroupName() == version,
            versionBuilder =>
            {
                foreach (var group in apiExplorer.ApiDescriptions)  // <-- trying to step in here, get's to the virtual property and locks up
                {
                    var description = "";
                    if (group.IsDeprecated) description += "This API deprecated";

                    versionBuilder.Version(group.Name, $"Citrix.Transaction.Api - v{group.ApiVersion} End Points")
                        .Description(description);
                }
            });
        c.GroupActionsBy(apiDesc =>
...
```

**Comment by commonsensesoftware** [comment]
Based on what you originally said, I assume it's VS2017? I've been exclusively using VS2019 for almost 2 years so I can't speak to the experience anymore. I do know that the first time symbols are loaded, the debugger loads a **ton** and it can be very, very slow. I've seen it take minutes. Usually there is either a load/progress dialog and/or the bottom left-hand corner will be flashing the symbols of all the libraries being processed.

If everything else is configured correctly, you can try:

`Debug → Windows → Modules` or `CTRL+D, M`

Then explicitly load the symbols for API Versioning ahead of time. Hopefully that will make a difference.

**Comment by commonsensesoftware** [comment]
It seems this issue has been resolved or abandoned. In terms of ordering, things need to be registered in this order:

1. `configuration.AddApiVersioning();`
2. `configuration.AddVersionedApiExplorer();`

It's find if you're using DI, but it's a not first-class concept in Web API. This makes the order of registrations a bit tricky. I also see calls to `configuration.EnsureInitialized()`. In general, this should **not** be called explicitly. It will be called when necessary by the infrastructure. It has _run once_ semantics, but you are calling it at least twice. Removing this call completely or delaying it until the very end may help.

This will replace the following standard services:

- **IHttpControllerSelector**
- **IHttpActionSelector**
- **IApiExplorer**

You can access the **IApiExplorer** at other times, but the result from `configuration.AddVersionedApiExplorer()` is the time you can safely get the type implementation. Accessing it later will require you to cast to the concrete type to get things grouped or rely on the flat list being collated the way you want.

In terms of debugging, the process may be slow, but it does work. It's not clear which VS version you were using. If you're stuck on VS2017, you _might_ consider trying to use VS2019 Community Edition (free) to see if it makes a difference. After VS2017, installations can safely be installed side-by-side.

I hope that helps. If you come back and are still stuck, we can reopen the issue and dive in further.

Thanks
