### ISSUE TITLE
Odata versioning (Microsoft.AspNetCore.OData.Versioning 5.0.0-rc.1) return error UnsupportedApiVersion

### ISSUE THREAD

**Issue by quybmt2003** [microsoft/aspnet-api-versioning#674]
I have a versioned OData API with version 5.0.0-rc.1 using ASP.NET Core 3.1.

I used to call MapVersionedODataRoutes in the EndpointRouteBuilder parameter of UseEndpoints() with configuration as below

Startup.cs:
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers(options => options.EnableEndpointRouting = false).AddNewtonsoftJson();
            services.AddApiVersioning(options =>
            {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true;
            });

            services.AddVersionedApiExplorer(options => ConfigureApiExplorer(options));
            services.AddOData().EnableApiVersioning();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, VersionedODataModelBuilder modelBuilder)
        {
            if (!env.IsDevelopment())
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseCors();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseApiVersioning();
            app.UseEndpoints(endpoints =>
            {
                endpoints.EnableDependencyInjection();
                endpoints.Select().Expand().Filter().OrderBy().Count();
                endpoints.MapVersionedODataRoutes("odata-url-segment-version", "api/v{version:apiVersion}", modelBuilder.GetEdmModels()); 
            });
        }

Entity Configuration:
    public class UserConfiguration : IModelConfiguration
    {
        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string routePrefix)
        {
            Configure(builder);
        }

        private void Configure(ODataModelBuilder builder)
        {
            var config = builder
                .EntitySet<User>(nameof(User))
                .EntityType;

            config.CollectionProperty(m => m.Id);
            config.CollectionProperty(m => m.Name);

            config
                .Filter(QueryOptionSetting.Allowed)
                .OrderBy(QueryOptionSetting.Allowed)
                .Count(QueryOptionSetting.Allowed)
                .Select(SelectExpandType.Allowed)
                .Expand(SelectExpandType.Disabled)
                .Page();
        }
    }

Api endpoint: 
Method get: http://localhost:5000/api/v1.0/UserOdata

Response with error:
{
    "error": {
        "code": "UnsupportedApiVersion",
        "message": "The HTTP resource that matches the request URI 'http://localhost:5000/api/v1.0/UserOdata' does not support the API version '1.0'.",
        "innerError": null
    }
}

Could you help me to identify what I'm doing wrong? Many thanks

**Comment by commonsensesoftware** [comment]
What does your controller look like? The route suggests it's called `UserOData`, but the registered entity set is `User`.

**Comment by quybmt2003** [comment]
My controller is UserOdataController inheriting from ODataController. You mean controller name should be the same as resgistered entity name, should it be UserController instead of UserOdataController?

**Comment by commonsensesoftware** [comment]
Yes. This is a basic concept of how routing works with OData. API Versioning does not change anything with the way that works.

**Comment by quybmt2003** [comment]
Aha, I changed the controller name according Entity Name. So it is working now. I think we should close this issue. Thank you so much for your help!

**Comment by quybmt2003** [comment]
> Yes. This is a basic concept of how routing works with OData. API Versioning does not change anything with the way that works.

Aha, I changed the controller name according Entity Name. So it is working now. I think we should close this issue. Thank you so much for your help!
