### ISSUE TITLE
Reported API version headers report incorrect supported API version

### ISSUE THREAD

**Issue by bascoder** [microsoft/aspnet-api-versioning#679]
In my `Startup.cs` I configure the API versioning as following:

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddApiVersioning(config =>
    {
        config.DefaultApiVersion = new ApiVersion(1, 0);
        config.AssumeDefaultVersionWhenUnspecified = true;
        config.ReportApiVersions = true;
        config.ApiVersionReader = new HeaderApiVersionReader("x-api-version");
    });

    services.AddControllers();
}
``` 

Note that I set the `ReportApiVersions` option to `true`, so it responds with the `api-supported-versions` and `api-deprecated-versions` headers.

As reproduction case I setup the following controller:

```cs
[Route("api/[controller]")]
[ApiController]
public class ValuesController : ControllerBase
{
    [HttpGet("A")]
    [ApiVersion("1.0")]
    public IActionResult GetA()
    {
        return Ok("A @v1.0");
    }

    [HttpGet("B")]
    [ApiVersion("1.0", Deprecated = true)]
    public IActionResult GetBOld()
    {
        return Ok("B @v1.0");
    }

    [HttpGet("B")]
    [ApiVersion("2.0")]
    public IActionResult GetB()
    {
        return Ok("B @v2.0");
    }
}
```

When I call the endpoints I get the following response headers:
```
api-supported-versions: 1.0, 2.0
api-deprecated-versions: 1.0
```

However these headers are **invalid** for endpoint A because it doesn't have a version 2.0.
Here is the output of cURL:

```
$ curl --request GET https://localhost:5001/api/values/a --insecure -i

HTTP/2 200
date: Thu, 22 Oct 2020 09:16:03 GMT
content-type: text/plain; charset=utf-8
server: Kestrel
api-supported-versions: 1.0, 2.0
api-deprecated-versions: 1.0
```

When I call endpoint A with the version 2 header I get the following results:
```
$ curl --request GET --url https://localhost:5001/api/values/a --header 'x
-api-version: 2.0' --insecure -i

HTTP/2 400
date: Thu, 22 Oct 2020 09:18:15 GMT
content-type: application/json; charset=utf-8
server: Kestrel
api-supported-versions: 1.0, 2.0
api-deprecated-versions: 1.0

{"error":{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI 'https://localhost:5001/api/values/a' does not support the API version '2'.","innerError":null}}
```

This result is expected when knowing the code. But it's strange behaviour because it tells `api-supported-versions: 1.0, 2.0`, so for an external developer it's very confusing to consume this API.

----
System information:
Blank ASP.NET Core web API template on .NET Core 3.1
Microsoft.AspNetCore.Mvc.Versioning version 4.1.1

**Comment by commonsensesoftware** [comment]
This is the expected, default behavior. The reported versions are an aggregation of all possibilities. There's no grouping by segment or method. However, the response will be 405 vs 400 for an unsupported method.

The reported versions are meant to be what's possible for a resource (e.g. controller), not individual actions. A client wanting to know the available versions might send

```http
OPTIONS /api/values HTTP/2
host: localhost
api-supported-versions: 2.0
api-deprecated-versions: 1.0
```

Clients that care might check for deprecation and plan to update. Policy is not conveyed by reported versions. 

It's easy to go cross-eyed when interleaving. While it's possible, API sets are typically not defined by individual actions. They are most often additive or updated and occasionally subtractive.

**Comment by bascoder** [comment]
> 
> 
> This is the expected, default behavior. The reported versions are an aggregation of all possibilities. There's no grouping by segment or method. However, the response will be 405 vs 400 for an unsupported method.
> 
> The reported versions are meant to be what's possible for a resource (e.g. controller), not individual actions. A client wanting to know the available versions might send
> 
> ```httpspec
> OPTIONS /api/values HTTP/2
> host: localhost
> api-supported-versions: 2.0
> api-deprecated-versions: 1.0
> ```
> 
> Clients that care might check for deprecation and plan to update. Policy is not conveyed by reported versions.
> 
> It's easy to go cross-eyed when interleaving. While it's possible, API sets are typically not defined by individual actions. They are most often additive or updated and occasionally subtractive.

So if I understand it correctly you see `values` as a single resource, and `A` and `B` could just be route parameters.
That's why they could support the same API version.

In my case `A` and `B` are sub-resources of `values`. So to get correct headers for my case I moved them to separate controllers:

```cs
[Route("api/values")]
[ApiController]
public class ValuesAController : ControllerBase
{
    [HttpGet("A")]
    [ApiVersion("1.0")]
    public IActionResult GetA()
    {
        return Ok("A @v1.0");
    }
}

[Route("api/values")]
[ApiController]
public class ValuesBController : ControllerBase
{
    [HttpGet("B")]
    [ApiVersion("1.0", Deprecated = true)]
    public IActionResult GetBOld()
    {
        return Ok("B @v1.0");
    }

    [HttpGet("B")]
    [ApiVersion("2.0")]
    public IActionResult GetB()
    {
        return Ok("B @v2.0");
    }
}
```

----

Now when I call `values/a` with cURL I get the expected headers:

```
$ curl --request GET --url https://localhost:5001/api/values/a --insecure -i
HTTP/2 200
date: Sat, 24 Oct 2020 10:03:32 GMT
content-type: text/plain; charset=utf-8
server: Kestrel
api-supported-versions: 1.0
```

**Comment by commonsensesoftware** [comment]
Correct. _Could_ is the magic word. Grouping and collation can be tricky. It's easy for humans, but not code. The routing system just matches templates to implementation code. This is quite difficult to do any grouping with. The only guaranteed thing is the logical controller name. If you want `api/values` more as a prefix, then splitting them apart as you've done is a pretty reasonable way to do it.
