### ISSUE TITLE
Ability to configure Conventions in a non-generic way

### ISSUE THREAD

**Issue by Broodja** [Microsoft/aspnet-api-versioning#68]
Maybe I'm looking from the wrong angle, so I'll describe my scenario first.
I have a wide set of API controllers for different versions (e.g. v1, v2, v3).
What I'm trying to achieve is configure versioning depending on namespace/typename/whatever.
Expected configuration code might look like this:

    foreach (var controllerType in controllerTypes)
    {
        if (controllerType.Name.Contains("v1"))
        {
            options.Conventions.Controller(controllerType).HasApiVersion(new ApiVersion(1, 0));
        }
    }

However I've found no approach except configuring each controller one by one (either via conventions or attributes).
Are there any elegant solution for this?

**Comment by commonsensesoftware** [comment]
Succinctly, I'll say that out-of-the-box - no. Individual services (e.g. controllers) require that API versioning be explicit per controller.  This is the only way to reliably ensure things map the right way. The only exception is the implicit matching for the _default_ API version.  This behavior, however, is primarily meant to support backward compatibly once you opt into API versioning. To keep things unambiguous, there can only be one use case that supports this behavior.

The underlying code does not explicitly reply on attributes or conventions.  It's really looking for implementations of **IApiVersionProvider**.  You can easily extend the built-in attributes or you can define your own attributes that implement this interface.  The [extensions and customizations](../wiki/Extensions-and-Customizations) topic describes how this can be done.  You can also choose to inherit from [ApiVersionsBaseAttribute](../blob/master/src/Common/Versioning/ApiVersionsBaseAttribute.cs) and implement **IApiVersionProvider**. It may also be to achieve your goals using a custom **IApiVersionSelector**.

Hopefully, this helps and gets you on your way. Keep in mind that it's critical that when the library asks what versions a controller supports, this can be retrieved in an unambiguous way.

**Comment by Broodja** [comment]
Thanks for clarification! **IApiVersionProvider** should be an answer, even it's not as straightforward as I wish.
