### ISSUE TITLE
issue after migration web API Core 1.0 to 3.1

### ISSUE THREAD

**Issue by Naveen29** [microsoft/aspnet-api-versioning#681]
Hi,

We have developed out application using asp.net core 1.0 for UI and Web Api with Core 1.0, and it was working fine, now we have planed to migrate Web Api to 3.1 and we have not migrated UI application. so now when we call the API from UI application i getting error like , we are not getting header values and even model values are null,

But when we try to call the api 3.1 from postman it working fine and able access the methods.

what can we the issue ?

**Comment by commonsensesoftware** [comment]
So things work if you use Postman, but not your app? Some significant changes to routing have been made since 1.0. It sounds like it may be an issue with the code. Do you have more details or a repro to share?

**Comment by commonsensesoftware** [comment]
We're you able to get things working? Can you provide some additional context if not?

**Comment by Naveen29** [comment]
Works fine now , changed few changes with startup.cs
