### ISSUE TITLE
Is possible set versioning on route as optional?

### ISSUE THREAD

**Issue by daviddelucca** [microsoft/aspnet-api-versioning#683]
Hey there!

I have set an api versioning on my routes and it's working smooth:

```
using System.Net;
using Microsoft.AspNetCore.Mvc;

namespace xpto.Controllers
{
    [Route("{version:apiVersion}/[controller]")]
    [ApiVersion("1.0")]
    [ApiController]
    public class HealthController : ControllerBase
    {
        [HttpGet]
        [ProducesResponseType((int)HttpStatusCode.OK)]
        public IActionResult Get()
        {
            return Ok();
        }
    }
}
```

```
            services.AddApiVersioning(config =>
            {
                config.DefaultApiVersion = new ApiVersion(1, 0);
                config.AssumeDefaultVersionWhenUnspecified = true;
                config.ReportApiVersions = true;
            });
```

Now my routes only works If I send the api version `http://localhost:500/1.0/health`. Is there any way to let the version as optional parameter? I would like to keep calling `http://localhost:500/health` and handle it as 1.0 default version.

Thank in advance.

**Comment by commonsensesoftware** [comment]
No... And yes.

This is one of the many issues of versioning by URL segment aside from being the least RESTful. Remember that the path, the whole path, is the identifiier of a resource. It, therefore, makes sense why you can't have an optional parameter in the middle. More technically, the routing system only allows optional parameters at the end of the path. That is intrinsic to ASP.NET and transcends API Versioning.

The way you can make it work is to define 2 routes: one with the version and one without. Essentially there are 2 _indentifiers_. The drawback is this second, default route may need to _float_ around if you change what the default is. There's more details in the known limitations section of the wiki.

I'd be remiss if I didn't point out that this is the only style of versioning that has this problem. All other methods have stable paths across versions. If you have the option, consider an alternate style.

**Comment by commonsensesoftware** [comment]
Did this sufficiently answer your question? Did you have additional questions?

**Comment by daviddelucca** [comment]
Hey there!

Sorry for lately answer!

yea, it's sufficient and thank for explaning :)
