### ISSUE TITLE
Versioning support based on Header

### ISSUE THREAD

**Issue by shinkarmv** [microsoft/aspnet-api-versioning#687]
I went through the code and wiki section but do not found the versioning support based on header.
Is there any reason behind it? any plan to integrate in near future?

**Comment by commonsensesoftware** [comment]
In reviewing this, you are right. There's _mention_ of versioning by header, but no actual documentation. It's fully supported and available if it's an option you want to use. I've added a [wiki page](../wiki/Versioning-by-Header) and other links to make it more discoverable.

There isn't anything all that special about versioning by header. You need only use the [HeaderApiVersionReader](.../wiki/API-Version-Reader#header-api-version-reader) like so:

```c#
options => options.ApiVersionReader = new HeaderApiVersionReader( "api-version" );
```

You can compose multiple styles of versioning using `ApiVersionReader.Combine`. The default configuration combines the query string and URL segment methods as they are the most common developer choices (even though URL segment is worse one they can choose).

**Comment by shinkarmv** [comment]
Thank you 👍
