### ISSUE TITLE
Need some help understanding IUrlHelper behaviour when using ApiVersioning

### ISSUE THREAD

**Issue by adrian-at-dmi** [microsoft/aspnet-api-versioning#688]
Hi,

I have been toying with the IUrlHelper interface in conjunction with the ApiVersioning package and came across the following scenario, which I fail to understand at the moment. I created the standard Web API project using Visual Studio 2019 and ASP.NET Core 3.1 (which contains a `WeatherForecastController` by default). I modified the `Startup` class to use ApiVersioning:

```csharp
public class Startup
{
	public Startup(IConfiguration configuration)
	{
		Configuration = configuration;
	}

	public IConfiguration Configuration { get; }

	// This method gets called by the runtime. Use this method to add services to the container.
	public void ConfigureServices(IServiceCollection services)
	{
		services.AddControllers();

		// here
		services
			.AddApiVersioning(options =>
			{
				options.ApiVersionReader = new UrlSegmentApiVersionReader();
				options.RegisterMiddleware = true;
			});
	}

	// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
	public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		if (env.IsDevelopment())
		{
			app.UseDeveloperExceptionPage();
		}

		app.UseHttpsRedirection();

		app.UseRouting();

		app.UseEndpoints(endpoints =>
		{
			endpoints.MapControllers();
		});
	}
}
```

In order to add URLs to the api results, I added two additional `string` Properties (`Get` and `Delete`) to the `WeatherForecast` class:

```csharp
public class WeatherForecast
{
	public DateTime Date { get; set; }
	public int TemperatureC { get; set; }
	public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
	public string Summary { get; set; }

	// here
	public string Get { get; set; }
	public string Delete { get; set; }
}
```

Inside the `WeatherForecastController` I generate links for the `Get` and `Delete` actions, when calling `GET api/v2/WeatherForecast`:

```csharp
[ApiController]
[ApiVersion("2")]
[Route("api/v{version:apiVersion}/[controller]")]
public class WeatherForecastController : ControllerBase
{
	private static readonly string[] Summaries = new[]
	{
		"Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
	};

	private readonly ILogger<WeatherForecastController> _logger;

	public WeatherForecastController(ILogger<WeatherForecastController> logger)
	{
		_logger = logger;
	}

	[HttpGet]
	public IEnumerable<WeatherForecast> Get()
	{
		var rng = new Random();
		return Enumerable.Range(1, 5).Select(index => new WeatherForecast
		{
			Date = DateTime.Now.AddDays(index),
			TemperatureC = rng.Next(-20, 55),
			Summary = Summaries[rng.Next(Summaries.Length)],

			// here
			Get = Url.Action(nameof(WeatherForecastController.Get), "WeatherForecast", new { id = 1 }, "https"),
			Delete = Url.Action(nameof(WeatherForecastController.Delete), "WeatherForecast", new { id = 1 }, "https"),
		})
		.ToArray();
	}

	[HttpGet]
	[Route("{id}")]
	public IActionResult Get([FromRoute] int id)
	{
		return NoContent();
	}

	[HttpDelete]
	[Route("{id}")]
	public IActionResult Delete([FromRoute] int id)
	{
		return NoContent();
	}
}
```

The result is:

```json
[
    // ... additional entries left for readabilty
    {
        "date": "2020-11-06T08:04:26.8129533+01:00",
        "temperatureC": -8,
        "temperatureF": 18,
        "summary": "Sweltering",
        "get": "https://localhost:5001/api/v2/WeatherForecast/1",
        "delete": null
    }
]
```

I fail to understand why the `"delete"` property is `null` in this instance. To my understanding the link should the the same as in `"get"`. After a lot of trial and error I realized, that adding a `version` property to the `routeValues` of `Url.Action()` fixes the problem, meaning

```csharp
// ...
Delete = Url.Action(nameof(WeatherForecastController.Delete), "WeatherForecast", new { id = 1, version = "2" }, "https"),
// ...
```

results in

```json
[
    // ... additional entries left for readabilty
    {
        "date": "2020-11-06T08:04:26.8129533+01:00",
        "temperatureC": -8,
        "temperatureF": 18,
        "summary": "Sweltering",
        "get": "https://localhost:5001/api/v2/WeatherForecast/1",
        "delete": "https://localhost:5001/api/v2/WeatherForecast/1"
    }
]
```

But why? 😅 Why can I omit the `version` when generating the url for the `Get` but not the `Delete` action? Any help is much appreciated.

**Comment by commonsensesoftware** [comment]
This is a good question and one that people who version this way have asked many times. In short, the **IUrlHelper** is doing exactly what it's supposed to do - by default. If the route template was `api/weatherforecast/{id}/today`, what would you expect to happen if you don't provide `{id}`? Surprise, the result will be `null`. But now for why...

ASP.NET makes very few assumptions about incoming route values. After review the source, I believe the only two route parameters that will automatically handle as _ambient values_ are `controller` and `action`. This is in stark contrast to how things worked in Web API (if you ever used it). A key part of this challenge is that ASP.NET doesn't know that the route parameter key/value pairs are and, best as I can tell, does not persist and hold on to them throughout the pipeline. Even API Versioning doesn't know what the user-defined route parameter name will be until the **ApiVersionRouteConstraint** is executed. You've defined it as `version` above, but that's not a hard requirement.

This issue has long been a pain point for people versioning by URL segment. It _shouldn't_ really be a surprise if a route parameter isn't provided, but there is definitely an expectation that it should be _automagically_ filled in. It took a very long time to figure exactly how this _could_ be made to work and I'm happy to report that there is a permanent solution. Starting 4.2.0, things will work as expected without having to provide the API version value. When (and only when) you version by URL segment, API Versioning will decorator the default **IUrlHelper** and inject the API version as a known route value. This feature is currently in the `rc.2` package, which is about to be promoted to full release. Things will continue to work in the next release, even if you explicitly provide the value (which is never wrong).

There's a couple of ways you can include the API version explicitly the route values for the **IUrlHelper**. The simplest and preferred method would be to use the _model binding_ support. Simply add the API version method parameter and it will be _magically_ provided for you. For example:

```c#
[HttpDelete]
[Route("{id}")]
public IActionResult Delete([FromRoute] int id, ApiVersion version) => NoContent();
```

You'll want to use `version.ToString()` as the value or ASP.NET will try to _explode_ the object apart by its properties, which is not what you want. Alternate methods of getting the value include using `HttpContext.GetRequestedApiVersion()` or the source of all values via **IApiVersioningFeature** which you can get from `HttpContext.Features`.

Hopefully that clears things up, explains why things behavior the way they do, and a path forward.

>Aside: I'd be remiss if I didn't also mention this is another (bad) side effect of versioning by URL segment, which is the least RESTful. Any other method of versioning does not have this issue. If you have the control and ability, you might consider another versioning style. I realize that's not always possible, but if you care about or want to be RESTful, then there's a mind field I'm happy to help people navigate.

**Comment by adrian-at-dmi** [comment]
Thank you very much for your answer and your hard work @commonsensesoftware . Much appreciated.

Your `api/weatherforecast/{id}/today` example is understandable. By not providing the `{id}` route value, I would indeed expect `IUrlHelper` to return `null`. It that sense not explicitly setting `{version}` when using `IUrlHelper` seems kind of nonsensical in retrospective. What threw me off - I guess - is the fact, that 
```csharp
Get = Url.Action(nameof(WeatherForecastController.Get), "WeatherForecast", new { id = 1 }, "https"),
```
was able to produce the valid URL, while 
```csharp
Delete = Url.Action(nameof(WeatherForecastController.Delete), "WeatherForecast", new { id = 1 }, "https"),
```
didn't.

Going forward I will use package version 4.2.0 for now as it fixes my "problem" and requires minimal rewriting (great timing btw 😅). Again thanks for the hard work.

P.S.: If you are up for it, I would very much like to hear your reasoning as to why URL segmented versioning is "bad" (or at least not RESTful) and what the benefits of the other methods are.

**Comment by commonsensesoftware** [comment]
Strange. I don't see how `Get` would ever work either. ¯\_ (ツ)_/¯

As soon as I get everything all caught up, I'm hoping to start blogging again. It's amazing to me how prolific versioning by URL segment is. I suspect a great many people have never read Fielding's dissertation or think it's some academic dogma that only needs to be pragmatically followed. REST is a set of constraints. It is the thing that has driven the success and evolution of HTTP. Fielding - himself - has said that if you don't follow all of the constraints, then you aren't implementing REST.

So what's wrong with the URL segment method? There are actually a great number of issues you may encounter, but the fundamental issue is that it violates the _Uniform Interface_ constraint. OK, but how? Using the current context, consider `api/v1/weatherforecast/42`. What is the _identifier_ here? 9 out of 10 people will say `42`. Bless humans; we're so _smart_. The identifier is actually `api/v1/weatherforecast/42`. The _Uniform Interface_ says that a resource is identified by a URI (or URL), which would be the _path_. This means that `api/v1/weatherforecast/42` versus `api/v2/weatherforecast/42` is two different identifiers and implies two different resources, but that's almost certainly not true. The real difference is typically the _representation_ of the source; for example, an attribute was added, removed, or renamed. REST already provides a way to deal with different representations - media types. Fielding claims the **only** way versioning should ever be done is by media type. There's several ways this could be achieved. This library supports it by way of media type parameter; for example, `application/json; v=2.0`. The GitHub API is one of the few well-known APIs I know of that versions by media type. The query string method tends to be the most pragmatic in terms of ease of use without breaking a constraint. A query parameter is not part of the path and, therefore, not part of the identifier.

That may seem pedantic, but there's other issues as well. The URL used by clients has to be changed every time a version changes. If you want to support independent service evolution and any form of HATEOAS, versioning by URL segment causes issues. Consider you have a _Order_ API (1.0, 2.0) which has a link to _Customer_ API (2.0, 3.0). If you request `v2/order/123`, which link to the customer should you return? `v2/customer/456`?  How does the server know that? What if the client is onboarded to 3.0 of the customer API? Ultimately, the server cannot know nor should impose version assumptions on the client. The client is required to indicate which version of a resource they want. It's no different than asking for `application/json` versus `application/xml`. Using `order/123` and `customer/456` is consistent across all versions. The client decides which one they want via other input such as media type, query string, or header.

Hopefully that puts a little perspective of some of the issues you can face with versioning by URL segment.

**Comment by commonsensesoftware** [comment]
Based on the age and activity of this issue, I believe it has now been resolved. If this didn't answer your questions or resolve your problem, feel free to reopen the issue or create a new one.
