### ISSUE TITLE
Consider improving the performance of Microsoft.AspNetCore.Mvc.Versioning.QueryStringApiVersionReader

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/aspnet-api-versioning#690]
The [`Read` method](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/QueryStringApiVersionReader.cs#L20) of [`Microsoft.AspNetCore.Mvc.Versioning.QueryStringApiVersionReader`](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/QueryStringApiVersionReader.cs#L12) [unconditionally instantiates an `HashSet<string>`](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/QueryStringApiVersionReader.cs#L27) regardless of having a version specified or not with the only purpose of [invoking `CollectionExtensions.EnsureZeroOrOneApiVersions`](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/QueryStringApiVersionReader.cs#L42).

`CollectionExtensions.EnsureZeroOrOneApiVersions` uses `Enumerable.SingleOrDefault` to return `null`, if the hash set is empty; and its single item if it isn't.

`Enumerable.SingleOrDefault` has optimizations for `IList<T>`, but not for `ICollection<T>`, which requires the instantiation and boxing of `HashSet<T>.Enumerator`.

All this could be optimized by only instantiating the `HashSet<string>` if 2 or more different versions are found and having an extension method to report the error that takes an `HashSet<string>` for the optimized construction of the list of versions.

**Comment by commonsensesoftware** [comment]
This is not an unreasonable enhancement. I've converted many iterator loops to indexing loops, but there's still a few left. This is was one of the earlier bits of code. I'll review all of the readers for potential optimization.

**Comment by commonsensesoftware** [comment]
This was a great observation and has been broadly integrated into all `IApiVersionReader` implementations, across all platforms. I've been continuing to look for unnecessary allocations and uses of `foreach`. If you find more, keep them coming. You were credited for this improvement in the latest release notes. Thanks again!
