### ISSUE TITLE
Failed to load API definition after publishing the SwaggerSample project into IIS

### ISSUE THREAD

**Issue by narsi24** [microsoft/aspnet-api-versioning#691]
Failed to load API definition after publishing the SwaggerSample project into IIS

Errors
Hide
 
Fetch error Not Found /swagger/v1/swagger.json

**Comment by anranruye** [comment]
i guess you make the project a subapplication in iis.
try 'swagger/v1/swagger.json' instead of '/swagger/v1/swagger.json'.
remove the first '/' character in the first string parameter of SwaggerEndpoint method.

**Comment by narsi24** [comment]
Thank you anranruye.
