### ISSUE TITLE
ApiVersion support for three decimals like 0.4.6 instead of 1.0

### ISSUE THREAD

**Issue by V4A001** [microsoft/aspnet-api-versioning#701]
Is it possible to extend to three decimals?

**Comment by V4A001** [comment]
https://semver.org/ 

`Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.`

**Comment by commonsensesoftware** [comment]
In the most technical sense, it is _possible_ to extend the **ApiVersion** class, but there are several places that are not easily swappable for a different implementation. Parsing is [currently] just done via a static method. This would need to be replaced with a swappable _service_. There are several other parts that most would consider too much effort to change. For example, **ApiVersion** supports comparisons, equality, and operator overloads. These would likely all need to be implemented on the subclass to function properly.

To clarify:

**_An API version is not a semantic version_**

A semantic version solves a completely different problem. An API version does not and cannot have a _range_. It **must** match exactly. _Any_ change in API version _can_ be a breaking change. The patch component is nonsensical to a client.

- **Major** - assumed to be a breaking change
- **Minor** - _any_ change, even additive, _can_ be a breaking change. the server cannot guarantee that all clients use a _tolerant reader_. while most clients will use tolerant readers and it is generally assumed that a client can handle additive changes, there is no guarantees that this is the case
- **Patch** - there is no visible change to the API from the client's perspective so this is completely irrelevant. a client should not be able to request a version of the API that only varies in runtime behavior

Something often overlooked in REST with HTTP is that HTTP **is** the API. HTTP methods are the _methods_. An API version tends to be far more about the format or shape of the messages passed to those methods. As such, there's really no place for a patch version within that lens. While minor versions are often backward-compatible, it should never been assumed. This is one reason why ranges and loose mappings are not allowed by default; the client should get exactly what they ask for or return an appropriate response. Minor version changes _can_ break consumers of other programming constructs too. For example, in many languages, adding a member to an existing interface will break older implementations that do not implement it. This is just one example of an additive change breaking a client.

While these are all pretty sensible rules, they aren't _my_ rules. These rules all derive from the [Microsoft REST API Guidelines](https://github.com/microsoft/api-guidelines/) from the very beginning. At some point, I may add a feature that would enable swapping out this part of the system, but it's deeply entrenched at this point and would require a significant refactor. Only a handful of people have ever asked for this and usually they ask for it for one of the following reasons:

1. My existing API has a version, but it's a different format
2. I want my API version to be a semantic version
3. I want my API version to support ranges
4. I subjectively want my API version to use a different format

`2` and `4` are effectively out of the picture at this point. There are some ways you can achieve `3` that you can find in the old issues as well as an example in the [3rd party extensions](../wiki/Extensions-and-Customizations#third-party-extensions). For `1`, my suggestion is to incremental up to a version that drops the patch version. If you _really_ need or want the patch version, you can still return that in a HTTP header or something.

This may not have been the answer you were looking for, but I hope that helps clear things up.

**Comment by commonsensesoftware** [comment]
Given the amount of idle time on this issue, it would seem you have accepted this answer.

There _might_ be a scenario sometime in the future where the API Version can be fully swapped out. It currently requires significant changes. Operator overloads are used heavily and they cannot be applied to interfaces.

It is technically possible to extend the **ApiVersion** class. There are a lot of other moving parts such as parsing and formatting. Changing the behavior will be nontrivial.
