### ISSUE TITLE
Strange ApiVersionUnspecified error in 5.0.0-preview.2

### ISSUE THREAD

**Issue by yjagota** [microsoft/aspnet-api-versioning#707]
Hello,

I updated a core app to v5 from 3.1 and I am encountering a very strange case of ApiVersionUnspecified error. Here is the controller:

```
[ApiVersionNeutral]
[Route("api/fend")]
[ApiController]
public class FrontEndController : ControllerBase
{
	[HttpGet]
	[Route("charts/alllic")]
	public IActionResult GetDashboardLicenseData() { ... }

	[HttpGet]
	[Route("charts/clientlicstats")]
	public IActionResult GetClientLicenseStatistics() { ... }

	[HttpGet]
	[Route("charts/reqstats")]
	public IActionResult GetDashboardRequestData() { ... }
}
```

The strange thing is, only one method is returning ApiVersionUnspecified. See the following fiddler output:

GetDashboardLicenseData & GetDashboardRequestData run fine:
![2020-12-05 17_35_34-Progress Telerik Fiddler Web Debugger](https://user-images.githubusercontent.com/120934/101242725-453ce800-3721-11eb-8591-6e0a3364eec1.png)

GetClientLicenseStatistics causes an ApiVersionUnspecified exception:
![2020-12-05 17_35_47-Progress Telerik Fiddler Web Debugger](https://user-images.githubusercontent.com/120934/101242732-4a9a3280-3721-11eb-8232-30f4147b529e.png)

The same happens with many other methods. Some methods run fine and others throw an ApiVersionUnspecified exception. I checked multiple times but I don't think it is an error from my end. This only happened after I updated from v4.2.0 to v5.0.0-preview.2.

Any help will be really appreciated.
Thanks & Regards,
Yogesh.

**Comment by commonsensesoftware** [comment]
If I'm honest here, this controller is authored strangely to me, but it _should_ work. I suspect the issue may be that the controller name does not match. This is really the **only** piece of information available to group APIs by.

Here's what I would expect to work:

```c#
[ApiVersionNeutral]
[ApiController]
[Route("api/fend/[controller]")]
public class ChartsController : ControllerBase
{
	[HttpGet("alllic")]
	public IActionResult GetDashboardLicenseData() { ... }

	[HttpGet("clientlicstats")]
	public IActionResult GetClientLicenseStatistics() { ... }

	[HttpGet("reqstats")]
	public IActionResult GetDashboardRequestData() { ... }
}
```

The fact that 2 of 3 the routes routes work as expected is bizarre. Do you have a repro you can share? It would be useful in tracking down where the issue occurs.

**Comment by yjagota** [comment]
I found the issue. Due to the update, an error on Linux systems was introduced. As all globally unhandled exceptions were forwarded to a controller which did not have any api version related attributes, the pipeline was throwing ApiVersionUnspecified for the error handling controller and not the controller mentioned in the original post. Apologies for the confusion. Closing the thread.
