### ISSUE TITLE
SwaggerDefaultValues doesn't set the default value for boolean properties correctly

### ISSUE THREAD

**Issue by icnocop** [microsoft/aspnet-api-versioning#717]
Hi.

[.\samples\aspnetcore\SwaggerODataSample\SwaggerDefaultValues.cs](https://github.com/microsoft/aspnet-api-versioning/blob/master/samples/aspnetcore/SwaggerODataSample/SwaggerDefaultValues.cs) assumes properties are strings and this causes some issues.

For example:

1. Run the `samples\aspnetcore\SwaggerODataSample` project
2. Select definition V3
3. Expand `GET ​/api​/Acme​/Products`
4. Click `Try it out`
5. Click `Execute`
6. Notice the `$count` parameter is required to be manually set to `true` or `false`.

**Comment by icnocop** [comment]
I found a solution to this problem here:
https://github.com/microsoft/aspnet-api-versioning/issues/429#issuecomment-605402330

**Comment by commonsensesoftware** [comment]
I'm sure why this issue didn't auto-close, but I believe you PR fixes this issue. If I'm mistaken, please re-open. Thanks
