### ISSUE TITLE
Wiki correction

### ISSUE THREAD

**Issue by Sa1Gur** [microsoft/aspnet-api-versioning#724]
In the https://github.com/microsoft/aspnet-api-versioning/wiki/API-Version-Reader HeaderApiVersionReader doesn't have Headers now. The correct name is HeaderNames.
I would gladly do it by PR, but git link to Wiki isn't working for me

**Comment by commonsensesoftware** [comment]
Ah ... yes ... good catch. This was mistake in the [composition](../wiki/API-Version-Reader#api-version-reader-composition--110-) section. I must have copy and pasted it from the older documentation when it **was** still `Headers`. I'm not 100% sure where the wiki docs are stored, but it doesn't seem you can do PRs for them like GH-Pages or other parts of the repo. For now the best option is to report it as an issue. Thanks for calling it out. I've made the appropriate update. If you find more, please call them out. :)
