### ISSUE TITLE
The sample code should show sample calls

### ISSUE THREAD

**Issue by agrabhi** [Microsoft/aspnet-api-versioning#76]
The sample code on page https://github.com/Microsoft/aspnet-api-versioning/wiki/How-to-Version-Your-Service should show the sample calls also for the controller.

**Comment by commonsensesoftware** [comment]
Sample call cannot be shown here without a lot of content.  The sample URLs are completely dependent upon which method of API versioning your service uses.  There are already topics for API versioning via the query string and URL path that do provide sample calls. I've updated this landing page with a small section that describes the out-of-the-box API versioning methods and then links to the specific topics that include the details, including sample URLs.
