### ISSUE TITLE
Error "Multiple controller types were found that match the URL with url root mapping

### ISSUE THREAD

**Issue by agrabhi** [Microsoft/aspnet-api-versioning#77]
The code on the link https://github.com/Microsoft/aspnet-api-versioning/wiki/Versioning-via-the-URL-Path

gives following error 

GET http://localhost:21593/api/v2/helloworld
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Multiple controller types were found that match the URL. This can happen if attribute routes on multiple controllers match the requested URL.\r\n\r\nThe request has found the following matching controller types: \r\nSampleCpim.HelloWorldController\r\nSampleCpim.HelloWorld2Controller",
  "ExceptionType": "System.InvalidOperationException",
  "StackTrace": "   at System.Web.Http.Dispatcher.DefaultHttpControllerSelector.GetDirectRouteController(IHttpRouteData routeData)\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerSelector.SelectController(HttpRequestMessage request)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

here is webapi.config 
public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services

            // Web API routes
           // config.MapHttpAttributeRoutes();

            var constraintResolver = new DefaultInlineConstraintResolver()
            {
                ConstraintMap =
                        {
                            ["apiVersion"] = typeof( ApiVersionRouteConstraint )
                        }
            };
            config.MapHttpAttributeRoutes(constraintResolver);

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
    }

**Comment by agrabhi** [comment]
I found the reason but not closing the issue for documentation correction
I needed to add  config.AddApiVersioning(); in my register function.
the sample needs to be updated.

**Comment by commonsensesoftware** [comment]
The _Quick Starts_ and the [examples](../tree/master/samples) where meant to provide the complete setups and configurations required. These areas were intended to restrict the content to the setup and configuration differences to highlight specific changes. Nevertheless, it doesn't matter if I understand the content, it matters if everyone else understands it.  If this small update brings more clarity, great. I've updated the topic with the additional method calls as requested.
