### ISSUE TITLE
Returns UnsupportedApiVersion on incorrect route parameter

### ISSUE THREAD

**Issue by snebjorn** [Microsoft/aspnet-api-versioning#95]
Given this controller

```
[ApiVersion("1.0")]
[RoutePrefix("api/v{version:apiVersion}/test")]
public class TestController : ApiController
{
	[Route({id:int})]
	public IHttpActionResult Get(int id) => Ok();
}
```
And calling it with incorrect parameters like so: GET /api/v1/test/foo

I would expect a 404 result like so:

```
{
  "message": "No HTTP resource was found that matches the request URI 'https://localhost/api/v1/test/foo'."
}
```

But I'm getting UnsupportedApiVersion instead.

```
{
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The HTTP resource that matches the request URI 'https://localhost/api/v1/test/foo' does not support the API version '1'.",
    "innerError": {
      "message": "No route providing a controller name with API version '1' was found to match request URI 'https://localhost/api/v1/test/foo'."
    }
  }
}
```

This is misleading for API consumers, as the version is correct but the URL isn't. Please help :)

**Comment by snebjorn** [comment]
Thanks for the details response. It makes a lot of sense. I'll have a look at the IActionFilter solution :)

**Comment by commonsensesoftware** [comment]
No problem. Some scenarios are tricky and/or gray. The goal is certainly to embrace the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Feedback and discussion with the community helps hash these things out. Keep it coming. Thanks.

**Comment by snebjorn** [comment]
Instead of making an IActionFilter you can remove the type constraint from the route and it'll work as (I) expected :)

```
[ApiVersion("1.0")]
[RoutePrefix("api/v{version:apiVersion}/test")]
public class TestController : ApiController
{
	[Route({id})] // <-- removed type
	public IHttpActionResult Get(int id) => Ok();
}
```

Now calling `GET /api/v1/test/foo` gives a `400 Bad Request`

```
{
  "message": "The request is invalid.",
  "messageDetail": "The parameters dictionary contains a null entry for parameter 'id' of non-nullable type 'System.Int32' for method 'System.Web.Http.IHttpActionResult Get(Int32)' in 'WebApplication.TestController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter."
}
```

👍 🙌  🍾 

@commonsensesoftware seems a similar scenario is handled, perhaps it could be expanded to include routes with type constraint?

**Comment by commonsensesoftware** [comment]
The behavior you are seeing is purely how Web API handles things out-of-the-box.  You can totally make it work this way if you want.  There reason I would suggest something like an **IActionFilter** or model binder for the parameter is if you want more control over what the response will be.  You can even make the **id** a string and then do your own validation and return 400 if it doesn't meet your criteria.  I hope that helps.
