### ISSUE TITLE
Web API with same route but different versioning- unable to generate multi version swagger document

### ISSUE THREAD

**Issue by Anjayg** [Microsoft/aspnet-api-versioning#98]
we adopted versioning approach for our public api and version can be accepted via query string or headers. below are same resource but different store to connect data. 

[ApiVersion("1")]
[RoutePrefix("api/items")]
items1controller: apicontroller 
{
GET api/items?api-version =1 
}

[ApiVersion("2")]
[RoutePrefix("api/items")]
items2controller: apicontroller 
{
GET api/items?api-version =2
}

api/items/1?api-version =1
api/items/1?api-version 2

we are unable to generate swagger documentation for multi version api. I think this question was asked many times in different forum. but looking for some solution/direction so that api explorer does not break and we are able to generate swagger document.

**Comment by commonsensesoftware** [comment]
Have you looked at #59, #60, and their related links? First-class support for documentation is on the roadmap, but getting out bugs and updates are the highest priority for me. I've almost got all of the other open issues burned down and then I'll have time to focus a lot more effort to formally supporting documentation.  Until then, there have been a lot of discussions, code examples, and community ad hoc implementations.

If there are questions that you can't find answered in any of the questions, then I'll answer what I can for you. Thanks for your patience.

**Comment by commonsensesoftware** [comment]
Since there don't seem to be any other questions on this topic and I've already linked the existing, active issues related to this topic, I'm going to close this issue out. I am actively looking into supporting the required documentation features for Swagger, etc. Follow the linked issues for updates. Thanks for your support and interest in the success of the project.

**Comment by Berezhnyk** [comment]
I was got the same bug

**Comment by commonsensesoftware** [comment]
Can you elaborate? Are you using Swagger? Have you included the API Explorer package for API Versioning? All of this information is documented in the [API Documentation](../wiki/API-Documentation) wiki topic. The NuGet packages, samples, and quick starts all have links on the home page as well.

Let me know how else I can help.
